force-app/main/default/objects/Copilot_Prompt__c/Copilot_Prompt__c.object-meta.xml
<CustomObject>
    <label>Copilot Prompt</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Copilot Prompt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copilot Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Copilot_Prompt__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project__c</fullName>
                <label>Project</label>
            </value>
            <value>
                <fullName>Project_Feature__c</fullName>
                <label>Project Feature</label>
            </value>
            <value>
                <fullName>Phase__c</fullName>
                <label>Phase</label>
            </value>
            <value>
                <fullName>Work_Item__c</fullName>
                <label>Work Item</label>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>EmailMessage</fullName>
                <label>Email Message</label>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Copilot_Prompt__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CopilotController.cls
public with sharing class CopilotController {
    
    @AuraEnabled(cacheable=true)
    public static String getContext(String objectApiName, Id recordId) {
        try {
            CopilotContext context = CopilotContextProvider.getCopilotContext(objectApiName, recordId);
            return context.getContext();
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Copilot_Prompt__c> getPrompts(String objectApiName) {
        try {
            List<Copilot_Prompt__c> prompts = [SELECT Id, Prompt__c FROM Copilot_Prompt__c WHERE Object__c = :objectApiName];
            if (prompts.size() == 0){
                return new List<Copilot_Prompt__c>();
            }
            return prompts;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled
    public static void handleAction(String objectApiName, Id recordId, String fieldName, String value) {
        try {
            CopilotFieldUpdateService.updateField(objectApiName, recordId, fieldName, value);
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }     
    }
}