force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Project_Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Meeting</label>
    <referenceTo>Project_Meeting__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Meeting__c/Project_Meeting__c.object-meta.xml
<CustomObject>
    <label>Project Meeting</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Project Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Meeting__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Meetings</relationshipLabel>
    <relationshipName>Project_Meetings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WeeklyStatusReportAction.cls
global class WeeklyStatusReportAction {
    @InvocableMethod(label='Save Weekly Status Reports')
    global static void saveWeeklyStatusReports(List<Id> meetingIds) {
        List<ContentVersion> contentVersionsToAdd = new List<ContentVersion>();
        List<ContentDocumentLink> contentDocumentLinksToAdd = new List<ContentDocumentLink>();
        Map<String, Id> pathToMeetingIdMap = new Map<String, Id>();

        List<Project_Meeting__c> meetingList = [SELECT Id, Name, Project__c, Project__r.Name FROM Project_Meeting__c WHERE Id IN :meetingIds];

        if (meetingList.size() == 0) {
            return;
        }

        String reportDate = Datetime.now().format('yyyy-MM-dd');

        for (Project_Meeting__c meeting : meetingList) {
            PageReference pageRef = Page.WeeklyStatusReport;
            pageRef.getParameters().put('id', meeting.Project__c);
            pageRef.setRedirect(true);

            ContentVersion contentVersion = new ContentVersion();
            contentVersion.ContentLocation = 'S';
            contentVersion.PathOnClient = 'weekly-status-report-' + meeting.Name + '-' + reportDate + '.pdf';
            contentVersion.Title = 'Weekly Status Report - ' + meeting.Project__r.Name + ' - ' + reportDate;

            if (Test.isRunningTest()) {
                contentVersion.VersionData = Blob.valueOf('Test');
            } else {
                contentVersion.VersionData = pageRef.getContent();
            }

            contentVersionsToAdd.add(contentVersion);
            pathToMeetingIdMap.put(contentVersion.PathOnClient, meeting.Id);
        }

        insert contentVersionsToAdd;

        Set<Id> contentVersionIds = new Set<Id>();

        for (ContentVersion contentVersion : contentVersionsToAdd) {
            contentVersionIds.add(contentVersion.Id);
        }

        List<ContentVersion> contentVersionList = [SELECT PathOnClient, ContentDocumentId FROM ContentVersion WHERE Id IN :contentVersionIds];

        for (ContentVersion contentVersion : contentVersionList) {
            ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
            contentDocumentLink.LinkedEntityId = pathToMeetingIdMap.get(contentVersion.PathOnClient);
            contentDocumentLink.ContentDocumentId = contentVersion.ContentDocumentId;
            contentDocumentLink.shareType = 'V';

            contentDocumentLinksToAdd.add(contentDocumentLink);
        }

        insert contentDocumentLinksToAdd;
    }
}