force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Est_Cost__c.field-meta.xml
<CustomField>
    <fullName>Est_Cost__c</fullName>
    <formula>Total_Est__c *  Project__r.Proposal_Hourly_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Est. Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>65000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Est_Time__c.field-meta.xml
<CustomField>
    <fullName>Est_Time__c</fullName>
    <label>Est. Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Is_Optional__c.field-meta.xml
<CustomField>
    <fullName>Is_Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Separates the work item from the others, putting it in a &quot;Recommended Options&quot; section of the proposal and removes it from all the total estimates</inlineHelpText>
    <label>Is Optional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>999</defaultValue>
    <inlineHelpText>Lowest at the top</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProjectSummaryController.cls
public with sharing class ProjectSummaryController {
  @AuraEnabled(cacheable=true)
  public static List<Project_Feature__c> getRows(Id projectId) {
    try {
      return [
        SELECT
          Id,
          Project__c,
          Name,
          CurrencyIsoCode,
          Description__c,
          Est_Cost__c,
          (
            SELECT
              Id,
              Name,
              Feature__c,
              Subject__c,
              Description__c,
              Est_Time__c,
              Is_Optional__c
            FROM Work_Items__r
            ORDER BY Sort_Order__c
          )
        FROM Project_Feature__c
        WHERE Project__c = :projectId
        WITH SECURITY_ENFORCED
        ORDER BY Sort_Order__c
      ];
    } catch (Exception e) {
      throw AuraHandledExceptionFactory.create(e);
    }
  }

  @AuraEnabled
  public static void save(Id id, String field, String value) {
    try {
      Schema.SObjectType sobjectType = id.getSobjectType();
      Schema.DescribeSObjectResult objectDescribe = sobjectType.getDescribe(
        SObjectDescribeOptions.DEFERRED
      );
      Schema.DescribeFieldResult fieldDescribe = objectDescribe.fields.getMap()
        .get(field)
        .getDescribe();
      Schema.DisplayType dataType = fieldDescribe.getType();

      if (!objectDescribe.isUpdateable()) {
        throw new AuraHandledException('Object is not updateable');
      }

      if (!fieldDescribe.isUpdateable()) {
        throw new AuraHandledException('Field is not updateable');
      }

      SObject record = sobjectType.newSObject(id);

      if (dataType == Schema.DisplayType.DOUBLE) {
        record.put(field, Decimal.valueOf(value));
      } else if (dataType == Schema.DisplayType.BOOLEAN) {
        record.put(field, value == 'true');
      } else {
        record.put(field, value);
      }

      update record; // NOPMD - Suppress the false positive ApexCRUDViolation
    } catch (Exception e) {
      throw AuraHandledExceptionFactory.create(e);
    }
  }
}