force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Challenges__c.field-meta.xml
<CustomField>
    <fullName>Challenges__c</fullName>
    <label>Challenges</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0ea854</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>55c022</fullName>
                <label>Yellow-Green</label>
            </value>
            <value>
                <fullName>faf300</fullName>
                <label>Yellow</label>
            </value>
            <value>
                <fullName>faa001</fullName>
                <label>Yellow-Orange</label>
            </value>
            <value>
                <fullName>fa7900</fullName>
                <label>Orange</label>
            </value>
            <value>
                <fullName>fa2430</fullName>
                <label>Red-Orange</label>
            </value>
            <value>
                <fullName>fa2207</fullName>
                <label>Red</label>
            </value>
            <value>
                <fullName>b10f91</fullName>
                <label>Red-Purple</label>
            </value>
            <value>
                <fullName>5f2596</fullName>
                <label>Purple</label>
            </value>
            <value>
                <fullName>1d3c9e</fullName>
                <label>Blue-Purple</label>
            </value>
            <value>
                <fullName>2365b7</fullName>
                <label>Blue</label>
            </value>
            <value>
                <fullName>22afae</fullName>
                <label>Blue-Green</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Introduction__c.field-meta.xml
<CustomField>
    <fullName>Introduction__c</fullName>
    <label>Introduction</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Support_Type__c.field-meta.xml
<CustomField>
    <fullName>Support_Type__c</fullName>
    <label>Support Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectTestDataFactory.cls
@isTest
public class ProjectTestDataFactory {
    public static Id create(Id accountId) {
        return create(accountId, 'test project', ProjectStatusNames.Backlog);
    }

    public static Id create(Id accountId, String name, String status) {
        return create(accountId, name, status, Date.today(), (Date.today() + 28));
    }

    public static Id create(Id accountId, String name, String status, Date startDate, Date endDate) {
        Project__c project = new Project__c();
        project.Name = name;
        project.Account__c = accountId;
        project.Status__c = status;
        project.Introduction__c = 'test';
        project.Challenges__c = 'test';
        project.Payment_Terms__c = 'test';
        project.Start_Date__c = startDate;
        project.End_Date__c = endDate;
        project.Colour__c = ProjectColourNames.RED;
        project.Support_Type__c = 'MSA';
        insert project;
        return project.Id;
    }
}