force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Support_Type__c.field-meta.xml
<CustomField>
    <fullName>Support_Type__c</fullName>
    <label>Support Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
                <default>true</default>
                <label>Project</label>
            </value>
            <value>
                <fullName>Managed Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/RAID_Log__c.object-meta.xml
<CustomObject>
    <label>RAID Log</label>
    <nameField>
        <displayFormat>RAID-{000000}</displayFormat>
        <label>RAID Log Entry Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAID Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RAID_Log__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Risk</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Decision</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/recordTypes/Issue.recordType-meta.xml
<RecordType>
    <fullName>Issue</fullName>
    <active>true</active>
    <label>Issue</label>
</RecordType>

force-app/main/default/objects/RAID_Log__c/recordTypes/Risk.recordType-meta.xml
<RecordType>
    <fullName>Risk</fullName>
    <active>true</active>
    <label>Risk</label>
</RecordType>

force-app/main/default/classes/GetProjectRAIDLogsControllerTest.cls
@isTest
public with sharing class GetProjectRAIDLogsControllerTest {
  @testSetup
  static void setupTestData() {
    Account testAccount = new Account(Name = 'Test Account');
    insert testAccount;

    Project__c testProject = new Project__c(
      Name = 'Test Project',
      Account__c = testAccount.Id,
      Support_Type__c = 'MSA'
    );
    insert testProject;

    List<Raid_Log__c> testRaidLogs = new List<Raid_Log__c>{
      new Raid_Log__c(
        Status__c = 'Open',
        Type__c = 'Risk',
        Project__c = testProject.Id
      ),
      new Raid_Log__c(
        Status__c = 'Open',
        Type__c = 'Issue',
        Project__c = testProject.Id
      )
    };

    insert testRaidLogs;

    for (Integer i = 0; i < testRaidLogs.size(); i++) {
      if (i == 0) {
        testRaidLogs[i].Type__c = 'Risk';
      } else {
        testRaidLogs[i].Type__c = 'Issue';
      }
    }

    update testRaidLogs;
  }

  @isTest
  static void testGetRaidLogs() {
    // Arrange
    Project__c testProject = [
      SELECT Id
      FROM Project__c
      WHERE Name = 'Test Project'
      LIMIT 1
    ];

    GetProjectRAIDLogsController controller = new GetProjectRAIDLogsController();
    controller.projectId = testProject.Id;
    controller.logType = 'Risk';

    // Act
    Test.startTest();
    List<Raid_Log__c> raidLogs = controller.getRaidLogs();
    Test.stopTest();

    // Assert
    System.assertEquals(
      1,
      raidLogs.size(),
      'Expected one Raid Log to be returned'
    );
    System.assertEquals(
      'Risk',
      raidLogs[0].Type__c,
      'Raid log type does not match'
    );
  }

  @isTest
  static void testGetIsRaidLogsEmpty() {
    // Arrange
    Project__c testProject = [
      SELECT Id
      FROM Project__c
      WHERE Name = 'Test Project'
      LIMIT 1
    ];

    // Instantiate controller and set values
    GetProjectRAIDLogsController controller = new GetProjectRAIDLogsController();
    controller.projectId = testProject.Id;
    controller.logType = 'Assumption';

    // Act
    Test.startTest();
    // Test getIsRaidLogsEmpty method
    Boolean isRaidLogsEmpty = controller.getIsRaidLogsEmpty();
    Test.stopTest();

    // Assert
    System.assertEquals(
      true,
      isRaidLogsEmpty,
      'Expected getIsRaidLogsEmpty to return true'
    );
  }
}