force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to contract/terms and conditions signature from client</description>
    <label>Contract</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.RecordType.Name</field>
            <operation>equals</operation>
            <value>T&amp;M Terms</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Support_Type__c.field-meta.xml
<CustomField>
    <fullName>Support_Type__c</fullName>
    <label>Support Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
                <default>true</default>
                <label>Project</label>
            </value>
            <value>
                <fullName>Managed Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vendor</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Project__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Change Request contract for client signature</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Est_Time__c.field-meta.xml
<CustomField>
    <fullName>Est_Time__c</fullName>
    <label>Est. Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Under Analysis</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Do</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Item</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateChangeRequestPdfTest.cls
@isTest
private class GenerateChangeRequestPdfTest {
  @isTest
  private static void testChangeRequestPDFCreation() {
    System.runAs(createTestContextUser()) {
      // Arrange
      Account testAccount = new Account(Name = 'Test Account');
      insert testAccount;

      Contract testContract = new Contract(
        Name = 'Test Contract',
        AccountId = testAccount.Id,
        StartDate = Date.newInstance(2024, 1, 1),
        CurrencyISOCode = 'GBP',
        Status = 'Draft'
      );
      insert testContract;

      Project__c testProject = new Project__c(
        Name = 'Test Project',
        Status__c = 'Kick off',
        Account__c = testAccount.Id,
        Start_Date__c = Date.newInstance(2024, 1, 1),
        End_Date__c = Date.newInstance(2024, 31, 3),
        Vendor__c = 'Salesforce',
        Support_Type__c = 'MSA'
      );
      insert testProject;

      Project_Feature__c testFeature = new Project_Feature__c(
        Project__c = testProject.Id,
        Name = 'Test Feature'
      );
      insert testFeature;

      Work_Item__c testWI = new Work_Item__c(
        Subject__c = 'Test Work Item',
        Project__c = testProject.Id,
        Feature__c = testFeature.Id,
        Status__c = 'Ready',
        Est_Time__c = 4,
        Contract__c = testContract.Id,
        Type__c = 'Work Item'
      );
      insert testWI;

      // Add the Contract Id to a list for the Invocable method
      List<Id> contractIds = new List<Id>();
      contractIds.add(testContract.Id);

      // Simulate a PageReference for getContentAsPDF()
      PageReference pref = Page.ChangeRequestItems;
      pref.getParameters().put('id', testContract.Id);
      pref.setRedirect(true);

      // Set the simulated PageReference for getContentAsPDF()
      Test.setCurrentPage(pref);

      // Act
      // Call the Invocable method to generate the PDF
      Test.startTest();
      GenerateChangeRequestPdf.generatePdf(contractIds);
      Test.stopTest();

      // Assert
      // Query ContentVersion records
      List<ContentVersion> contentVersions = [
        SELECT
          Id,
          ContentDocumentId,
          Title,
          PathOnClient,
          VersionData,
          ContentLocation
        FROM ContentVersion
        WHERE PathOnClient LIKE 'contract-%.pdf'
      ];

      // Verify the records were created
      Assert.areEqual(
        1,
        contentVersions.size(),
        'ContentVersion records were not created'
      );
      for (ContentVersion cv : contentVersions) {
        Assert.areEqual(
          testContract.Name + '.pdf',
          cv.Title,
          'The Title was not set correctly.'
        );
        Assert.areEqual(
          'contract-' + testContract.Id + '.pdf',
          cv.PathOnClient,
          'The PathOnClient was not set correctly.'
        );
        Assert.areEqual(
          'Test',
          cv.VersionData.toString(),
          'The VersionData was not set correctly.' + cv.VersionData.toString()
        );
        Assert.areEqual(
          'S',
          cv.ContentLocation,
          'The ContentLocation was not set correctly.'
        );
      }

      // Collect the ContentDocumentId values
      Set<Id> contentDocumentIds = new Set<Id>();
      for (ContentVersion contentVersion : contentVersions) {
        contentDocumentIds.add(contentVersion.ContentDocumentId);
      }

      // Query ContentDocumentLink records using IN operator
      List<ContentDocumentLink> contentDocumentLinks = [
        SELECT Id, LinkedEntityId, ShareType, Visibility
        FROM ContentDocumentLink
        WHERE
          ContentDocumentId IN :contentDocumentIds
          AND LinkedEntityId = :testContract.Id
      ];

      // Verify the records were created
      Assert.areEqual(
        1,
        contentDocumentLinks.size(),
        'ContentDocumentLink records were not created'
      );
      for (ContentDocumentLink cdl : contentDocumentLinks) {
        Assert.areEqual(
          testContract.Id,
          cdl.LinkedEntityId,
          'The LinkedEntityId was not set correctly.'
        );
        Assert.areEqual(
          'V',
          cdl.ShareType,
          'The ShareType was not set correctly.'
        );
      }
    }
  }

  @isTest
  private static void testRepeatedChangeRequestPDFCreation() {
    System.runAs(createTestContextUser()) {
      // Arrange
      Account testAccount = new Account(Name = 'Test Account');
      insert testAccount;

      Contract testContract = new Contract(
        Name = 'Test Contract',
        AccountId = testAccount.Id,
        StartDate = Date.newInstance(2024, 1, 1),
        CurrencyISOCode = 'GBP',
        Status = 'Draft'
      );
      insert testContract;

      Project__c testProject = new Project__c(
        Name = 'Test Project',
        Status__c = 'Kick off',
        Account__c = testAccount.Id,
        Start_Date__c = Date.newInstance(2024, 1, 1),
        End_Date__c = Date.newInstance(2024, 31, 3),
        Vendor__c = 'Salesforce',
          Support_Type__c = 'MSA'
      );
      insert testProject;

      Project_Feature__c testFeature = new Project_Feature__c(
        Project__c = testProject.Id,
        Name = 'Test Feature'
      );
      insert testFeature;

      Work_Item__c testWI = new Work_Item__c(
        Subject__c = 'Test Work Item',
        Project__c = testProject.Id,
        Feature__c = testFeature.Id,
        Status__c = 'Ready',
        Est_Time__c = 4,
        Contract__c = testContract.Id,
        Type__c = 'Work Item'
      );
      insert testWI;

      // Add the Contract Id to a list for the Invocable method
      List<Id> contractIds = new List<Id>();
      contractIds.add(testContract.Id);

      // Simulate a PageReference for getContentAsPDF()
      PageReference pref = Page.ChangeRequestItems;
      pref.getParameters().put('id', testContract.Id);
      pref.setRedirect(true);

      // Set the simulated PageReference for getContentAsPDF()
      Test.setCurrentPage(pref);
      // Call the Invocable method to generate the PDF a first time
      GenerateChangeRequestPdf.generatePdf(contractIds);
      ContentVersion firstGenPdfContentVersion = [
        SELECT Id, ContentDocumentId
        FROM ContentVersion
        WHERE PathOnClient LIKE 'contract-%.pdf'
      ];
      Id firstGenPdfContentDocumentLinkId = [
        SELECT Id
        FROM ContentDocumentLink
        WHERE
          ContentDocumentId = :firstGenPdfContentVersion.ContentDocumentId
          AND LinkedEntityId = :testContract.Id
      ]
      .Id;

      // Act
      // Call the Invocable method to generate the PDF a second time
      Test.startTest();
      GenerateChangeRequestPdf.generatePdf(contractIds);
      Test.stopTest();

      // Assert
      // Query ContentVersion records
      List<ContentVersion> contentVersionsCreatedBySecondRequest = [
        SELECT Id, ContentDocumentId
        FROM ContentVersion
        WHERE
          PathOnClient LIKE 'contract-%.pdf'
          AND Id != :firstGenPdfContentVersion.Id
      ];

      // Verify the records were created
      Assert.areEqual(
        1,
        contentVersionsCreatedBySecondRequest.size(),
        'Unexpected number of ContentVersion records created by second PDF generation request'
      );

      // Query ContentDocumentLink records (note cannot filter on Id on this SObject,
      // can only filter on ContentDocumentId and LinkedEntityId so cannot filter out the first
      // ContentDocumentLink record based on Id)
      List<ContentDocumentLink> contentDocumentLinksCreatedAcrossBothRequests = [
        SELECT Id, ContentDocumentId
        FROM ContentDocumentLink
        WHERE LinkedEntityId = :testContract.Id
      ];

      // Verify the second request did not add any new ContentDocumentLink records
      Assert.areEqual(
        1,
        contentDocumentLinksCreatedAcrossBothRequests.size(),
        'Unexpected number of ContentDocumentLink records after second PDF generation request'
      );
      Assert.areEqual(
        firstGenPdfContentDocumentLinkId,
        contentDocumentLinksCreatedAcrossBothRequests[0].Id,
        'Unexpected ContentDocumentLink record after second PDF generation request, should have kept just the initial record created by the first request'
      );
      Assert.areEqual(
        firstGenPdfContentVersion.ContentDocumentId,
        contentDocumentLinksCreatedAcrossBothRequests[0].ContentDocumentId,
        'Unexpected ContentDocumentId on the ContentDocumentLink record after second PDF generation request'
      );
    }
  }

  private static User createTestContextUser() {
    return TestUtil.createUserWithProfileAndPermissionSets(
      'Standard User',
      new Set<String>{
        'Edit_Access_on_Contracts',
        'Create_Work_Items',
        'Project_Proposal_Generator'
      }
    );
  }
}