force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/RAID_Log__c.object-meta.xml
<CustomObject>
    <label>RAID Log</label>
    <nameField>
        <displayFormat>RAID-{000000}</displayFormat>
        <label>RAID Log Entry Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAID Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RAID_Log__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Strategic</fullName>
                <label>1 - Highest</label>
            </value>
            <value>
                <fullName>Critical</fullName>
                <label>2 - High</label>
            </value>
            <value>
                <fullName>Moderate</fullName>
                <label>3 - Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <label>4 - Low</label>
            </value>
            <value>
                <fullName>5 - Lowest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RaidLogTestDataFactoryTest.cls
@isTest
public class RaidLogTestDataFactoryTest {
    @isTest
    public static void test_create() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();
        Id projectId = ProjectTestDataFactory.create(accountId);

        // Act
        RAID_Log__c log = RaidLogTestDataFactory.create(projectId, RaidLogUtils.getRiskRecordTypeId, RaidLogStatusNames.Open, RaidLogRatingNames.Low);

        // Assert
        System.assertEquals(projectId, log.Project__c);
        System.assertEquals(RaidLogUtils.getRiskRecordTypeId, log.RecordTypeId);
        System.assertEquals(RaidLogStatusNames.Open, log.Status__c);
        System.assertEquals(RaidLogRatingNames.Low, log.Rating__c);
    }
}