force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectTestDataFactoryTest.cls
@isTest
public class ProjectTestDataFactoryTest {
    @isTest
    public static void test_create() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();

        // Act
        Id projectId = ProjectTestDataFactory.create(accountId);

        // Assert
        Project__c project = [SELECT Name, Account__c, Status__c, Start_Date__c, End_Date__c FROM Project__c WHERE Id = :projectId];
        System.assertEquals('test project', project.Name);
        System.assertEquals(accountId, project.Account__c);
        System.assertEquals(ProjectStatusNames.Backlog, project.Status__c);
        System.assertEquals(Date.today(), project.Start_Date__c);
        System.assertEquals((Date.today() + 28), project.End_Date__c);
    }

    @isTest
    public static void test_create_with_name_and_status() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();

        // Act
        Id projectId = ProjectTestDataFactory.create(accountId, 'New Project', ProjectStatusNames.Complete);

        // Assert
        Project__c project = [SELECT Name, Account__c, Status__c, Start_Date__c, End_Date__c FROM Project__c WHERE Id = :projectId];
        System.assertEquals('New Project', project.Name);
        System.assertEquals(accountId, project.Account__c);
        System.assertEquals(ProjectStatusNames.Complete, project.Status__c);
        System.assertEquals(Date.today(), project.Start_Date__c);
        System.assertEquals((Date.today() + 28), project.End_Date__c);
    }

    @isTest
    public static void test_create_with_name_and_status_and_dates() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();

        // Act
        Id projectId = ProjectTestDataFactory.create(accountId, 'New Project', ProjectStatusNames.Complete, Date.newInstance(2020, 1, 1), Date.newInstance(2020, 2, 28));

        // Assert
        Project__c project = [SELECT Name, Account__c, Status__c, Start_Date__c, End_Date__c FROM Project__c WHERE Id = :projectId];
        System.assertEquals('New Project', project.Name);
        System.assertEquals(accountId, project.Account__c);
        System.assertEquals(ProjectStatusNames.Complete, project.Status__c);
        System.assertEquals(Date.newInstance(2020, 1, 1), project.Start_Date__c);
        System.assertEquals(Date.newInstance(2020, 2, 28), project.End_Date__c);
    }
}