force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Support_Type__c.field-meta.xml
<CustomField>
    <fullName>Support_Type__c</fullName>
    <label>Support Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
                <default>true</default>
                <label>Project</label>
            </value>
            <value>
                <fullName>Managed Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <description>Used to capture the implementation team&apos;s billable and non-billable time and assign it to a project</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TIME-{0000000}</displayFormat>
        <label>Time Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox for whether the time entry is billable or not. Default value is true</description>
    <label>Is Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-detail to Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Time the time entry was started</description>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <description>Time the time entry stopped being worked on</description>
    <label>Stop</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to User to get the user the time entry belongs to</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Work Item to get the one the time entry should be logged against</description>
    <label>Work Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Work Item or Project must not be Completed</errorMessage>
        <filterItems>
            <field>Work_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deployed</value>
        </filterItems>
        <filterItems>
            <field>Work_Item__c.Project__r.Status__c</field>
            <operation>notEqual</operation>
            <value>Complete</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/Timesheet_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings object for timesheet calendar</description>
    <label>Timesheet</label>
</CustomObject>

force-app/main/default/objects/Timesheet_Settings__c/fields/Billable_Event_Colour__c.field-meta.xml
<CustomField>
    <fullName>Billable_Event_Colour__c</fullName>
    <description>Custom colour setting for billable time entries</description>
    <label>Billable Event Colour</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Default_Event_Colour__c.field-meta.xml
<CustomField>
    <fullName>Default_Event_Colour__c</fullName>
    <description>Default custom colour setting for calendar events</description>
    <label>Default Event Colour</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Draft_Event_Colour__c.field-meta.xml
<CustomField>
    <fullName>Draft_Event_Colour__c</fullName>
    <description>Custom colour setting for draft time entries</description>
    <label>Draft Event Colour</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Draft_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Draft_Project_Name__c</fullName>
    <description>Default project name when creating time entries in calendar, if a work item is not provided</description>
    <label>Draft Project Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Non_Billable_Event_Colour__c.field-meta.xml
<CustomField>
    <fullName>Non_Billable_Event_Colour__c</fullName>
    <description>Custom colour setting for non-billable time entries</description>
    <label>Non-Billable Event Colour</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <description>The number of days before today that events should load from</description>
    <label>Number of Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Project__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Item</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimesheetHelperTest.cls
@isTest
private class TimesheetHelperTest {
  private final static String BILLABLE_EVENT_COLOUR = 'green';
  private final static String DEFAULT_EVENT_COLOUR = 'blue';
  private final static String DRAFT_EVENT_COLOUR = 'grey';
  private final static String DRAFT_PROJECT_NAME = 'Draft Time Entry';
  private final static String NON_BILLABLE_EVENT_COLOUR = 'orange';
  private final static String RECORD_NAME = 'Test Record';
  private final static String USER_ID = UserInfo.getUserId();
  private final static String WORK_ITEM_TYPE = 'Work Item';
  private final static Integer NUM_OF_DAYS = 180;

  @TestSetup
  static void setup() {
    Timesheet_Settings__c settings = new Timesheet_Settings__c();
    settings.Billable_Event_Colour__c = BILLABLE_EVENT_COLOUR;
    settings.Default_Event_Colour__c = DEFAULT_EVENT_COLOUR;
    settings.Draft_Event_Colour__c = DRAFT_EVENT_COLOUR;
    settings.Draft_Project_Name__c = DRAFT_PROJECT_NAME;
    settings.Non_Billable_Event_Colour__c = NON_BILLABLE_EVENT_COLOUR;
    settings.Number_Of_Days__c = NUM_OF_DAYS;
    insert settings;

    Account account = new Account();
    account.Name = RECORD_NAME;
    insert account;

    Project__c project = new Project__c();
    project.Name = DRAFT_PROJECT_NAME;
    project.Account__c = account.Id;
    project.Start_Date__c = Date.today();
    project.End_Date__c = Date.today().addDays(1);
    project.Support_Type__c = 'MSA';
    insert project;

    Time_Entry__c timeEntry = new Time_Entry__c();
    timeEntry.User__c = USER_ID;
    timeEntry.Start__c = DateTime.now().addHours(1);
    timeEntry.Stop__c = DateTime.now().addHours(2);
    insert timeEntry;
  }

  @isTest
  static void testGetTimeEntryName() {
    Time_Entry__c timeEntry = [SELECT Id, Name FROM Time_Entry__c LIMIT 1];
    Test.startTest();
    String timeEntryName = TimesheetHelper.getTimeEntryName(timeEntry.Id);
    Test.stopTest();
    System.assertEquals(
      timeEntryName,
      timeEntry.Name,
      'The method should return the time entry name'
    );
  }

  @isTest
  static void testGetSchedulerEvents() {
    Id projectId = [SELECT Id FROM Project__c LIMIT 1].Id;

    Event testEvent = new Event();
    testEvent.EndDateTime = DateTime.now().addHours(3);
    testEvent.StartDateTime = DateTime.now().addHours(2);
    testEvent.Subject = RECORD_NAME;
    testEvent.OwnerId = USER_ID;
    insert testEvent;

    Project_Feature__c feature = new Project_Feature__c();
    feature.Name = RECORD_NAME;
    feature.Project__c = projectId;
    insert feature;

    Work_Item__c workItem = new Work_Item__c();
    workItem.Type__c = WORK_ITEM_TYPE;
    workItem.Feature__c = feature.Id;
    workItem.Project__c = projectId;
    insert workItem;

    Time_Entry__c timeEntryNonBillable = new Time_Entry__c();
    timeEntryNonBillable.Work_Item__c = workItem.Id;
    timeEntryNonBillable.Is_Billable__c = false;
    timeEntryNonBillable.User__c = USER_ID;
    timeEntryNonBillable.Start__c = DateTime.now().addHours(3);
    timeEntryNonBillable.Stop__c = DateTime.now().addHours(4);

    Time_Entry__c timeEntryBillable = new Time_Entry__c();
    timeEntryBillable.Work_Item__c = workItem.Id;
    timeEntryBillable.Is_Billable__c = true;
    timeEntryBillable.User__c = USER_ID;
    timeEntryBillable.Start__c = DateTime.now().addHours(4);
    timeEntryBillable.Stop__c = DateTime.now().addHours(5);
    insert new List<Time_Entry__c>{ timeEntryNonBillable, timeEntryBillable };

    Test.startTest();
    List<DhtmlxSchedulerEvent> result = TimesheetHelper.getSchedulerEvents();
    Test.stopTest();

    System.assertEquals(
      4,
      result.size(),
      'The method should return four events'
    );
    for (DhtmlxSchedulerEvent event : result) {
      if (event.type == 'Event') {
        System.assertEquals(
          DEFAULT_EVENT_COLOUR,
          event.color,
          'The event should be default'
        );
      }
      if (event.type != 'Event' && String.isBlank(event.work_item_id)) {
        System.assertEquals(
          DRAFT_EVENT_COLOUR,
          event.color,
          'The event should be draft'
        );
      }
      if (!String.isBlank(event.work_item_id) && event.is_billable == false) {
        System.assertEquals(
          NON_BILLABLE_EVENT_COLOUR,
          event.color,
          'The event should be non-billable'
        );
      }
      if (!String.isBlank(event.work_item_id) && event.is_billable) {
        System.assertEquals(
          BILLABLE_EVENT_COLOUR,
          event.color,
          'The event should be billable'
        );
      }
    }
  }
}