force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FeatureCloneServiceTest.cls
@isTest
public class FeatureCloneServiceTest {
    @isTest
    public static void test_clone_feature() {
        // Arrange
        Id account1Id = AccountTestDataFactory.create('Account One');
        Id account2Id = AccountTestDataFactory.create('Account Two');

        Id project1Id = ProjectTestDataFactory.create(account1Id, 'Project One', ProjectStatusNames.Backlog);
        Id project2Id = ProjectTestDataFactory.create(account2Id, 'Project Two', ProjectStatusNames.Backlog);

        Id featureId = ProjectFeatureTestDataFactory.create(project1Id, 'Feature To Clone');
        Id workItemId = WorkItemTestDataFactory.create(project1Id, featureId);

        // Act
        Test.startTest();
        Id clonedFeatureId = new FeatureCloneService().cloneFeature(featureId, project2Id);
        Test.stopTest();

        // Assert
        Project_Feature__c clonedFeature = [SELECT Id, Name, Project__c, (SELECT Id FROM Work_Items__r) FROM Project_Feature__c WHERE Id = :clonedFeatureId];
        System.assertEquals('Feature To Clone', clonedFeature.Name);
        System.assertEquals(project2Id, clonedFeature.Project__c);
        System.assertEquals(1, clonedFeature.Work_Items__r.size());
    }
}