force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource_Assignment__c/Project_Resource_Assignment__c.object-meta.xml
<CustomObject>
    <label>Project Resource Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000000}</displayFormat>
        <label>Project Resource Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resource Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Friday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Friday__c</fullName>
    <label>Hours Friday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Monday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Monday__c</fullName>
    <label>Hours Monday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Hours_Per_Day__c</fullName>
    <label>Hours Per Day</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Thursday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Thursday__c</fullName>
    <label>Hours Thursday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Tuesday__c</fullName>
    <label>Hours Tuesday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Wednesday__c</fullName>
    <label>Hours Wednesday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Resource Assignments</relationshipLabel>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Is_Resource_Assignable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectResourceAssignmentTestDataFactory.cls
// TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
@SuppressWarnings('PMD.ApexSharingViolations')
public class ProjectResourceAssignmentTestDataFactory {
  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ExcessiveParameterList, PMD.ApexCRUDViolation')
  public static Id create(
    Id projectId,
    Id userId,
    Date startDate,
    Date endDate,
    Decimal hoursPerDay
  ) {
    Project_Resource_Assignment__c resource = new Project_Resource_Assignment__c();
    resource.Project__c = projectId;
    resource.User__c = userId;
    resource.Start_Date__c = startDate;
    resource.End_Date__c = endDate;
    resource.Hours_Per_Day__c = hoursPerDay;
    insert resource;
    return resource.Id;
  }

  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ExcessiveParameterList')
  public static Project_Resource_Assignment__c create(
    Id userId,
    Id projectId,
    Decimal rate,
    Date startDate,
    Decimal hoursMonday,
    Decimal hoursTuesday,
    Decimal hoursWednesday,
    Decimal hoursThursday,
    Decimal hoursFriday
  ) {
    Project_Resource_Assignment__c resourceAssignment = new Project_Resource_Assignment__c();
    resourceAssignment.User__c = userId;
    resourceAssignment.Project__c = projectId;
    resourceAssignment.Rate__c = rate;
    resourceAssignment.Start_Date__c = startDate;
    resourceAssignment.Hours_Monday__c = hoursMonday;
    resourceAssignment.Hours_Tuesday__c = hoursTuesday;
    resourceAssignment.Hours_Wednesday__c = hoursWednesday;
    resourceAssignment.Hours_Thursday__c = hoursThursday;
    resourceAssignment.Hours_Friday__c = hoursFriday;

    return resourceAssignment;
  }
}