force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <description>Used to capture the implementation team&apos;s billable and non-billable time and assign it to a project</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TIME-{0000000}</displayFormat>
        <label>Time Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Master-detail to Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Time the time entry was started</description>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Work Item to get the one the time entry should be logged against</description>
    <label>Work Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Work Item or Project must not be Completed</errorMessage>
        <filterItems>
            <field>Work_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deployed</value>
        </filterItems>
        <filterItems>
            <field>Work_Item__c.Project__r.Status__c</field>
            <operation>notEqual</operation>
            <value>Complete</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimeEntryTestDataFactoryTest.cls
@isTest
public class TimeEntryTestDataFactoryTest {
    @isTest
    public static void test_create() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();
        Id projectId = ProjectTestDataFactory.create(accountId);
        Id featureId = ProjectFeatureTestDataFactory.create(projectId);
        Id workItemId = WorkItemTestDataFactory.create(projectId, featureId);

        // Act
        Id timeEntryId = TimeEntryTestDataFactory.create(projectId, workItemId);

        // Assert
        Time_Entry__c timeEntry = [SELECT Work_Item__c, Project__c, Start__c FROM Time_Entry__c WHERE Id = :timeEntryId];
        System.assertEquals(workItemId, timeEntry.Work_Item__c);
        System.assertEquals(projectId, timeEntry.Project__c);
        System.assertNotEquals(null, timeEntry.Start__c);
    }
}