force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource_Assignment__c/Project_Resource_Assignment__c.object-meta.xml
<CustomObject>
    <label>Project Resource Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000000}</displayFormat>
        <label>Project Resource Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resource Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Hours_Per_Day__c</fullName>
    <label>Hours Per Day</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Resource Assignments</relationshipLabel>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Is_Resource_Assignable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectResourceAssignmentFactoryTest.cls
@isTest
private class ProjectResourceAssignmentFactoryTest {
  @isTest
  static void testCreate() {
    // Arrange
    User user = UserTestDataFactory.create('test@r3.digital', 'Test', 'User');
    Id accountId = AccountTestDataFactory.create();
    Id projectId = ProjectTestDataFactory.create(accountId);
    Date startDate = Date.newInstance(2020, 1, 1);
    Date endDate = Date.newInstance(2020, 1, 31);
    Decimal hoursPerDay = 8;

    // Act
    Id resourceId = ProjectResourceAssignmentTestDataFactory.create(
      projectId,
      user.Id,
      startDate,
      endDate,
      hoursPerDay
    );

    // Assert
    Project_Resource_Assignment__c resource = [
      SELECT Project__c, User__c, Start_Date__c, End_Date__c, Hours_Per_Day__c
      FROM Project_Resource_Assignment__c
      WHERE Id = :resourceId
    ];

    System.assertEquals(
      projectId,
      resource.Project__c,
      'Project ID is not correct'
    );
    System.assertEquals(user.Id, resource.User__c, 'User ID is not correct');
    System.assertEquals(
      startDate,
      resource.Start_Date__c,
      'Start date is not correct'
    );
    System.assertEquals(
      endDate,
      resource.End_Date__c,
      'End date is not correct'
    );
    System.assertEquals(
      hoursPerDay,
      resource.Hours_Per_Day__c,
      'Hours per day is not correct'
    );
  }
}