force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/Salesforce_License__c.object-meta.xml
<CustomObject>
    <label>Salesforce License</label>
    <nameField>
        <displayFormat>SFL-{0000}</displayFormat>
        <label>Salesforce License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_License__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that holds these Licenses.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salesforce Licenses</relationshipLabel>
    <relationshipName>Salesforce_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <label>License</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Studio</fullName>
            </value>
            <value>
                <fullName>Agentforce</fullName>
            </value>
            <value>
                <fullName>Agentforce - Customer Service</fullName>
            </value>
            <value>
                <fullName>Agentforce - Marketing Campaigns</fullName>
            </value>
            <value>
                <fullName>Agentforce - Personal Shopper</fullName>
            </value>
            <value>
                <fullName>Agentforce - Sales Coach</fullName>
            </value>
            <value>
                <fullName>Agentforce - SDR</fullName>
            </value>
            <value>
                <fullName>API Access</fullName>
            </value>
            <value>
                <fullName>Channel Account Login</fullName>
            </value>
            <value>
                <fullName>Channel Account Member</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Login License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Member License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Plus Login License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Plus Member License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2C</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud D2C</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>CPQ &amp; Billing</fullName>
            </value>
            <value>
                <fullName>CPQ for Customer Communities Login</fullName>
            </value>
            <value>
                <fullName>CPQ for Customer Communities Member</fullName>
            </value>
            <value>
                <fullName>CPQ for Partner Communities Login</fullName>
            </value>
            <value>
                <fullName>CPQ for Partner Communities Member</fullName>
            </value>
            <value>
                <fullName>CPQ Plus</fullName>
            </value>
            <value>
                <fullName>CPQ Plus &amp; Billing</fullName>
            </value>
            <value>
                <fullName>CRM Analytics Growth</fullName>
            </value>
            <value>
                <fullName>CRM Analytics Plus</fullName>
            </value>
            <value>
                <fullName>Customer Community Login</fullName>
            </value>
            <value>
                <fullName>Customer Community Member</fullName>
            </value>
            <value>
                <fullName>Salesforce Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Project you have selected is not linked to the selected Account</errorMessage>
        <filterItems>
            <field>Project__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Salesforce Licenses</relationshipLabel>
    <relationshipName>Salesforce_Licenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/fields/Salesforce_License__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_License__c</fullName>
    <formula>HYPERLINK(Id, TEXT( License__c ) , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesforce License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesforceLicenseTestDataFactory.cls
// TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
@SuppressWarnings('PMD.ApexSharingViolations')
public class SalesforceLicenseTestDataFactory {
  public static Id create(Id projectId, Id accountId) {
    return create(projectId, accountId, 'Salesforce Platform');
  }

  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ApexCRUDViolation')
  public static Id create(Id projectId, Id accountId, String licenceType) {
    Salesforce_License__c licence = new Salesforce_License__c();
    licence.Project__c = projectId;
    licence.Account__c = accountId;
    licence.License__c = licenceType;
    licence.Quantity__c = 10;
    insert licence;

    return licence.Id;
  }
}