force-app/main/default/objects/Leave_Summary__c/Leave_Summary__c.object-meta.xml
<CustomObject>
    <label>Leave Summary</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Leave Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Summary__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),12,31)</defaultValue>
    <inlineHelpText>Employee end date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Summary__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,1)</defaultValue>
    <inlineHelpText>Employee start date for period</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeaveSummaryTestDataFactoryTest.cls
@isTest
public class LeaveSummaryTestDataFactoryTest {
    @isTest
    public static void test_create() {
        // Arrange
        User user = UserTestDataFactory.create('test@r3.digtial', 'Test', 'User');

        // Act
        Id summaryId = LeaveSummaryTestDataFactory.create(user.Id, '2020', Date.newInstance(2020, 1, 1), Date.newInstance(2020, 12, 31));

        // Assert
        Leave_Summary__c summary = [SELECT OwnerId, Year__c, Start_Date__c, End_Date__c FROM Leave_Summary__c WHERE Id = :summaryId];
        System.assertEquals(user.Id, summary.OwnerId);
        System.assertEquals('2020', summary.Year__c);
        System.assertEquals(Date.newInstance(2020, 1, 1), summary.Start_Date__c);
        System.assertEquals(Date.newInstance(2020, 12, 31), summary.End_Date__c);
    }
}