force-app/main/default/objects/Leave_Summary__c/Leave_Summary__c.object-meta.xml
<CustomObject>
    <label>Leave Summary</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Leave Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Summary__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),12,31)</defaultValue>
    <inlineHelpText>Employee end date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Summary__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,1)</defaultValue>
    <inlineHelpText>Employee start date for period</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeaveSummaryTestDataFactory.cls
// TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
@SuppressWarnings('PMD.ApexSharingViolations')
public class LeaveSummaryTestDataFactory {
  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ExcessiveParameterList, PMD.ApexCRUDViolation')
  public static Id create(
    Id ownerId,
    String year,
    Date startDate,
    Date endDate
  ) {
    Leave_Summary__c summary = new Leave_Summary__c();
    summary.OwnerId = ownerId;
    summary.Year__c = year;
    summary.Start_Date__c = startDate;
    summary.End_Date__c = endDate;
    insert summary;
    return summary.Id;
  }
}