force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Change Request contract for client signature</description>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Est_Time__c.field-meta.xml
<CustomField>
    <fullName>Est_Time__c</fullName>
    <label>Est. Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChangeRequestItemsController.cls
public with sharing class ChangeRequestItemsController {
  public Boolean hasWorkItems { get; private set; }
  public String currencySymbol { get; private set; }
  public List<LineItem> workItems { get; private set; }
  public ChangeRequestContract changeRequest { get; private set; }

  // Constructor
  public ChangeRequestItemsController() {
    Contract con = getContractDataForInitialisation();
    this.workItems = getWorkItems(con.Id);
    this.hasWorkItems = !this.workItems.isEmpty();
    this.currencySymbol = getCurrencySymbol(con.CurrencyIsoCode);
    this.changeRequest = getTotals(this.workItems);
  }

  private static String getCurrencySymbol(String currencyCode) {
    if (currencyCode == 'USD') {
      return '$';
    } else if (currencyCode == 'GBP') {
      return '£';
    } else if (currencyCode == 'EUR') {
      return '€';
    }

    return '';
  }

  private static Contract getContractDataForInitialisation() {
    Id idValue = getContractIdFromPageParams();

    List<Contract> contractList = [
      SELECT Id, CurrencyIsoCode
      FROM Contract
      WHERE Id = :idValue
      WITH SECURITY_ENFORCED
    ];

    if (contractList.isEmpty()) {
      throw new CustomException('Contract not found for ID: ' + idValue);
    }

    return contractList[0];
  }

  private static Id getContractIdFromPageParams() {
    Map<String, String> params = ApexPages.currentPage().getParameters();
    if (!params.containsKey('id') || String.isBlank(params.get('id'))) {
      throw new CustomException(
        'Id page parameter for ChangeRequestItemsController has not been set'
      );
    }

    Id idValue;

    try {
      idValue = Id.valueOf(params.get('id'));
    } catch (Exception e) {
      throw new CustomException(
        'Id page parameter for ChangeRequestItemsController is not a valid ID'
      );
    }
    if (idValue.getSObjectType() != Contract.SObjectType) {
      throw new CustomException(
        'Id page parameter for ChangeRequestItemsController is not a Contract ID'
      );
    }
    return idValue;
  }

  private static List<LineItem> getWorkItems(Id contractId) {
    List<LineItem> lineItemList = new List<LineItem>();

    for (Work_Item__c workItem : [
      SELECT Subject__c, Est_Time__c
      FROM Work_Item__c
      WHERE Contract__c = :contractId
      WITH SECURITY_ENFORCED
      ORDER BY Subject__c
    ]) {
      LineItem lineItem = new LineItem();
      lineItem.subject = workItem.Subject__c;
      lineItem.unitPrice = 125;
      lineItem.estHours = workItem.Est_Time__c;
      lineItem.totalPrice = (lineItem.unitPrice * lineItem.estHours);

      lineItemList.add(lineItem);
    }

    return lineItemList;
  }

  private static ChangeRequestContract getTotals(List<LineItem> lineItemList) {
    ChangeRequestContract changeRequest = new ChangeRequestContract();
    changeRequest.totalHours = 0;
    changeRequest.TotalPrice = 0;

    for (LineItem li : lineItemList) {
      changeRequest.totalHours += li.estHours;
      changeRequest.totalPrice += (li.unitPrice * li.estHours);
    }

    return changeRequest;
  }

  public Integer year {
    get {
      return System.today().year();
    }
  }

  public class CustomException extends Exception {
  }

  public class LineItem {
    @AuraEnabled
    public String subject { get; set; }

    @AuraEnabled
    public Decimal unitPrice { get; set; }

    @AuraEnabled
    public Decimal estHours { get; set; }

    @AuraEnabled
    public Decimal totalPrice { get; set; }
  }

  public class ChangeRequestContract {
    @AuraEnabled
    public Decimal totalHours { get; set; }

    @AuraEnabled
    public Decimal totalPrice { get; set; }
  }
}