force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>65000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Documentation_URL__c.field-meta.xml
<CustomField>
    <fullName>Documentation_URL__c</fullName>
    <label>Documentation URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <label>Implementation</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CopilotWorkItemContext.cls
public with sharing class CopilotWorkItemContext extends CopilotContext {

    Work_Item__c item;

    public override void buildContext() {
        item = WorkItemDataAccess.getWorkItem(recordId);
    }

    public override String getContext() {

        StringBuilder builder = new StringBuilder();

        builder.appendLine('CONTEXT')
            .appendLine('This is the Work Item Subject: ' + item.Subject__c)
            .appendLine('This is the Work Item Description: ' + item.Description__c)
            .appendLine('This Work Item has a link to this related documentation' + item.Documentation_URL__c)
            .appendLine('This is the Work Item Implementation details: ' + item.Implementation__c);

        return builder.toString();
    }
}