force-app/main/default/objects/Acceptance_Criteria__c/Acceptance_Criteria__c.object-meta.xml
<CustomObject>
    <label>Acceptance Criteria</label>
    <nameField>
        <displayFormat>AC-{0000000}</displayFormat>
        <label>Acceptance Criteria Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acceptance Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Acceptance_Criteria__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Acceptance Criteria</relationshipLabel>
    <relationshipName>Acceptance_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>ASS-{0000000}</displayFormat>
        <label>Assumption Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Assumption__c.field-meta.xml
<CustomField>
    <fullName>Assumption__c</fullName>
    <label>Assumption</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assumptions</relationshipLabel>
    <relationshipName>Assumptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Requirement__c/Business_Requirement__c.object-meta.xml
<CustomObject>
    <label>Business Requirement</label>
    <nameField>
        <label>Business Requirement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Requirement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Business Requirements</relationshipLabel>
    <relationshipName>Business_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Persona__c/Persona__c.object-meta.xml
<CustomObject>
    <label>Persona</label>
    <nameField>
        <label>Persona</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Persona__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Personas</relationshipLabel>
    <relationshipName>Personas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/RAID_Log__c.object-meta.xml
<CustomObject>
    <label>RAID Log</label>
    <nameField>
        <displayFormat>RAID-{000000}</displayFormat>
        <label>RAID Log Entry Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAID Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RAID_Log__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/Salesforce_License__c.object-meta.xml
<CustomObject>
    <label>Salesforce License</label>
    <nameField>
        <displayFormat>SFL-{0000}</displayFormat>
        <label>Salesforce License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_License__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that holds these Licenses.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salesforce Licenses</relationshipLabel>
    <relationshipName>Salesforce_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Project you have selected is not linked to the selected Account</errorMessage>
        <filterItems>
            <field>Project__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Salesforce Licenses</relationshipLabel>
    <relationshipName>Salesforce_Licenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/fields/Salesforce_License__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_License__c</fullName>
    <formula>HYPERLINK(Id, TEXT( License__c ) , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesforce License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Third_Party_Service__c/Third_Party_Service__c.object-meta.xml
<CustomObject>
    <label>Third Party Service</label>
    <nameField>
        <displayFormat>TPS-{00000}</displayFormat>
        <label>Third Party Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Service__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Third Party Services</relationshipLabel>
    <relationshipName>Third_Party_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>User Story Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>As a &lt;persona&gt;</label>
    <referenceTo>Persona__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <formula>HYPERLINK(Id, &apos;As a &apos; +  Persona__r.Name + &apos;, I want to &apos; + Goal__c + &apos; so that I can &apos; +  Outcome__c , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User Story</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProjectProposalBuilder.cls
public with sharing class ProjectProposalBuilder {
  private ProjectProposalFactory factory;
  private ProjectProposalDataAccess dataAccess;

  public ProjectProposalBuilder() {
    factory = new ProjectProposalFactory();
    dataAccess = new ProjectProposalDataAccess();
  }

  public ProjectProposal build(Id projectId) {
    Project__c project = dataAccess.getProject(projectId);
    List<Project_Feature__c> features = dataAccess.getFeatures(projectId);
    List<Third_Party_Service__c> services = dataAccess.getServices(projectId);
    List<Salesforce_License__c> licenses = dataAccess.getLicenses(projectId);
    List<Persona__c> personas = dataAccess.getPersonas(project.Account__c);
    List<User_Story__c> userStories = dataAccess.getUserStories(projectId);
    List<Acceptance_Criteria__c> acceptanceCriterias = dataAccess.getAcceptanceCriterias(
      projectId
    );
    List<Business_Requirement__c> businessRequirements = dataAccess.getBusinessRequirements(
      projectId
    );
    List<RAID_Log__c> raidLogs = dataAccess.getRaidLogs(projectId);
    List<Assumption__c> assumptions = dataAccess.getAssumptions(projectId);

    ProjectProposal proposal = new ProjectProposal(project);
    proposal.features = factory.createFeatures(features);
    proposal.optionalFeatures = factory.createOptionalFeatures(features);
    proposal.files = dataAccess.getFiles(projectId);
    proposal.services = factory.createServices(services);
    proposal.teamMembers = factory.createTeamMembers(
      dataAccess.getProjectTeamMembers(projectId)
    );
    proposal.assumptions = factory.createAssumptions(assumptions);
    proposal.licenses = factory.createLicenses(licenses);
    proposal.personas = factory.createPersonas(personas);
    proposal.userStories = factory.createUserStories(userStories);
    proposal.acceptanceCriterias = factory.createAcceptanceCriterias(
      acceptanceCriterias
    );
    proposal.businessRequirements = factory.createBusinessRequirements(
      businessRequirements
    );
    proposal.raidLogs = factory.createRaidLogs(raidLogs);

    return proposal;
  }
}