force-app/main/default/objects/Acceptance_Criteria__c/Acceptance_Criteria__c.object-meta.xml
<CustomObject>
    <label>Acceptance Criteria</label>
    <nameField>
        <displayFormat>AC-{0000000}</displayFormat>
        <label>Acceptance Criteria Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acceptance Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Acceptance_Criteria__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Item</label>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>Acceptance Criteria</relationshipLabel>
    <relationshipName>Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>ASS-{0000000}</displayFormat>
        <label>Assumption Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Governance</fullName>
            </value>
            <value>
                <fullName>Requirements</fullName>
            </value>
            <value>
                <fullName>Readiness</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>3rd Parties</fullName>
            </value>
            <value>
                <fullName>Licenses</fullName>
            </value>
            <value>
                <fullName>Org</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Assumption__c.field-meta.xml
<CustomField>
    <fullName>Assumption__c</fullName>
    <label>Assumption</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Est_Cost__c.field-meta.xml
<CustomField>
    <fullName>Est_Cost__c</fullName>
    <formula>Total_Est__c *  Project__r.Proposal_Hourly_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Est. Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/Project_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{000000}</displayFormat>
        <label>Project Team Member Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(NOT(ISBLANK(User__c)), User__r.Email,
IF(NOT(ISBLANK(Contact__c)), Contact__r.Email,
&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF(NOT(ISBLANK(User__c)), User__r.FirstName + &apos; &apos; + User__r.LastName,
IF(NOT(ISBLANK(Contact__c)), Contact__r.FirstName + &apos; &apos; + Contact__r.LastName,
&apos;Not set&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>IF(NOT(ISBLANK(User__c)),  User__r.MobilePhone ,
IF(NOT(ISBLANK(Contact__c)),  Contact__r.MobilePhone ,
&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Team_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/RAID_Log__c.object-meta.xml
<CustomObject>
    <label>RAID Log</label>
    <nameField>
        <displayFormat>RAID-{000000}</displayFormat>
        <label>RAID Log Entry Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAID Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RAID_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Item</label>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/Salesforce_License__c.object-meta.xml
<CustomObject>
    <label>Salesforce License</label>
    <nameField>
        <displayFormat>SFL-{0000}</displayFormat>
        <label>Salesforce License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_License__c/fields/Salesforce_License__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_License__c</fullName>
    <formula>HYPERLINK(Id, TEXT( License__c ) , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesforce License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Third_Party_Service__c/Third_Party_Service__c.object-meta.xml
<CustomObject>
    <label>Third Party Service</label>
    <nameField>
        <displayFormat>TPS-{00000}</displayFormat>
        <label>Third Party Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Service__c/fields/Est_Cost__c.field-meta.xml
<CustomField>
    <fullName>Est_Cost__c</fullName>
    <label>Est. Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Third_Party_Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aircall</fullName>
            </value>
            <value>
                <fullName>Blackthorn Payments</fullName>
            </value>
            <value>
                <fullName>BNF Drug Interaction Database</fullName>
            </value>
            <value>
                <fullName>Conga</fullName>
            </value>
            <value>
                <fullName>FormStack Documents</fullName>
            </value>
            <value>
                <fullName>FormStack Documents and eSign</fullName>
            </value>
            <value>
                <fullName>FormStack eSign</fullName>
            </value>
            <value>
                <fullName>FormStack Forms</fullName>
            </value>
            <value>
                <fullName>Gazela DM+D Medication Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Interactive Scheduler</fullName>
            </value>
            <value>
                <fullName>Gazela Job Board Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Microsoft Dynamics Integration Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Netsuite Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Sage Connector</fullName>
            </value>
            <value>
                <fullName>Gazela SAP Connector</fullName>
            </value>
            <value>
                <fullName>Gazela SharePoint app</fullName>
            </value>
            <value>
                <fullName>Gazela Signature Rx Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Stripe App</fullName>
            </value>
            <value>
                <fullName>Gazela Trustpilot Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Xero Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Zoom Meeting Connector</fullName>
            </value>
            <value>
                <fullName>Gearset</fullName>
            </value>
            <value>
                <fullName>Gearset - CPQ+ and Billing</fullName>
            </value>
            <value>
                <fullName>Gearset - Enterprise</fullName>
            </value>
            <value>
                <fullName>Gearset - Salesforce Industries</fullName>
            </value>
            <value>
                <fullName>Gearset - Starter</fullName>
            </value>
            <value>
                <fullName>Gearset - Teams</fullName>
            </value>
            <value>
                <fullName>Impriviata</fullName>
            </value>
            <value>
                <fullName>InventoryWorks - Small Business Inventory Management</fullName>
            </value>
            <value>
                <fullName>IQVIA OneKey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>65000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Is_Optional__c.field-meta.xml
<CustomField>
    <fullName>Is_Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Separates the work item from the others, putting it in a &quot;Recommended Options&quot; section of the proposal and removes it from all the total estimates</inlineHelpText>
    <label>Is Optional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProjectProposalFactory.cls
public with sharing class ProjectProposalFactory {
  public List<ProjectProposal.FeatureRow> createFeatures(
    List<Project_Feature__c> features
  ) {
    return createFeatureRows(features, false);
  }

  public List<ProjectProposal.FeatureRow> createOptionalFeatures(
    List<Project_Feature__c> features
  ) {
    return createFeatureRows(features, true);
  }

  private List<ProjectProposal.FeatureRow> createFeatureRows(
    List<Project_Feature__c> features,
    Boolean isOptional
  ) {
    List<ProjectProposal.FeatureRow> featureRows = new List<ProjectProposal.FeatureRow>();

    for (Project_Feature__c feature : features) {
      List<ProjectProposal.WorkItemRow> workItems = new List<ProjectProposal.WorkItemRow>();
      Boolean isFirstRow = true;
      for (Work_Item__c workItem : feature.Work_Items__r) {
        if (workItem.Is_Optional__c == isOptional) {
          workItems.add(new ProjectProposal.WorkItemRow(workItem, isFirstRow));
          isFirstRow = false;
        }
      }
      if (workItems.size() > 0) {
        featureRows.add(new ProjectProposal.FeatureRow(feature, workItems));
      }
    }
    return featureRows;
  }

  public List<ProjectProposal.AssumptionRow> createAssumptions(
    List<Assumption__c> source
  ) {
    List<ProjectProposal.AssumptionRow> target = new List<ProjectProposal.AssumptionRow>();

    for (Assumption__c assumption : source) {
      target.add(
        new ProjectProposal.AssumptionRow(
          assumption.Area__c,
          assumption.Assumption__c
        )
      );
    }

    return target;
  }

  public List<ProjectProposal.ServiceRow> createServices(
    List<Third_Party_Service__c> source
  ) {
    List<ProjectProposal.ServiceRow> target = new List<ProjectProposal.ServiceRow>();
    for (Third_Party_Service__c service : source) {
      target.add(createServiceRow(service));
    }
    return target;
  }

  private ProjectProposal.ServiceRow createServiceRow(
    Third_Party_Service__c source
  ) {
    ProjectProposal.ServiceRow target = new ProjectProposal.ServiceRow();
    target.Name = source.Service__c;
    target.Description = String.isNotBlank(source.Description__c)
      ? StringUtil.removeBlankLinesFromRichText(source.Description__c)
      : '';
    target.EstCost = source.Est_Cost__c;
    target.CurrencySymbol = CurrencyUtils.getSymbol(source.CurrencyIsoCode);
    return target;
  }

  public List<ProjectProposal.TeamMemberRow> createTeamMembers(
    List<Project_Team_Member__c> source
  ) {
    List<ProjectProposal.TeamMemberRow> target = new List<ProjectProposal.TeamMemberRow>();
    for (Project_Team_Member__c member : source) {
      target.add(createTeamMemberRow(member));
    }
    return target;
  }

  private ProjectProposal.TeamMemberRow createTeamMemberRow(
    Project_Team_Member__c source
  ) {
    ProjectProposal.TeamMemberRow target = new ProjectProposal.TeamMemberRow();
    target.Email = source.Email__c;
    target.Phone = source.Phone__c;
    target.Name = source.Name__c;
    target.Role = source.Role__c;
    return target;
  }

  public List<ProjectProposal.LicenseRow> createLicenses(
    List<Salesforce_License__c> source
  ) {
    List<ProjectProposal.LicenseRow> target = new List<ProjectProposal.LicenseRow>();

    for (Salesforce_License__c license : source) {
      target.add(
        new ProjectProposal.LicenseRow(license.License__c, license.Quantity__c)
      );
    }

    return target;
  }

  public List<ProjectProposal.PersonaRow> createPersonas(
    List<Persona__c> source
  ) {
    List<ProjectProposal.PersonaRow> target = new List<ProjectProposal.PersonaRow>();

    for (Persona__c persona : source) {
      target.add(
        new ProjectProposal.PersonaRow(persona.Name, persona.Description__c)
      );
    }

    return target;
  }

  public List<ProjectProposal.UserStoryRow> createUserStories(
    List<User_Story__c> source
  ) {
    List<ProjectProposal.UserStoryRow> target = new List<ProjectProposal.UserStoryRow>();

    for (User_Story__c userStory : source) {
      target.add(
        new ProjectProposal.UserStoryRow(userStory.User_Story_Title__c)
      );
    }

    return target;
  }

  public List<ProjectProposal.AcceptanceCriteriaRow> createAcceptanceCriterias(
    List<Acceptance_Criteria__c> source
  ) {
    Map<String, List<ProjectProposal.AcceptanceCriteriaItemRow>> acceptanceCriteriasByUserStory = new Map<String, List<ProjectProposal.AcceptanceCriteriaItemRow>>();

    for (Acceptance_Criteria__c acceptanceCriteria : source) {
      Boolean isFirstOfUserStory = false;

      if (
        !acceptanceCriteriasByUserStory.containsKey(
          acceptanceCriteria.User_Story__r.User_Story_Title__c
        )
      ) {
        isFirstOfUserStory = true;
        acceptanceCriteriasByUserStory.put(
          acceptanceCriteria.User_Story__r.User_Story_Title__c,
          new List<ProjectProposal.AcceptanceCriteriaItemRow>()
        );
      }

      acceptanceCriteriasByUserStory.get(
          acceptanceCriteria.User_Story__r.User_Story_Title__c
        )
        .add(
          new ProjectProposal.AcceptanceCriteriaItemRow(
            acceptanceCriteria.Given__c,
            acceptanceCriteria.When__c,
            acceptanceCriteria.Then__c,
            isFirstOfUserStory
          )
        );
    }

    List<ProjectProposal.AcceptanceCriteriaRow> target = new List<ProjectProposal.AcceptanceCriteriaRow>();

    for (String userStory : acceptanceCriteriasByUserStory.keySet()) {
      target.add(
        new ProjectProposal.AcceptanceCriteriaRow(
          userStory,
          acceptanceCriteriasByUserStory.get(userStory)
        )
      );
    }

    return target;
  }

  public List<ProjectProposal.BusinessRequirementRow> createBusinessRequirements(
    List<Business_Requirement__c> source
  ) {
    List<ProjectProposal.BusinessRequirementRow> target = new List<ProjectProposal.BusinessRequirementRow>();

    for (Business_Requirement__c businessRequirement : source) {
      target.add(
        new ProjectProposal.BusinessRequirementRow(
          businessRequirement.Name,
          businessRequirement.Description__c
        )
      );
    }

    return target;
  }

  public List<ProjectProposal.RaidLogRow> createRaidLogs(
    List<RAID_Log__c> source
  ) {
    Map<String, List<ProjectProposal.RaidLogItemRow>> raidLogsByType = new Map<String, List<ProjectProposal.RaidLogItemRow>>();

    for (RAID_Log__c raidLog : source) {
      Boolean isFirstOfType = false;

      if (!raidLogsByType.containsKey(raidLog.Type__c)) {
        isFirstOfType = true;
        raidLogsByType.put(
          raidLog.Type__c,
          new List<ProjectProposal.RaidLogItemRow>()
        );
      }

      raidLogsByType.get(raidLog.Type__c)
        .add(
          new ProjectProposal.RaidLogItemRow(
            raidLog.Rating__c,
            raidLog.Subject__c,
            isFirstOfType
          )
        );
    }

    List<ProjectProposal.RaidLogRow> target = new List<ProjectProposal.RaidLogRow>();

    for (String raidLogType : raidLogsByType.keySet()) {
      target.add(
        new ProjectProposal.RaidLogRow(
          raidLogType,
          raidLogsByType.get(raidLogType)
        )
      );
    }

    return target;
  }
}