force-app/main/default/objects/Wiki_Record_Page__c/Wiki_Record_Page__c.object-meta.xml
<CustomObject>
    <description>Represents a wiki record page.</description>
    <label>Wiki Record Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Record Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wiki_Record_Page__c/fields/Parent_Page__c.field-meta.xml
<CustomField>
    <fullName>Parent_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent page of the wiki record page.</description>
    <label>Parent Page</label>
    <referenceTo>Wiki_Record_Page__c</referenceTo>
    <relationshipLabel>Wiki Record Pages</relationshipLabel>
    <relationshipName>Wiki_Record_Pages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wiki_Record_Page__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <description>The unique identifier for the wiki record page.</description>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wiki_Record_Page__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The sort order of the wiki page within its peer group.</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WikiRecordSpaceController.cls
public with sharing class WikiRecordSpaceController {
  @AuraEnabled(cacheable=true)
  public static Wiki_Record_Page__c getHomepage(String recordId) {
    try {
      List<Wiki_Record_Page__c> pages = [
        SELECT Id, Name
        FROM Wiki_Record_Page__c
        WHERE Record_ID__c = :recordId AND Parent_page__c = NULL
        WITH SECURITY_ENFORCED
        ORDER BY Sort_Order__c ASC
        LIMIT 1
      ];

      if (pages.size() == 0) {
        return null;
      }

      return pages[0];
    } catch (Exception cause) {
      throw AuraHandledExceptionFactory.create(cause);
    }
  }
}