force-app/main/default/objects/R3_Settings__c/R3_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>R3 Settings</label>
</CustomObject>

force-app/main/default/objects/R3_Settings__c/fields/ProjectId__c.field-meta.xml
<CustomField>
    <fullName>ProjectId__c</fullName>
    <description>Project Id of last viewed project</description>
    <label>ProjectId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LastViewedProjectController.cls
public class LastViewedProjectController 
{
    @AuraEnabled
    public static void captureProjectId(String projectId) 
    {
        R3_Settings__c settings = R3_Settings__c.getInstance(UserInfo.getUserId());
        if(settings.projectId__c != projectId) 
        {
            // update current project
            settings.SetupOwnerId = UserInfo.getUserId();
            settings.projectId__c = projectId;
            upsert settings;
        }
    }
}