force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <description>Used to capture the implementation team&apos;s billable and non-billable time and assign it to a project</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TIME-{0000000}</displayFormat>
        <label>Time Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of what the time entry is for</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Is_Billable__c.field-meta.xml
<CustomField>
    <fullName>Is_Billable__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox for whether the time entry is billable or not. Default value is true</description>
    <label>Is Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Time the time entry was started</description>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <description>Time the time entry stopped being worked on</description>
    <label>Stop</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/User_Is_Current_User__c.field-meta.xml
<CustomField>
    <fullName>User_Is_Current_User__c</fullName>
    <description>Checkbox for if the current user logged in is the one the time entry belongs to</description>
    <formula>User__c = $User.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User Is Current User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Work Item to get the one the time entry should be logged against</description>
    <label>Work Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Work Item or Project must not be Completed</errorMessage>
        <filterItems>
            <field>Work_Item__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Deployed</value>
        </filterItems>
        <filterItems>
            <field>Work_Item__c.Project__r.Status__c</field>
            <operation>notEqual</operation>
            <value>Complete</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/Timesheet_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings object for timesheet calendar</description>
    <label>Timesheet</label>
</CustomObject>

force-app/main/default/objects/Timesheet_Settings__c/fields/Billable_Event_Colour__c.field-meta.xml
<CustomField>
    <fullName>Billable_Event_Colour__c</fullName>
    <description>Custom colour setting for billable time entries</description>
    <label>Billable Event Colour</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Default_Event_Colour__c.field-meta.xml
<CustomField>
    <fullName>Default_Event_Colour__c</fullName>
    <description>Default custom colour setting for calendar events</description>
    <label>Default Event Colour</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Draft_Event_Colour__c.field-meta.xml
<CustomField>
    <fullName>Draft_Event_Colour__c</fullName>
    <description>Custom colour setting for draft time entries</description>
    <label>Draft Event Colour</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Non_Billable_Event_Colour__c.field-meta.xml
<CustomField>
    <fullName>Non_Billable_Event_Colour__c</fullName>
    <description>Custom colour setting for non-billable time entries</description>
    <label>Non-Billable Event Colour</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet_Settings__c/fields/Number_of_Days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Days__c</fullName>
    <description>The number of days before today that events should load from</description>
    <label>Number of Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>65000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimesheetHelper.cls
public with sharing class TimesheetHelper {
  private static final String SCHEDULER_EVENT_TYPE_TIME_ENTRY = 'Time_Entry__c';
  private static final String SCHEDULER_EVENT_TYPE_EVENT = 'Event';

  @AuraEnabled(cacheable=true)
  public static Timesheet_Settings__c getCustomSettings() {
    return Timesheet_Settings__c.getOrgDefaults();
  }

  @AuraEnabled(cacheable=true)
  public static String getTimeEntryName(Id recordId) {
    return [
      SELECT Name
      FROM Time_Entry__c
      WHERE Id = :recordId
      WITH SECURITY_ENFORCED
    ]
    .Name;
  }

  @AuraEnabled(cacheable=true)
  public static List<DhtmlxSchedulerEvent> getSchedulerEvents() {
    Timesheet_Settings__c settings = getCustomSettings();
    List<DhtmlxSchedulerEvent> schedulerEvents = new List<DhtmlxSchedulerEvent>();
    Integer numOfDays = settings.Number_of_Days__c.intValue();
    Date nDaysAgo = System.today().addDays(-numOfDays);

    for (Time_Entry__c timeEntry : [
      SELECT
        Id,
        Name,
        Description__c,
        Is_Billable__c,
        Start__c,
        Stop__c,
        Work_Item__c
      FROM Time_Entry__c
      WHERE
        User_Is_Current_User__c = TRUE
        AND Start__c != NULL
        AND Start__c > :nDaysAgo
        AND Stop__c != NULL
      WITH SECURITY_ENFORCED
    ]) {
      DhtmlxSchedulerEvent schedulerEvent = new DhtmlxSchedulerEvent();
      schedulerEvent.id = timeEntry.Id;
      schedulerEvent.color = String.isBlank(timeEntry.Work_Item__c)
        ? settings.Draft_Event_Colour__c
        : timeEntry.Is_Billable__c
            ? settings.Billable_Event_Colour__c
            : settings.Non_Billable_Event_Colour__c;
      schedulerEvent.end_date = timeEntry.Stop__c;
      schedulerEvent.info = timeEntry.Name;
      schedulerEvent.is_billable = timeEntry.Is_Billable__c;
      schedulerEvent.readonly = false;
      schedulerEvent.start_date = timeEntry.Start__c;
      schedulerEvent.text = timeEntry.Description__c;
      schedulerEvent.type = SCHEDULER_EVENT_TYPE_TIME_ENTRY;
      schedulerEvent.work_item_id = timeEntry.Work_Item__c;
      schedulerEvents.add(schedulerEvent);
    }

    for (Event event : [
      SELECT Id, Description, EndDateTime, StartDateTime, Subject
      FROM Event
      WHERE OwnerId = :UserInfo.getUserId() AND StartDateTime > :nDaysAgo
      WITH SECURITY_ENFORCED
    ]) {
      DhtmlxSchedulerEvent schedulerEvent = new DhtmlxSchedulerEvent();
      schedulerEvent.id = event.Id;
      schedulerEvent.color = settings.Default_Event_Colour__c;
      schedulerEvent.info = event.Description;
      schedulerEvent.end_date = event.EndDateTime;
      schedulerEvent.readonly = true;
      schedulerEvent.start_date = event.StartDateTime;
      schedulerEvent.text = event.Subject;
      schedulerEvent.type = SCHEDULER_EVENT_TYPE_EVENT;
      schedulerEvents.add(schedulerEvent);
    }

    return schedulerEvents;
  }
}