force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProjectCopyActionTest.cls
@isTest
private class ProjectCopyActionTest {
  @isTest
  static void testExecute() {
    // Arrange
    Id accountId = AccountTestDataFactory.create('Test Account');
    Id oldProjectId = ProjectTestDataFactory.create(accountId);
    Id newProjectId = ProjectTestDataFactory.create(accountId);

    Phase__c oldProjectPhase = PhaseTestDataFactory.create(oldProjectId);
    insert oldProjectPhase;

    Project_Feature__c oldProjectFeature = new Project_Feature__c();
    oldProjectFeature.Name = 'Test Feature';
    oldProjectFeature.Project__c = oldProjectId;
    oldProjectFeature.Phase__c = oldProjectPhase.Id;
    insert oldProjectFeature;

    WorkItemTestDataFactory.create(
      oldProjectId,
      oldProjectFeature.Id,
      WorkItemStatusNames.Backlog,
      oldProjectPhase.Id
    );

    ProjectCopyAction.Request request = new ProjectCopyAction.Request();
    request.oldProjectId = oldProjectId;
    request.newProjectId = newProjectId;

    // Act
    Test.startTest();
    System.runAs(TestUtil.getSysAdminUser()) {
      ProjectCopyAction.execute(new List<ProjectCopyAction.Request>{ request });
    }
    Test.stopTest();

    // Assert
    System.assertEquals(
      1,
      [SELECT Id FROM Phase__c WHERE Project__c = :newProjectId].size(),
      'New Project should have 1 Phase'
    );

    System.assertEquals(
      1,
      [SELECT Id FROM Project_Feature__c WHERE Project__c = :newProjectId]
        .size(),
      'New Project should have 1 Feature'
    );

    System.assertEquals(
      1,
      [SELECT Id FROM Work_Item__c WHERE Project__c = :newProjectId].size(),
      'New Project should have 1 Work Item'
    );
  }
}