force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Start_Date__c)) &amp;&amp; NOT(ISBLANK(End_Date__c)),
    (
        CASE(
            MOD(Start_Date__c - DATE(1985, 6, 24), 7),
            0, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 5, 1), 
            1, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 4, 4, 4, 5, 4, 6, 5, 1), 
            2, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 3, 4, 3, 5, 4, 6, 5, 1), 
            3, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 2, 3, 2, 4, 3, 5, 4, 6, 5, 1), 
            4, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 1, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 1), 
            5, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0), 
            6, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 5, 0), 
            999
        ) 
        + 
        (FLOOR((End_Date__c - Start_Date__c) / 7) * 5)
    ) * 8,
    null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PhaseTest.cls
@isTest
public class PhaseTest {
    @isTest
    public static void test_duration_formula() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();
        Id projectId = ProjectTestDataFactory.create(accountId);
        insert new List<Phase__c>{
            PhaseTestDataFactory.createWithDates(projectId, null, null), // No dates
            PhaseTestDataFactory.createWithDates(projectId, Date.newInstance(2021, 2, 1), null), // No end date
            PhaseTestDataFactory.createWithDates(projectId, null, Date.newInstance(2021, 2, 1)), // No start date
            PhaseTestDataFactory.createWithDates(projectId, Date.newInstance(2021, 2, 1), Date.newInstance(2021, 2, 5)), // Mon-Fri (5 days)
            PhaseTestDataFactory.createWithDates(projectId, Date.newInstance(2021, 2, 2), Date.newInstance(2021, 2, 8)), // Tue-Mon (5 days)
            PhaseTestDataFactory.createWithDates(projectId, Date.newInstance(2021, 2, 3), Date.newInstance(2021, 2, 7)), // Wed-Sun (3 days)
            PhaseTestDataFactory.createWithDates(projectId, Date.newInstance(2021, 2, 6), Date.newInstance(2021, 2, 12)), // Sat-Fri (5 days)
            PhaseTestDataFactory.createWithDates(projectId, Date.newInstance(2021, 2, 18), Date.newInstance(2021, 3, 8)) // Thu-Mon (13 days, 3 weekends)
        };

        // Assert
        List<Phase__c> phaseList = [SELECT Id, Duration__c FROM Phase__c];
        System.assertEquals(null, phaseList[0].Duration__c);
        System.assertEquals(null, phaseList[1].Duration__c);
        System.assertEquals(null, phaseList[2].Duration__c);
        System.assertEquals(40, phaseList[3].Duration__c);
        System.assertEquals(40, phaseList[4].Duration__c);
        System.assertEquals(24, phaseList[5].Duration__c);
        System.assertEquals(40, phaseList[6].Duration__c);
        System.assertEquals(104, phaseList[7].Duration__c);
    }
}