force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Meeting__c/Project_Meeting__c.object-meta.xml
<CustomObject>
    <label>Project Meeting</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Project Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Meeting__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Meetings</relationshipLabel>
    <relationshipName>Project_Meetings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/RAID_Log__c.object-meta.xml
<CustomObject>
    <label>RAID Log</label>
    <nameField>
        <displayFormat>RAID-{000000}</displayFormat>
        <label>RAID Log Entry Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAID Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RAID_Log__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Item</label>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/UAT_Feedback__c.object-meta.xml
<CustomObject>
    <description>The UAT Feedback custom object is used to collect and track User Acceptance Testing feedback from customers. The object contains information about the feedback, including the description, type, status, priority, and date, as well as the customer who provided the feedback. This information is used to improve the product and processes and to provide insights into customer feedback.</description>
    <label>UAT Feedback</label>
    <nameField>
        <displayFormat>UAT-{00000000}</displayFormat>
        <label>UAT No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UAT Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UAT_Feedback__c/fields/Project_UAT__c.field-meta.xml
<CustomField>
    <fullName>Project_UAT__c</fullName>
    <description>Master-detail relationship field to record which project UAT Feedback is related to.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>UAT Feedback Records</relationshipLabel>
    <relationshipName>UAT_Feedback_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Phase</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Phase__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WeeklyStatusReportBuilder.cls
public with sharing class WeeklyStatusReportBuilder {
  private WeeklyStatusReportFactory factory;
  private WeeklyStatusReportDataAccess dataAccess;

  public WeeklyStatusReportBuilder() {
    this.factory = new WeeklyStatusReportFactory();
    this.dataAccess = new WeeklyStatusReportDataAccess();
  }

  public WeeklyStatusReport build(Id projectId) {
    Project__c project = dataAccess.getProject(projectId);

    WeeklyStatusReport report = new WeeklyStatusReport(project);
    report.OpenUATItems = factory.createOpenUATItems(
      project.UAT_Feedback_Records__r
    );
    report.WIPUATItems = factory.createWIPUATItems(
      project.UAT_Feedback_Records__r
    );
    report.ReTestUATItems = factory.createReTestUATItems(
      project.UAT_Feedback_Records__r
    );
    report.ClosedUATItems = factory.createClosedUATItems(
      project.UAT_Feedback_Records__r
    );
    report.Phases = factory.createPhases(project.Phases__r);
    report.Meeting = factory.createMeeting(project.Project_Meetings__r);
    report.CriticalIssueLogs = factory.createCriticalIssueLogs(
      project.RAID_Log__r
    );
    report.OpenRiskLogs = factory.createOpenRiskLogs(project.RAID_Log__r);
    report.OpenActionLogs = factory.createOpenActionLogs(project.RAID_Log__r);
    report.OpenIssueLogs = factory.createOpenIssueLogs(project.RAID_Log__r);
    report.OpenDecisionLogs = factory.createOpenDecisionLogs(
      project.RAID_Log__r
    );
    report.ClosedRiskLogs = factory.createClosedRiskLogs(project.RAID_Log__r);
    report.ClosedActionLogs = factory.createClosedActionLogs(
      project.RAID_Log__r
    );
    report.ClosedIssueLogs = factory.createClosedIssueLogs(project.RAID_Log__r);
    report.ClosedDecisionLogs = factory.createClosedDecisionLogs(
      project.RAID_Log__r
    );
    report.BlockedWorkItems = factory.createBlockedWorkItems(
      project.Work_Items__r
    );
    report.ProjectPhasesImageId = this.getProjectPlanImageId(projectId);
    report.RaidLogs = factory.createRaidLogs(project.RAID_Log__r);

    return report;
  }

  @TestVisible
  @SuppressWarnings('PMD.ApexCRUDViolation')
  private Id getProjectPlanImageId(Id projectId) {
    List<ContentDocumentLink> documentLinks = [
      SELECT ContentDocument.Title, ContentDocument.LatestPublishedVersionId
      FROM ContentDocumentLink
      WHERE
        LinkedEntityId = :projectId
        AND ContentDocument.Title = 'project-phases'
        AND ContentDocument.FileType = 'PNG'
      LIMIT 1
    ];

    if (documentLinks.size() == 0) {
      return null;
    }

    return documentLinks[0].ContentDocument.LatestPublishedVersionId;
  }
}