force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Sponsor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sponsor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Projects_R3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Template_Project__c.field-meta.xml
<CustomField>
    <fullName>Template_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the original project template this template was created from</inlineHelpText>
    <label>Template Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Projects_R3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/RAID_Log__c.object-meta.xml
<CustomObject>
    <label>RAID Log</label>
    <nameField>
        <displayFormat>RAID-{000000}</displayFormat>
        <label>RAID Log Entry Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAID Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RAID_Log__c/fields/Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Assign_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RAID_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Impact__c.field-meta.xml
<CustomField>
    <fullName>Impact__c</fullName>
    <label>Impact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Mitigation_Resolution__c.field-meta.xml
<CustomField>
    <fullName>Mitigation_Resolution__c</fullName>
    <label>Mitigation / Resolution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Strategic</fullName>
                <label>1 - Highest</label>
            </value>
            <value>
                <fullName>Critical</fullName>
                <label>2 - High</label>
            </value>
            <value>
                <fullName>Moderate</fullName>
                <label>3 - Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <label>4 - Low</label>
            </value>
            <value>
                <fullName>5 - Lowest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Update__c.field-meta.xml
<CustomField>
    <fullName>Update__c</fullName>
    <label>Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SteeringCommitteePdfController.cls
public without sharing class SteeringCommitteePdfController {
    public Account account { get; private set; }
    public List<ProjectTransformer> projects { get; private set; }
    public Id clientLogoId { get; private set; }
    public Id programPlanId { get; private set; }
    public List<RAID_Log__c> actions { get; private set; }
    public List<RAID_Log__c> decisions { get; private set; }
    public List<RAID_Log__c> issues { get; private set; }
    public List<RAID_Log__c> risks { get; private set; }

    public SteeringCommitteePdfController() {
        Id accountId = ApexPages.currentPage().getParameters().get('id');
        this.account = this.getAccount(accountId);
        this.cacheAccountImageIds();
        this.collateProjects();
        this.collateRaidLogs();
    }

    private Account getAccount(Id accountId) {
        List<String> projectStatuses = new List<String>{ ProjectStatusNames.Estimate, ProjectStatusNames.KickOff, ProjectStatusNames.InProgress, ProjectStatusNames.Uat, ProjectStatusNames.HyperCare };

        List<Account> accountList = [
            SELECT Id, Executive_Summary__c, (SELECT Id, Name, Status__c, Sponsor__r.Name FROM Projects_R3__r WHERE Status__c IN :projectStatuses)
            FROM Account
            WHERE Id = :accountId
        ];

        if (accountList.size() == 0) {
            throw new CustomException('Unable to find account with ID: ' + accountId);
        }

        return accountList[0];
    }

    private void cacheAccountImageIds() {
        List<ContentDocumentLink> documentLinks = [
            SELECT ContentDocument.Title, ContentDocument.LatestPublishedVersionId
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :this.account.Id AND ContentDocument.Title IN ('client-logo', 'program-plan') AND ContentDocument.FileType = 'PNG'
        ];

        for (ContentDocumentLink documentLink : documentLinks) {
            Id versionId = documentLink.ContentDocument.LatestPublishedVersionId;

            if (documentLink.ContentDocument.Title == 'client-logo') {
                this.clientLogoId = versionId;
            } else if (documentLink.ContentDocument.Title == 'program-plan') {
                this.programPlanId = versionId;
            }
        }
    }

    private Map<Id, Id> getProjectGanttMap() {
        List<Id> projectIds = this.getProjectIds();

        if (projectIds.isEmpty()) {
            return new Map<Id, Id>();
        }

        List<ContentDocumentLink> documentLinks = [
            SELECT LinkedEntityId, ContentDocument.LatestPublishedVersionId
            FROM ContentDocumentLink
            WHERE LinkedEntityId IN :projectIds AND ContentDocument.Title IN ('project-plan') AND ContentDocument.FileType = 'PNG'
        ];

        Map<Id, Id> projectGanttMap = new Map<Id, Id>();

        for (ContentDocumentLink documentLink : documentLinks) {
            projectGanttMap.put(documentLink.LinkedEntityId, documentLink.ContentDocument.LatestPublishedVersionId);
        }

        return projectGanttMap;
    }

    private void collateProjects() {
        this.projects = new List<ProjectTransformer>();
        Map<Id, Id> projectGanttMap = this.getProjectGanttMap();
        List<Phase__c> phases = [SELECT Project__c, Name, End_Date__c, Status__c, Notes__c FROM Phase__c WHERE Project__c IN :this.getProjectIds() ORDER BY Project__c, Sort_Order__c];
        Map<Id, List<Phase__c>> projectPhaseMap = new Map<Id, List<Phase__c>>();

        for (Phase__c phase : phases) {
            if (!projectPhaseMap.containsKey(phase.Project__c)) {
                projectPhaseMap.put(phase.Project__c, new List<Phase__c>());
            }

            projectPhaseMap.get(phase.Project__c).add(phase);
        }

        for (Project__c project : this.account.Projects_R3__r) {
            ProjectTransformer transformer = new ProjectTransformer();
            transformer.Name = project.Name;
            transformer.Status = project.Status__c;
            transformer.Sponsor = project.Sponsor__r.Name;

            if (projectGanttMap.containsKey(project.Id)) {
                transformer.ProjectPlanId = projectGanttMap.get(project.Id);
            }

            if (projectPhaseMap.containsKey(project.Id)) {
                transformer.Milestones = projectPhaseMap.get(project.Id);
            }

            this.projects.add(transformer);
        }
    }

    private void collateRaidLogs() {
        List<RAID_Log__c> raidLogs = [
            SELECT Id, CreatedDate, Impact__c, Mitigation_Resolution__c, Rating__c, RecordTypeId, Status__c, Subject__c, Update__c, When__c, Assign_To__r.Name
            FROM RAID_Log__c
            WHERE Project__c IN :this.getProjectIds() AND Status__c IN (:RaidLogStatusNames.Open, :RaidLogStatusNames.Closed)
            ORDER BY When__c, CreatedDate
        ];

        Set<String> actionRatings = new Set<String>{ RaidLogRatingNames.Critical, RaidLogRatingNames.Strategic };

        this.actions = new List<RAID_Log__c>();
        this.decisions = new List<RAID_Log__c>();
        this.issues = new List<RAID_Log__c>();
        this.risks = new List<RAID_Log__c>();

        for (RAID_Log__c log : raidLogs) {
            if (log.RecordTypeId == RaidLogUtils.getActionRecordTypeId && log.Rating__c == RaidLogRatingNames.Strategic) {
                this.actions.add(log);
            } else if (log.RecordTypeId == RaidLogUtils.getDecisionRecordTypeId && log.Status__c == RaidLogStatusNames.Open) {
                this.decisions.add(log);
            } else if (log.RecordTypeId == RaidLogUtils.getIssueRecordTypeId && log.Status__c == RaidLogStatusNames.Open && actionRatings.contains(log.Rating__c)) {
                this.issues.add(log);
            } else if (log.RecordTypeId == RaidLogUtils.getRiskRecordTypeId && log.Status__c == RaidLogStatusNames.Open) {
                this.risks.add(log);
            }
        }
    }

    private List<Id> getProjectIds() {
        List<Id> projectIds = new List<Id>();

        for (Project__c project : this.account.Projects_R3__r) {
            projectIds.add(project.Id);
        }

        return projectIds;
    }

    public class CustomException extends Exception {
    }

    public class ProjectTransformer {
        public String Name { get; set; }
        public String Status { get; set; }
        public String Sponsor { get; set; }
        public Id ProjectPlanId { get; set; }
        public List<Phase__c> Milestones { get; set; }
    }
}