force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Closed_Count__c.field-meta.xml
<CustomField>
    <fullName>Closed_Count__c</fullName>
    <label>Closed Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Project_Meeting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Meeting</label>
    <referenceTo>Project_Meeting__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Meeting__c/Project_Meeting__c.object-meta.xml
<CustomObject>
    <label>Project Meeting</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Project Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Meeting__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Meetings</relationshipLabel>
    <relationshipName>Project_Meetings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/RAID_Log__c.object-meta.xml
<CustomObject>
    <label>RAID Log</label>
    <nameField>
        <displayFormat>RAID-{000000}</displayFormat>
        <label>RAID Log Entry Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAID Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RAID_Log__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Item</label>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/UAT_Feedback__c.object-meta.xml
<CustomObject>
    <description>The UAT Feedback custom object is used to collect and track User Acceptance Testing feedback from customers. The object contains information about the feedback, including the description, type, status, priority, and date, as well as the customer who provided the feedback. This information is used to improve the product and processes and to provide insights into customer feedback.</description>
    <label>UAT Feedback</label>
    <nameField>
        <displayFormat>UAT-{00000000}</displayFormat>
        <label>UAT No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UAT Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UAT_Feedback__c/fields/Feedback_Subject__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Subject__c</fullName>
    <description>A field for customers to submit a brief descriptions about issues, questions and new change requests that have arisen during UAT.</description>
    <inlineHelpText>Please provide a brief description of the issue you are reporting.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Open_Count__c.field-meta.xml
<CustomField>
    <fullName>Open_Count__c</fullName>
    <label>Open Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Project_UAT__c.field-meta.xml
<CustomField>
    <fullName>Project_UAT__c</fullName>
    <description>Master-detail relationship field to record which project UAT Feedback is related to.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>UAT Feedback Records</relationshipLabel>
    <relationshipName>UAT_Feedback_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Re_Test_Count__c.field-meta.xml
<CustomField>
    <fullName>Re_Test_Count__c</fullName>
    <label>Re-Test Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Status_UAT_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Status_UAT_Feedback__c</fullName>
    <description>A field to record and display what the status of a UAT feedback record is.</description>
    <inlineHelpText>Please update the status of your UAT feedback.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <color>#FF6666</color>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>WIP</fullName>
                <color>#FFFF66</color>
                <label>WIP</label>
            </value>
            <value>
                <fullName>Re-Test</fullName>
                <color>#FF9966</color>
                <label>Re-Test</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#9999FF</color>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/WIP_Count__c.field-meta.xml
<CustomField>
    <fullName>WIP_Count__c</fullName>
    <label>WIP Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to create a relationship between the UAT Feedback and Work Item tab</description>
    <inlineHelpText>Please select the work item that this is related to.</inlineHelpText>
    <label>Work Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Work_Item__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_UAT__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>UAT Feedback</relationshipLabel>
    <relationshipName>UAT_Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Project__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Phase</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Phase__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Under Analysis</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Do</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeeklyStatusReportDataAccessTest.cls
@isTest
public class WeeklyStatusReportDataAccessTest {
  @isTest
  public static void testGetProject() {
    // Arrange
    Id accountId = AccountTestDataFactory.create('Test Account');
    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    List<Phase__c> phaseList = new List<Phase__c>{
      PhaseTestDataFactory.create(projectId, 'Phase One'),
      PhaseTestDataFactory.create(projectId, 'Phase Two')
    };
    insert phaseList;

    List<RAID_Log__c> raidLogList = new List<RAID_Log__c>{
      RaidLogTestDataFactory.create(
        projectId,
        RaidLogUtils.getRiskRecordTypeId,
        RaidLogStatusNames.Open,
        RaidLogRatingNames.Low
      ),
      RaidLogTestDataFactory.create(
        projectId,
        RaidLogUtils.getActionRecordTypeId,
        RaidLogStatusNames.Closed,
        RaidLogRatingNames.Strategic
      )
    };
    insert raidLogList;

    // Act
    WeeklyStatusReportDataAccess dataAccess = new WeeklyStatusReportDataAccess();
    Project__c project = dataAccess.getProject(projectId);

    // Assert
    Assert.areEqual('Test Account', project.Account__r.Name, 'Account Name');
    Assert.areEqual('Test Project', project.Name, 'Project Name');
    Assert.areEqual(
      ProjectStatusNames.InProgress,
      project.Status__c,
      'Project Status'
    );
    Assert.areEqual('Test Account', project.Account__r.Name, 'Account Name');
    Assert.areEqual(2, project.Phases__r.size(), 'Phases');
    Assert.areEqual(2, project.RAID_Log__r.size(), 'RAID Log');
  }

  @isTest
  public static void testGetProjectMeetings() {
    // Arrange
    Id accountId = AccountTestDataFactory.create('Test Account');
    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    Project_Meeting__c meeting = ProjectMeetingTestDataFactory.create(
      projectId
    );
    insert meeting;

    // Act
    WeeklyStatusReportDataAccess dataAccess = new WeeklyStatusReportDataAccess();
    Project__c project = dataAccess.getProject(projectId);

    Assert.areEqual(1, project.Project_Meetings__r.size(), 'Project Meetings');
  }

  @isTest
  public static void testGetUATItems() {
    // Arrange
    Id accountId = AccountTestDataFactory.create('Test Account');
    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    List<UAT_Feedback__c> uatFeedbackList = new List<UAT_Feedback__c>{
      createInMemoryUATFeedback('Test Feedback 1', 'Open', projectId),
      createInMemoryUATFeedback('Test Feedback 2', 'WIP', projectId),
      createInMemoryUATFeedback('Test Feedback 3', 'Re-Test', projectId),
      createInMemoryUATFeedback('Test Feedback 4', 'Closed', projectId)
    };
    insert uatFeedbackList;

    UAT_Feedback__c openFeedback = [
      SELECT
        Id,
        Status_UAT_Feedback__c,
        Feedback_Subject__c,
        Open_Count__c,
        WIP_Count__c,
        Re_Test_Count__c,
        Closed_Count__c
      FROM UAT_Feedback__c
      WHERE Id = :uatFeedbackList[0].ID
      LIMIT 1
    ];
    UAT_Feedback__c wipFeedback = [
      SELECT
        Id,
        Status_UAT_Feedback__c,
        Feedback_Subject__c,
        Open_Count__c,
        WIP_Count__c,
        Re_Test_Count__c,
        Closed_Count__c
      FROM UAT_Feedback__c
      WHERE Id = :uatFeedbackList[1].ID
      LIMIT 1
    ];
    UAT_Feedback__c reTestFeedback = [
      SELECT
        Id,
        Status_UAT_Feedback__c,
        Feedback_Subject__c,
        Open_Count__c,
        WIP_Count__c,
        Re_Test_Count__c,
        Closed_Count__c
      FROM UAT_Feedback__c
      WHERE Id = :uatFeedbackList[2].ID
      LIMIT 1
    ];
    UAT_Feedback__c closedFeedback = [
      SELECT
        Id,
        Status_UAT_Feedback__c,
        Feedback_Subject__c,
        Open_Count__c,
        WIP_Count__c,
        Re_Test_Count__c,
        Closed_Count__c
      FROM UAT_Feedback__c
      WHERE Id = :uatFeedbackList[3].ID
      LIMIT 1
    ];

    // Act
    WeeklyStatusReportDataAccess dataAccess = new WeeklyStatusReportDataAccess();
    Project__c project = dataAccess.getProject(projectId);

    // Assert
    Assert.areEqual(4, project.UAT_Feedback_Records__r.size(), 'UAT Items');
    Assert.areEqual(
      openFeedback.Open_Count__c,
      project.UAT_Feedback_Records__r[0].Open_Count__c,
      'Open UAT Items'
    );
    Assert.areEqual(
      wipFeedback.WIP_Count__c,
      project.UAT_Feedback_Records__r[1].WIP_Count__c,
      'WIP UAT Items'
    );
    Assert.areEqual(
      reTestFeedback.Re_Test_Count__c,
      project.UAT_Feedback_Records__r[2].Re_Test_Count__c,
      'Re-Test UAT Items'
    );
    Assert.areEqual(
      closedFeedback.Closed_Count__c,
      project.UAT_Feedback_Records__r[3].Closed_Count__c,
      'Closed UAT Items'
    );
  }

  @isTest
  public static void testGetBlockedWorkItems() {
    // Arrange
    Id accountId = AccountTestDataFactory.create('Test Account');
    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );
    Id featureId = ProjectFeatureTestDataFactory.create(projectId);

    List<String> workItems = new List<String>{
      WorkItemTestDataFactory.create(
        projectId,
        featureId,
        WorkItemStatusNames.Blocked,
        'Testing blocked work item'
      ),
      WorkItemTestDataFactory.create(
        projectId,
        featureId,
        WorkItemStatusNames.Backlog,
        ''
      ),
      WorkItemTestDataFactory.create(
        projectId,
        featureId,
        WorkItemStatusNames.Approved,
        ''
      )
    };
    List<Work_Item__c> workItemList = [
      SELECT Id, Status__c
      FROM Work_Item__c
      WHERE
        Id IN :workItems
        AND Project__c = :projectId
        AND Status__c = :WorkItemStatusNames.Blocked
    ];

    // Act
    WeeklyStatusReportDataAccess dataAccess = new WeeklyStatusReportDataAccess();
    Project__c project = dataAccess.getProject(projectId);

    // Assert
    Assert.areEqual(
      workItemList.size(),
      project.Work_Items__r.size(),
      'Blocked Work Items'
    );
    Assert.areEqual(
      'Blocked',
      project.Work_Items__r[0].Status__c,
      'The status should be Blocked'
    );
  }

  private static UAT_Feedback__c createInMemoryUATFeedback(
    String subject,
    String status,
    Id projectId
  ) {
    String guid = EncodingUtil.convertToHex(Crypto.generateAesKey(128))
      .substring(0, 16);
    User testUser = UserTestDataFactory.create(
      'test-' + guid + '@example.com',
      'Test',
      'User'
    );
    UAT_Feedback__c uatFeedback = new UAT_Feedback__c();
    uatFeedback.Project_UAT__c = projectId;
    uatFeedback.Feedback_Subject__c = subject;
    uatFeedback.Priority__c = 'Low';
    uatFeedback.Status_UAT_Feedback__c = status;
    uatFeedback.Assigned_to_UAT__c = testUser.Id;
    return uatFeedback;
  }
}