force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Phase</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Phase__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProjectCopyService.cls
public with sharing class ProjectCopyService {
  public static Map<Id, Id> copyProjectPhases(
    List<Phase__c> oldProjectPhaseList,
    Map<Id, Id> oldToNewProjectIdMap
  ) {
    // Insert new Project Phases
    List<Phase__c> newProjectPhaseList = new List<Phase__c>();

    for (Phase__c oldProjectPhase : oldProjectPhaseList) {
      Phase__c newProjectPhase = oldProjectPhase.clone(
        false,
        true,
        false,
        false
      );
      newProjectPhase.Project__c = oldToNewProjectIdMap.get(
        oldProjectPhase.Project__c
      );
      newProjectPhaseList.add(newProjectPhase);
    }

    if (Schema.sObjectType.Phase__c.isCreateable()) {
      insert newProjectPhaseList;
    }

    // Create map of old Project Phase ID to new Project Phase ID
    Map<Id, Id> oldToNewProjectPhaseIdMap = new Map<Id, Id>();

    for (Integer i = 0; i < oldProjectPhaseList.size(); i++) {
      oldToNewProjectPhaseIdMap.put(
        oldProjectPhaseList[i].Id,
        newProjectPhaseList[i].Id
      );
    }

    return oldToNewProjectPhaseIdMap;
  }

  public static Map<Id, Id> copyProjectFeatures(
    List<Project_Feature__c> oldProjectFeatureList,
    Map<Id, Id> oldToNewProjectIdMap,
    Map<Id, Id> oldToNewProjectPhaseIdMap
  ) {
    // Insert new Project Features
    List<Project_Feature__c> newProjectFeatureList = new List<Project_Feature__c>();

    for (Project_Feature__c oldProjectFeature : oldProjectFeatureList) {
      Project_Feature__c newProjectFeature = oldProjectFeature.clone(
        false,
        true,
        false,
        false
      );
      newProjectFeature.Project__c = oldToNewProjectIdMap.get(
        oldProjectFeature.Project__c
      );
      newProjectFeature.Phase__c = oldToNewProjectPhaseIdMap.get(
        oldProjectFeature.Phase__c
      );
      newProjectFeatureList.add(newProjectFeature);
    }

    if (Schema.sObjectType.Project_Feature__c.isCreateable()) {
      insert newProjectFeatureList;
    }

    // Create map of old Project Feature ID to new Project Feature ID
    Map<Id, Id> oldToNewProjectFeatureIdMap = new Map<Id, Id>();

    for (Integer i = 0; i < oldProjectFeatureList.size(); i++) {
      oldToNewProjectFeatureIdMap.put(
        oldProjectFeatureList[i].Id,
        newProjectFeatureList[i].Id
      );
    }

    return oldToNewProjectFeatureIdMap;
  }

  @SuppressWarnings('PMD.ExcessiveParameterList')
  public static Map<Id, Id> copyWorkItems(
    List<Work_Item__c> oldWorkItemList,
    Map<Id, Id> oldToNewProjectIdMap,
    Map<Id, Id> oldToNewProjectPhaseIdMap,
    Map<Id, Id> oldToNewProjectFeatureIdMap
  ) {
    // Insert new Work Items
    List<Work_Item__c> newWorkItemList = new List<Work_Item__c>();

    for (Work_Item__c oldWorkItem : oldWorkItemList) {
      Work_Item__c newWorkItem = oldWorkItem.clone(false, true, false, false);
      newWorkItem.Project__c = oldToNewProjectIdMap.get(oldWorkItem.Project__c);
      newWorkItem.Project_Phase__c = oldToNewProjectPhaseIdMap.get(
        oldWorkItem.Project_Phase__c
      );
      newWorkItem.Feature__c = oldToNewProjectFeatureIdMap.get(
        oldWorkItem.Feature__c
      );
      newWorkItemList.add(newWorkItem);
    }

    if (Schema.sObjectType.Work_Item__c.isCreateable()) {
      insert newWorkItemList;
    }

    // Create map of old Work Item ID to new Work Item ID
    Map<Id, Id> oldToNewWorkItemIdMap = new Map<Id, Id>();

    for (Integer i = 0; i < oldWorkItemList.size(); i++) {
      oldToNewWorkItemIdMap.put(oldWorkItemList[i].Id, newWorkItemList[i].Id);
    }

    return oldToNewWorkItemIdMap;
  }
}