force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Total_Effort__c.field-meta.xml
<CustomField>
    <fullName>Total_Effort__c</fullName>
    <inlineHelpText>Total effort estimate (hours)</inlineHelpText>
    <label>Total Effort</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Challenges__c.field-meta.xml
<CustomField>
    <fullName>Challenges__c</fullName>
    <label>Challenges</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hide_Assumptions__c.field-meta.xml
<CustomField>
    <fullName>Hide_Assumptions__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Hide Assumptions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hide_Our_Approach__c.field-meta.xml
<CustomField>
    <fullName>Hide_Our_Approach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Our Approach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hide_Project_Management_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Hide_Project_Management_Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Project Management &amp; Delivery</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hide_Services__c.field-meta.xml
<CustomField>
    <fullName>Hide_Services__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hide_Table_of_Contents__c.field-meta.xml
<CustomField>
    <fullName>Hide_Table_of_Contents__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Table of Contents</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hypercare__c.field-meta.xml
<CustomField>
    <fullName>Hypercare__c</fullName>
    <defaultValue>0.05</defaultValue>
    <label>Hypercare %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hypercare_Est__c.field-meta.xml
<CustomField>
    <fullName>Hypercare_Est__c</fullName>
    <description>Estimated hours required for hypercare</description>
    <formula>Total_Feature_Est__c * Hypercare__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hypercare Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Management__c.field-meta.xml
<CustomField>
    <fullName>Project_Management__c</fullName>
    <defaultValue>0.25</defaultValue>
    <label>Project Management %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Management_Est__c.field-meta.xml
<CustomField>
    <fullName>Project_Management_Est__c</fullName>
    <description>Estimated hours required for project management</description>
    <formula>Total_Feature_Est__c * Project_Management__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Management Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Proposal_Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Hourly_Rate__c</fullName>
    <defaultValue>137.5</defaultValue>
    <label>Proposal Hourly Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Testing__c.field-meta.xml
<CustomField>
    <fullName>Testing__c</fullName>
    <defaultValue>0.15</defaultValue>
    <label>Testing %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Testing_Est__c.field-meta.xml
<CustomField>
    <fullName>Testing_Est__c</fullName>
    <description>Estimated hours required for testing</description>
    <formula>Total_Feature_Est__c * Testing__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Testing Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Effort__c.field-meta.xml
<CustomField>
    <fullName>Total_Effort__c</fullName>
    <inlineHelpText>Total effort estimate (hours, from work items)</inlineHelpText>
    <label>Total Effort (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/UAT__c.field-meta.xml
<CustomField>
    <fullName>UAT__c</fullName>
    <defaultValue>0.15</defaultValue>
    <label>UAT %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/UAT_Est__c.field-meta.xml
<CustomField>
    <fullName>UAT_Est__c</fullName>
    <description>Estimated hours required for user acceptance testing</description>
    <formula>Total_Feature_Est__c * UAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field shows the Total UAT Time estimated for each Project Feature during the Project Design Phase.</inlineHelpText>
    <label>UAT Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Total_Effort__c.field-meta.xml
<CustomField>
    <fullName>Total_Effort__c</fullName>
    <inlineHelpText>Total estimated effort (hours)</inlineHelpText>
    <label>Total Effort [DEPRECATED]</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Project__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>65000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Est_Time__c.field-meta.xml
<CustomField>
    <fullName>Est_Time__c</fullName>
    <label>Est. Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Importance__c.field-meta.xml
<CustomField>
    <fullName>Importance__c</fullName>
    <description>Importance of the work item</description>
    <label>Importance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Importance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PhaseProposal.cls
// TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
@SuppressWarnings('PMD.ExcessivePublicCount')
public with sharing class PhaseProposal {
  private Phase__c phase;
  //private Project__c project;

  public List<TeamMemberRow> TeamMembers { get; set; } // NOPMD
  public List<FeatureRow> Features { get; set; } // NOPMD
  public List<FeatureRow> OptionalFeatures { get; set; } // NOPMD
  public List<ServiceRow> Services { get; set; } // NOPMD
  public List<AssumptionRow> Assumptions { get; set; } // NOPMD
  public List<LicenseRow> Licenses { get; set; } // NOPMD

  public List<ContentVersion> Files { get; set; } // NOPMD

  public String AccountName { // NOPMD
    get {
      return this.phase.Project__r.Account__r.Name;
    }
  }

  public String ProjectName { // NOPMD
    get {
      return this.phase.Project__r.Name;
    }
  }

  public String PhaseName { // NOPMD
    get {
      return this.phase.Name;
    }
  }

  public String Stage { // NOPMD
    get {
      return this.phase.Stage__c;
    }
  }

  public Boolean hasTableOfContents {
    get {
      return this.phase.Project__r.Hide_Table_of_Contents__c == false;
    }
  }

  public Boolean hasIntroduction {
    get {
      return String.isNotBlank(this.phase.Description__c);
    }
  }

  public String Introduction { // NOPMD
    get {
      return this.hasIntroduction
        ? this.phase.Description__c.replace('<p><br></p>', '')
        : '';
    }
  }

  public Boolean hasChallenges {
    get {
      return String.isNotBlank(this.phase.Project__r.Challenges__c);
    }
  }

  public String Challenges { // NOPMD
    get {
      return this.hasChallenges
        ? this.phase.Project__r.Challenges__c.replace('<p><br></p>', '')
        : '';
    }
  }

  public Boolean hasRequirements {
    get {
      return this.phase.Project__r.Hide_Our_Approach__c == false;
    }
  }

  public Boolean hasProjectManagementDelivery {
    get {
      return this.phase.Project__r.Hide_Project_Management_Delivery__c == false;
    }
  }

  public Boolean hasTeamMembers {
    get {
      return this.TeamMembers.size() > 0;
    }
  }

  public Boolean hasServices {
    get {
      return this.Services.size() > 0 &&
        this.phase.Project__r.Hide_Services__c == false;
    }
  }

  public Decimal ProjectManagementEstTime { // NOPMD
    get {
      return this.phase.Project__r.Project_Management_Est__c;
    }
  }

  public Decimal TestingEstTime { // NOPMD
    get {
      return this.phase.Project__r.Testing_Est__c;
    }
  }

  public Decimal UATEstTime { // NOPMD
    get {
      return this.phase.Project__r.UAT_Est__c;
    }
  }

  public Decimal HypercareEstTime { // NOPMD
    get {
      return this.phase.Project__r.Hypercare_Est__c;
    }
  }

  public Decimal EstTotalProjectManagement { // NOPMD
    get {
      return ((this.phase.Project__r.Project_Management__c / 100) *
        this.phase.Total_Effort__c)
        .setScale(2, RoundingMode.HALF_UP);
    }
  }

  public Decimal EstTotalTesting { // NOPMD
    get {
      return ((this.phase.Project__r.Testing__c / 100) *
        this.phase.Total_Effort__c)
        .setScale(2, RoundingMode.HALF_UP);
    }
  }

  public Decimal EstTotalUAT { // NOPMD
    get {
      return ((this.phase.Project__r.UAT__c / 100) * this.phase.Total_Effort__c)
        .setScale(2, RoundingMode.HALF_UP);
    }
  }

  public Decimal EstTotalHypercare { // NOPMD
    get {
      return ((this.phase.Project__r.Hypercare__c / 100) *
        this.phase.Total_Effort__c)
        .setScale(2, RoundingMode.HALF_UP);
    }
  }

  public Decimal TotalEffort { // NOPMD
    get {
      return this.phase.Total_Effort__c;
    }
  }

  public Decimal TotalEstTime { // NOPMD
    get {
      return (this.TotalEffort).setScale(2, RoundingMode.HALF_UP);
    }
  }

  public Decimal TotalEstDays { // NOPMD
    get {
      return (this.TotalEstTime / 8).setScale(2, RoundingMode.HALF_UP);
    }
  }

  public Decimal TotalEstCost { // NOPMD
    get {
      return this.TotalEstTime * this.phase.Project__r.Proposal_Hourly_Rate__c;
    }
  }

  public String CurrencySymbol { // NOPMD
    get {
      return CurrencyUtils.getSymbol(this.phase.CurrencyIsoCode);
    }
  }

  public Boolean hasAssumptions {
    get {
      return this.phase.Project__r.Hide_Assumptions__c == false;
    }
  }

  public Boolean hasLicenses {
    get {
      return this.Licenses.size() > 0;
    }
  }

  public Decimal ProposalHourlyRate { // NOPMD
    get {
      return this.phase.Project__r.Proposal_Hourly_Rate__c;
    }
  }

  public PhaseProposal(Phase__c phase) {
    this.phase = phase;
    this.Files = new List<ContentVersion>();
    this.TeamMembers = new List<TeamMemberRow>();
    this.Features = new List<FeatureRow>();
    this.OptionalFeatures = new List<FeatureRow>();
    this.Services = new List<ServiceRow>();
    this.Assumptions = new List<AssumptionRow>();
    this.Licenses = new List<LicenseRow>();
  }
  public class TeamMemberRow {
    public String Role { get; set; } // NOPMD
    public String Name { get; set; } // NOPMD
    public String Email { get; set; } // NOPMD
    public String Phone { get; set; } // NOPMD
  }

  public class FeatureRow {
    public String Name { get; private set; } // NOPMD
    public String Description { get; private set; } // NOPMD
    public Decimal EstTime { get; private set; } // NOPMD
    public List<WorkItemRow> WorkItems { get; private set; } // NOPMD
    public Integer WorkItemRowCount { // NOPMD
      get {
        return WorkItems.size();
      }
    }

    public FeatureRow(Project_Feature__c feature, List<WorkItemRow> workItems) {
      this.Name = feature.Name;
      this.Description = String.isNotBlank(feature.Description__c)
        ? feature.Description__c.replace('<p><br></p>', '')
        : '';
      this.EstTime = 0;
      for (WorkItemRow workItem : workItems) {
        this.EstTime += workItem.EstTime;
      }
      this.WorkItems = workItems;
    }
  }

  public class WorkItemRow {
    public String Subject { get; private set; } // NOPMD
    public String Description { get; private set; } // NOPMD
    public String Name { get; private set; } // NOPMD
    public String MSCW { get; private set; } // NOPMD
    public Decimal EstTime { get; private set; } // NOPMD
    public Boolean ShowFeatureName { get; private set; } // NOPMD
    public Boolean HasDescription { // NOPMD
      get {
        return String.isNotBlank(this.Description);
      }
    }

    public WorkItemRow(Work_Item__c workItem, Boolean showFeatureName) {
      this.Subject = workItem.Subject__c;
      this.Description = String.isNotBlank(workItem.Description__c)
        ? workItem.Description__c.replace('<p><br></p>', '')
        : '';
      this.MSCW = this.getMscwFromImportance(workItem.Importance__c);
      this.EstTime = workItem.Est_Time__c;
      this.ShowFeatureName = showFeatureName;
      this.Name = workItem.Name;
    }

    private String getMscwFromImportance(String importance) {
      if (importance == WorkItemImportanceNames.MUST_HAVE_VALUE) {
        return WorkItemImportanceNames.MUST_HAVE_LABEL;
      } else if (importance == WorkItemImportanceNames.SHOULD_HAVE_VALUE) {
        return WorkItemImportanceNames.SHOULD_HAVE_LABEL;
      } else if (importance == WorkItemImportanceNames.COULD_HAVE_VALUE) {
        return WorkItemImportanceNames.COULD_HAVE_LABEL;
      } else if (importance == WorkItemImportanceNames.WONT_HAVE_VALUE) {
        return WorkItemImportanceNames.WONT_HAVE_LABEL;
      }

      return null;
    }
  }

  public class ServiceRow {
    public String Name { get; set; } // NOPMD
    public String Description { get; set; } // NOPMD
    public Decimal EstCost { get; set; } // NOPMD
    public String CurrencySymbol { get; set; } // NOPMD
    public Boolean HasDescription { // NOPMD
      get {
        return String.isNotBlank(this.Description);
      }
    }
  }

  public class AssumptionRow {
    public String Area { get; private set; } // NOPMD
    public String Assumptions { get; private set; } // NOPMD

    public AssumptionRow(String area, String assumptions) {
      this.Area = area;
      this.Assumptions = assumptions;
    }
  }

  public class LicenseRow {
    public String License { get; private set; } // NOPMD
    public Integer Quantity { get; private set; } // NOPMD

    public LicenseRow(String license, Decimal quantity) {
      this.License = license;
      this.Quantity = Integer.valueOf(quantity);
    }
  }
}