force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Start_Date__c)) &amp;&amp; NOT(ISBLANK(End_Date__c)),
    (
        CASE(
            MOD(Start_Date__c - DATE(1985, 6, 24), 7),
            0, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 5, 1), 
            1, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 4, 4, 4, 5, 4, 6, 5, 1), 
            2, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 3, 4, 3, 5, 4, 6, 5, 1), 
            3, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 2, 3, 2, 4, 3, 5, 4, 6, 5, 1), 
            4, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 1, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 1), 
            5, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0), 
            6, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 5, 0), 
            999
        ) 
        + 
        (FLOOR((End_Date__c - Start_Date__c) / 7) * 5)
    ) * 8,
    null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Date__c</fullName>
    <label>Milestone Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Project__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Est_Time__c.field-meta.xml
<CustomField>
    <fullName>Est_Time__c</fullName>
    <label>Est. Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Phase</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Phase__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Scheduled_End__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_End__c</fullName>
    <label>Scheduled End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Scheduled_Start__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Start__c</fullName>
    <label>Scheduled Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>999</defaultValue>
    <inlineHelpText>Lowest at the top</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Under Analysis</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Do</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GanttChartController.cls
public with sharing class GanttChartController {
  @AuraEnabled
  public static String getEntityType(Id recordId) {
    return recordId.getSobjectType().getDescribe().getName();
  }

  @AuraEnabled
  public static List<GanttChartTaskTransformer> getTasks(Id recordId) {
    String entityType = getEntityType(recordId);

    switch on entityType {
      when 'Account' {
        List<String> projectStatuses = new List<String>{
          ProjectStatusNames.Estimate,
          ProjectStatusNames.KickOff,
          ProjectStatusNames.InProgress,
          ProjectStatusNames.Uat,
          ProjectStatusNames.HyperCare,
          ProjectStatusNames.Support
        };

        List<SObject> projectList = new List<SObject>(
          Database.query(
            'SELECT Id, Name, Start_Date__c, End_Date__c, Duration__c ' +
              'FROM Project__c ' +
              'WHERE Account__c = :recordId ' +
              'AND Status__c IN :projectStatuses ' +
              'AND Start_Date__c != NULL ' +
              'AND End_Date__c != NULL ' +
              'ORDER BY Sort_Order__c ASC'
          )
        );

        return appendProjectWorkItemStats(projectList);
      }
      when 'Project__c' {
        List<SObject> phaseList = new List<SObject>(
          Database.query(
            'SELECT Id, Name, Start_Date__c, End_Date__c, Duration__c, Milestone_Date__c, ' +
              '(SELECT Id, Name, Subject__c, Est_Time__c, Scheduled_Start__c, Scheduled_End__c FROM Work_Items__r ORDER BY Sort_Order__c ASC) ' +
              'FROM Phase__c ' +
              'WHERE Project__c = :recordId ' +
              'AND ((Start_Date__c != NULL AND End_Date__c != NULL) OR Milestone_Date__c != NULL) ' +
              'ORDER BY Sort_Order__c ASC'
          )
        );

        return appendPhaseWorkItemStats(phaseList);
      }
      when else {
        throw new AuraHandledException(
          'Unsupported object type: ' + entityType
        );
      }
    }
  }

  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ApexCRUDViolation')
  private static List<GanttChartTaskTransformer> appendPhaseWorkItemStats(
    List<SObject> phaseList
  ) {
    List<Id> phaseIds = new List<Id>();

    for (SObject phase : phaseList) {
      phaseIds.add(phase.Id);
    }

    List<Work_Item__c> workItemList = [
      SELECT Id, Est_Time__c, Status__c, Project_Phase__c
      FROM Work_Item__c
      WHERE
        Project_Phase__c IN :phaseIds
        AND Status__c IN (
          :WorkItemStatusNames.Approved,
          :WorkItemStatusNames.Blocked,
          :WorkItemStatusNames.InProgress,
          :WorkItemStatusNames.Implemented,
          :WorkItemStatusNames.Accepted,
          :WorkItemStatusNames.Rejected,
          :WorkItemStatusNames.Deployed
        )
        AND Est_Time__c != NULL
    ];

    Map<Id, Decimal> phaseTotalHoursMap = new Map<Id, Decimal>();

    for (Work_Item__c workItem : workItemList) {
      if (!phaseTotalHoursMap.containsKey(workItem.Project_Phase__c)) {
        phaseTotalHoursMap.put(workItem.Project_Phase__c, 0);
      }

      phaseTotalHoursMap.put(
        workItem.Project_Phase__c,
        (phaseTotalHoursMap.get(workItem.Project_Phase__c) +
        workItem.Est_Time__c)
      );
    }

    List<GanttChartTaskTransformer> phases = new List<GanttChartTaskTransformer>();

    for (SObject phase : phaseList) {
      phases.add(
        new GanttChartTaskTransformer(phase, phaseTotalHoursMap.get(phase.Id))
      );
    }

    return phases;
  }

  private static List<GanttChartTaskTransformer> appendProjectWorkItemStats(
    List<SObject> projectList
  ) {
    List<GanttChartTaskTransformer> projects = new List<GanttChartTaskTransformer>();

    for (SObject project : projectList) {
      projects.add(new GanttChartTaskTransformer(project, 0));
    }

    return projects;
  }

  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ExcessiveParameterList, PMD.ApexCRUDViolation')
  @AuraEnabled
  public static Boolean updateDates(
    Id recordId,
    String startDate,
    String endDate,
    String milestoneDate
  ) {
    try {
      SObject obj = recordId.getSobjectType().newSObject(recordId);

      if (String.isNotBlank(startDate) && String.isNotBlank(endDate)) {
        obj.put('Start_Date__c', Date.valueOf(startDate));
        obj.put('End_Date__c', Date.valueOf(endDate));
      } else if (String.isNotBlank(milestoneDate)) {
        obj.put('Milestone_Date__c', Date.valueOf(milestoneDate));
      }

      update obj;

      return true;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ApexCRUDViolation')
  @AuraEnabled
  public static Boolean updateWorkItem(
    Id recordId,
    String startDate,
    String endDate
  ) {
    try {
      SObject obj = recordId.getSobjectType().newSObject(recordId);

      if (String.isNotBlank(startDate) && String.isNotBlank(endDate)) {
        obj.put('Scheduled_Start__c', Date.valueOf(startDate));
        // obj.put('Est_Time__c', estimatedTime);
        obj.put('Scheduled_End__c', Date.valueOf(endDate));
      }

      update obj;

      return true;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ApexCRUDViolation')
  @AuraEnabled
  public static Boolean updateOrder(List<Id> ids) {
    try {
      List<SObject> sObjectsToUpdate = new List<SObject>();
      Integer sortOrder = 1;

      for (Id id : ids) {
        SObject obj = id.getSobjectType().newSObject(id);
        obj.put('Sort_Order__c', sortOrder);
        sObjectsToUpdate.add(obj);

        sortOrder++;
      }

      update sObjectsToUpdate;

      return true;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}