force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/Salesforce_License__c.object-meta.xml
<CustomObject>
    <label>Salesforce License</label>
    <nameField>
        <displayFormat>SFL-{0000}</displayFormat>
        <label>Salesforce License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_License__c/fields/Salesforce_License__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_License__c</fullName>
    <formula>HYPERLINK(Id, TEXT( License__c ) , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesforce License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Third_Party_Service__c/Third_Party_Service__c.object-meta.xml
<CustomObject>
    <label>Third Party Service</label>
    <nameField>
        <displayFormat>TPS-{00000}</displayFormat>
        <label>Third Party Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PhaseProposalBuilder.cls
public with sharing class PhaseProposalBuilder {
    private PhaseProposalFactory factory;
    private PhaseProposalDataAccess dataAccess;

    public PhaseProposalBuilder() {
        factory = new PhaseProposalFactory();
        dataAccess = new PhaseProposalDataAccess();
    }

    public PhaseProposal Build(Id phaseId) {
        Phase__c phase = dataAccess.getPhases(phaseId);
        List<Project_Feature__c> features = dataAccess.getFeatures(phaseId);
        //List<Third_Party_Service__c> services = dataAccess.getServices(phaseId);
        //List<Salesforce_License__c> licenses = dataAccess.getLicesnses(phaseId);

        PhaseProposal proposal = new PhaseProposal(phase);
        proposal.Features = factory.createFeatures(features);
        proposal.OptionalFeatures = factory.createOptionalFeatures(features);
        proposal.Files = dataAccess.getFiles(phaseId);
        //proposal.Services = factory.createServices(services);
        //proposal.TeamMembers = factory.createTeamMembers(dataAccess.getProjectTeamMembers(phaseId));
        // proposal.Assumptions = factory.createAssumptions(features);
        //proposal.Licenses = factory.createLicenses(licenses);

        return proposal;
    }
}