force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
                <default>true</default>
                <label>Project</label>
            </value>
            <value>
                <fullName>Managed Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Phase</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Phase__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Under Analysis</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Do</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Item</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProjectCopyServiceTest.cls
@isTest
private class ProjectCopyServiceTest {
  @isTest
  static void testCopyProjectPhases() {
    // Arrange
    Id accountId = AccountTestDataFactory.create('Test Account');
    Id oldProjectId = ProjectTestDataFactory.create(accountId);
    Id newProjectId = ProjectTestDataFactory.create(accountId);
    List<Phase__c> oldProjectPhaseList = new List<Phase__c>{
      PhaseTestDataFactory.create(oldProjectId),
      PhaseTestDataFactory.create(oldProjectId)
    };
    insert oldProjectPhaseList;

    // Act
    Test.startTest();
    Map<Id, Id> oldToNewProjectPhaseIdMap = ProjectCopyService.copyProjectPhases(
      oldProjectPhaseList,
      new Map<Id, Id>{ oldProjectId => newProjectId }
    );
    Test.stopTest();

    // Assert
    System.assertEquals(
      2,
      oldToNewProjectPhaseIdMap.size(),
      'oldToNewProjectPhaseIdMap should have 2 entries'
    );

    List<Phase__c> newProjectPhaseList = [
      SELECT Id
      FROM Phase__c
      WHERE Project__c = :newProjectId
    ];

    System.assertEquals(
      2,
      newProjectPhaseList.size(),
      'newProjectPhaseList should have 2 entries'
    );
  }

  @isTest
  static void testCopyProjectFeatures() {
    // Arrange
    Id accountId = AccountTestDataFactory.create('Test Account');
    Id oldProjectId = ProjectTestDataFactory.create(accountId);
    Id newProjectId = ProjectTestDataFactory.create(accountId);

    Phase__c oldProjectPhase = PhaseTestDataFactory.create(oldProjectId);
    insert oldProjectPhase;

    Phase__c newProjectPhase = PhaseTestDataFactory.create(newProjectId);
    insert newProjectPhase;

    Project_Feature__c oldProjectFeature1 = new Project_Feature__c();
    oldProjectFeature1.Name = 'Test Feature 1';
    oldProjectFeature1.Project__c = oldProjectId;
    oldProjectFeature1.Phase__c = oldProjectPhase.Id;

    Project_Feature__c oldProjectFeature2 = new Project_Feature__c();
    oldProjectFeature2.Name = 'Test Feature 2';
    oldProjectFeature2.Project__c = oldProjectId;
    oldProjectFeature2.Phase__c = oldProjectPhase.Id;

    List<Project_Feature__c> oldProjectFeatureList = new List<Project_Feature__c>{
      oldProjectFeature1,
      oldProjectFeature2
    };
    insert oldProjectFeatureList;

    // Act
    Test.startTest();
    Map<Id, Id> oldToNewProjectFeatureIdMap = ProjectCopyService.copyProjectFeatures(
      oldProjectFeatureList,
      new Map<Id, Id>{ oldProjectId => newProjectId },
      new Map<Id, Id>{ oldProjectPhase.Id => newProjectPhase.Id }
    );
    Test.stopTest();

    // Assert
    System.assertEquals(
      2,
      oldToNewProjectFeatureIdMap.size(),
      'oldToNewProjectFeatureIdMap should have 2 entries'
    );

    List<Project_Feature__c> newProjectFeatureList = [
      SELECT Id
      FROM Project_Feature__c
      WHERE Project__c = :newProjectId AND Phase__c = :newProjectPhase.Id
    ];

    System.assertEquals(
      2,
      newProjectFeatureList.size(),
      'newProjectFeatureList should have 2 entries'
    );
  }

  @isTest
  static void testCopyWorkItems() {
    // Arrange
    Id accountId = AccountTestDataFactory.create('Test Account');
    Id oldProjectId = ProjectTestDataFactory.create(accountId);
    Id newProjectId = ProjectTestDataFactory.create(accountId);

    Phase__c oldProjectPhase = PhaseTestDataFactory.create(oldProjectId);
    insert oldProjectPhase;

    Phase__c newProjectPhase = PhaseTestDataFactory.create(newProjectId);
    insert newProjectPhase;

    Project_Feature__c oldProjectFeature = new Project_Feature__c();
    oldProjectFeature.Name = 'Test Feature';
    oldProjectFeature.Project__c = oldProjectId;
    oldProjectFeature.Phase__c = oldProjectPhase.Id;
    insert oldProjectFeature;

    Project_Feature__c newProjectFeature = new Project_Feature__c();
    newProjectFeature.Name = 'Test Feature';
    newProjectFeature.Project__c = newProjectId;
    newProjectFeature.Phase__c = newProjectPhase.Id;
    insert newProjectFeature;

    Work_Item__c workItem1 = new Work_Item__c();
    workItem1.Project__c = oldProjectId;
    workItem1.Project_Phase__c = oldProjectPhase.Id;
    workItem1.Feature__c = oldProjectFeature.Id;
    workItem1.Subject__c = 'Test Work Item 1';
    workItem1.Type__c = 'Work Item';
    workItem1.Status__c = WorkItemStatusNames.Backlog;
    insert workItem1;

    Work_Item__c workItem2 = new Work_Item__c();
    workItem2.Project__c = oldProjectId;
    workItem2.Project_Phase__c = oldProjectPhase.Id;
    workItem2.Feature__c = oldProjectFeature.Id;
    workItem2.Subject__c = 'Test Work Item 2';
    workItem2.Type__c = 'Work Item';
    workItem2.Status__c = WorkItemStatusNames.Backlog;
    insert workItem2;

    List<Work_Item__c> oldWorkItemList = new List<Work_Item__c>{
      workItem1,
      workItem2
    };

    // Act
    Test.startTest();
    Map<Id, Id> oldToNewWorkItemIdMap = ProjectCopyService.copyWorkItems(
      oldWorkItemList,
      new Map<Id, Id>{ oldProjectId => newProjectId },
      new Map<Id, Id>{ oldProjectPhase.Id => newProjectPhase.Id },
      new Map<Id, Id>{ oldProjectFeature.Id => newProjectFeature.Id }
    );
    Test.stopTest();

    // Assert
    System.assertEquals(
      2,
      oldToNewWorkItemIdMap.size(),
      'oldToNewWorkItemIdMap should have 2 entries'
    );

    List<Work_Item__c> newWorkItemList = [
      SELECT Id
      FROM Work_Item__c
      WHERE
        Project__c = :newProjectId
        AND Project_Phase__c = :newProjectPhase.Id
        AND Feature__c = :newProjectFeature.Id
    ];

    System.assertEquals(
      2,
      newWorkItemList.size(),
      'newWorkItemList should have 2 entries'
    );
  }
}