force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Meeting__c/Project_Meeting__c.object-meta.xml
<CustomObject>
    <label>Project Meeting</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Project Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Meeting__c/fields/Date_of_Next_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Next_Meeting__c</fullName>
    <label>Date of Next Meeting</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Meeting__c/fields/Demo__c.field-meta.xml
<CustomField>
    <fullName>Demo__c</fullName>
    <label>Demo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project_Meeting__c/fields/Holidays__c.field-meta.xml
<CustomField>
    <fullName>Holidays__c</fullName>
    <label>Holidays</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project_Meeting__c/fields/Project_Report_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Report_Name__c</fullName>
    <defaultValue>&quot;Weekly Status Report&quot;</defaultValue>
    <label>Project Report Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Meeting__c/fields/Weekly_Status_Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Status_Report_Date__c</fullName>
    <label>Weekly Status Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/RAID_Log__c.object-meta.xml
<CustomObject>
    <label>RAID Log</label>
    <nameField>
        <displayFormat>RAID-{000000}</displayFormat>
        <label>RAID Log Entry Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAID Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RAID_Log__c/fields/Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Assign_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assign To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RAID_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Strategic</fullName>
                <label>1 - Highest</label>
            </value>
            <value>
                <fullName>Critical</fullName>
                <label>2 - High</label>
            </value>
            <value>
                <fullName>Moderate</fullName>
                <label>3 - Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
                <label>4 - Low</label>
            </value>
            <value>
                <fullName>5 - Lowest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Update__c.field-meta.xml
<CustomField>
    <fullName>Update__c</fullName>
    <label>Update</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RAID_Log__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Item</label>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>RAID Log</relationshipLabel>
    <relationshipName>RAID_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/UAT_Feedback__c.object-meta.xml
<CustomObject>
    <description>The UAT Feedback custom object is used to collect and track User Acceptance Testing feedback from customers. The object contains information about the feedback, including the description, type, status, priority, and date, as well as the customer who provided the feedback. This information is used to improve the product and processes and to provide insights into customer feedback.</description>
    <label>UAT Feedback</label>
    <nameField>
        <displayFormat>UAT-{00000000}</displayFormat>
        <label>UAT No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UAT Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UAT_Feedback__c/fields/Blocked_Reason__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Reason__c</fullName>
    <description>Reason for UAT Feedback being blocked</description>
    <label>Blocked Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Feedback_Subject__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Subject__c</fullName>
    <description>A field for customers to submit a brief descriptions about issues, questions and new change requests that have arisen during UAT.</description>
    <inlineHelpText>Please provide a brief description of the issue you are reporting.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Open_Count__c.field-meta.xml
<CustomField>
    <fullName>Open_Count__c</fullName>
    <label>Open Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Re_Test_Count__c.field-meta.xml
<CustomField>
    <fullName>Re_Test_Count__c</fullName>
    <label>Re-Test Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Status_UAT_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Status_UAT_Feedback__c</fullName>
    <description>A field to record and display what the status of a UAT feedback record is.</description>
    <inlineHelpText>Please update the status of your UAT feedback.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <color>#FFFFFF</color>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <color>#FF6666</color>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>WIP</fullName>
                <color>#FFFF66</color>
                <label>WIP</label>
            </value>
            <value>
                <fullName>Re-Test</fullName>
                <color>#FF9966</color>
                <label>Re-Test</label>
            </value>
            <value>
                <fullName>Closed</fullName>
                <color>#9999FF</color>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/WIP_Count__c.field-meta.xml
<CustomField>
    <fullName>WIP_Count__c</fullName>
    <label>WIP Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UAT_Feedback__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup field to create a relationship between the UAT Feedback and Work Item tab</description>
    <inlineHelpText>Please select the work item that this is related to.</inlineHelpText>
    <label>Work Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Work_Item__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project_UAT__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Work_Item__c</referenceTo>
    <relationshipLabel>UAT Feedback</relationshipLabel>
    <relationshipName>UAT_Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Blocked_Age__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Age__c</fullName>
    <label>Blocked Age</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Blocked_Reason__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Reason__c</fullName>
    <label>Blocked Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Est_Time__c.field-meta.xml
<CustomField>
    <fullName>Est_Time__c</fullName>
    <label>Est. Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Set_to_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Set_to_Blocked__c</fullName>
    <description>The date the WI was set to the Status Blocked</description>
    <label>Set to Blocked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Under Analysis</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Do</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeeklyStatusReportFactory.cls
@SuppressWarnings('PMD.ExcessivePublicCount, PMD.CyclomaticComplexity')
public with sharing class WeeklyStatusReportFactory {
  public List<WeeklyStatusReport.PhaseRow> createPhases(
    List<Phase__c> phaseList
  ) {
    List<WeeklyStatusReport.PhaseRow> rowList = new List<WeeklyStatusReport.PhaseRow>();

    for (Phase__c phase : phaseList) {
      WeeklyStatusReport.PhaseRow row = new WeeklyStatusReport.PhaseRow();
      row.Name = phase.Name;
      row.StartDate = phase.Start_Date__c;
      row.EndDate = phase.End_Date__c;

      rowList.add(row);
    }

    return rowList;
  }

  public List<WeeklyStatusReport.UATRow> createOpenUATItems(
    List<UAT_Feedback__c> uatList
  ) {
    return this.createUATItems(uatList, UATItemStatusNames.Open);
  }
  public List<WeeklyStatusReport.UATRow> createWIPUATItems(
    List<UAT_Feedback__c> uatList
  ) {
    return this.createUATItems(uatList, UATItemStatusNames.WIP);
  }
  public List<WeeklyStatusReport.UATRow> createReTestUATItems(
    List<UAT_Feedback__c> uatList
  ) {
    return this.createUATItems(uatList, UATItemStatusNames.ReTest);
  }
  public List<WeeklyStatusReport.UATRow> createClosedUATItems(
    List<UAT_Feedback__c> uatList
  ) {
    return this.createUATItems(uatList, UATItemStatusNames.Closed);
  }

  @TestVisible
  private List<WeeklyStatusReport.UATRow> createUATItems(
    List<UAT_Feedback__c> uatList,
    String status
  ) {
    List<WeeklyStatusReport.UATRow> rowList = new List<WeeklyStatusReport.UATRow>();

    for (UAT_Feedback__c uat : uatList) {
      if (status != null && uat.Status_UAT_Feedback__c != status) {
        continue;
      }

      WeeklyStatusReport.UATRow row = new WeeklyStatusReport.UATRow();
      row.Status = uat.Status_UAT_Feedback__c;
      row.Subject = uat.Feedback_Subject__c;
      row.OpenStatusCount = uat.Open_Count__c;
      row.WIPStatusCount = uat.WIP_Count__c;
      row.ReTestStatusCount = uat.Re_Test_Count__c;
      row.ClosedStatusCount = uat.Closed_Count__c;

      rowList.add(row);
    }

    return rowList;
  }

  public WeeklyStatusReport.MeetingRow createMeeting(
    List<Project_Meeting__c> meetingList
  ) {
    WeeklyStatusReport.MeetingRow row = new WeeklyStatusReport.MeetingRow();

    if (meetingList.size() == 0) {
      return row;
    }

    Project_Meeting__c meeting = meetingList[0];

    row.Created = meeting.CreatedDate;
    row.Notes = meeting.Notes__c;
    row.ReportName = meeting.Project_Report_Name__c;
    row.ReportDate = meeting.Weekly_Status_Report_Date__c;
    row.Demo = meeting.Demo__c;
    row.Holidays = meeting.Holidays__c;
    row.NextMeeting = meeting.Date_of_Next_Meeting__c;

    return row;
  }

  public List<WeeklyStatusReport.RaidLogRow> createCriticalIssueLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      null,
      RaidLogRatingNames.Critical,
      null
    );
  }

  public List<WeeklyStatusReport.RaidLogRow> createOpenRiskLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      RaidLogStatusNames.Open,
      null,
      RaidLogUtils.getRiskRecordTypeId
    );
  }

  public List<WeeklyStatusReport.RaidLogRow> createOpenActionLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      RaidLogStatusNames.Open,
      null,
      RaidLogUtils.getActionRecordTypeId
    );
  }

  public List<WeeklyStatusReport.RaidLogRow> createOpenIssueLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      RaidLogStatusNames.Open,
      null,
      RaidLogUtils.getIssueRecordTypeId
    );
  }

  public List<WeeklyStatusReport.RaidLogRow> createOpenDecisionLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      RaidLogStatusNames.Open,
      null,
      RaidLogUtils.getDecisionRecordTypeId
    );
  }

  public List<WeeklyStatusReport.RaidLogRow> createClosedRiskLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      RaidLogStatusNames.Closed,
      null,
      RaidLogUtils.getRiskRecordTypeId
    );
  }

  public List<WeeklyStatusReport.RaidLogRow> createClosedActionLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      RaidLogStatusNames.Closed,
      null,
      RaidLogUtils.getActionRecordTypeId
    );
  }

  public List<WeeklyStatusReport.RaidLogRow> createClosedIssueLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      RaidLogStatusNames.Closed,
      null,
      RaidLogUtils.getIssueRecordTypeId
    );
  }

  public List<WeeklyStatusReport.RaidLogRow> createClosedDecisionLogs(
    List<RAID_Log__c> logList
  ) {
    return this.createRaidLogs(
      logList,
      RaidLogStatusNames.Closed,
      null,
      RaidLogUtils.getDecisionRecordTypeId
    );
  }

  @SuppressWarnings('PMD.OperationWithLimitsInLoop')
  public List<WeeklyStatusReport.RaidLogRow> createRaidLogs(
    List<RAID_Log__c> source
  ) {
    Map<String, List<WeeklyStatusReport.RaidLogItemRow>> raidLogsByType = new Map<String, List<WeeklyStatusReport.RaidLogItemRow>>();

    for (RAID_Log__c raidLog : source) {
      Boolean isFirstOfType = false;
      String type = [
        SELECT Name, RecordType.DeveloperName
        FROM RecordType
        WHERE Id = :raidLog.RecordTypeId
      ]
      .Name;
      String s1 = raidLog.Name;
      String s2 = s1.substringAfter('-');

      if (raidLog.Status__c == RaidLogStatusNames.Open) {
        if (!raidLogsByType.containsKey(type)) {
          isFirstOfType = true;
          raidLogsByType.put(
            type,
            new List<WeeklyStatusReport.RaidLogItemRow>()
          );
        }

        raidLogsByType.get(type)
          .add(
            new WeeklyStatusReport.RaidLogItemRow(
              s2,
              raidLog.CreatedDate,
              raidLog.Assign_To__r.Name,
              raidLog.Update__c,
              raidLog.Rating__c,
              raidLog.Subject__c,
              isFirstOfType
            )
          );
      }
    }

    List<WeeklyStatusReport.RaidLogRow> target = new List<WeeklyStatusReport.RaidLogRow>();

    for (String raidLogType : raidLogsByType.keySet()) {
      target.add(
        new WeeklyStatusReport.RaidLogRow(
          raidLogType,
          raidLogsByType.get(raidLogType)
        )
      );
    }

    return target;
  }

  private List<WeeklyStatusReport.RaidLogRow> createRaidLogs( //NOPMD
    List<RAID_Log__c> logList,
    String status,
    String rating,
    Id recordTypeId
  ) {
    List<WeeklyStatusReport.RaidLogRow> rowList = new List<WeeklyStatusReport.RaidLogRow>();

    for (RAID_Log__c log : logList) {
      if (status != null && log.Status__c != status) {
        continue;
      }

      if (rating != null && log.Rating__c != rating) {
        continue;
      }

      if (recordTypeId != null && log.RecordTypeId != recordTypeId) {
        continue;
      }
    }

    return rowList;
  }

  public List<WeeklyStatusReport.WorkItemRow> createWorkItems(
    List<Work_Item__c> workItemList,
    String status
  ) {
    List<WeeklyStatusReport.WorkItemRow> rowList = new List<WeeklyStatusReport.WorkItemRow>();

    for (Work_Item__c workItem : workItemList) {
      if (status != null && workItem.Status__c != status) {
        continue;
      }
      WeeklyStatusReport.WorkItemRow row = new WeeklyStatusReport.WorkItemRow();
      row.Status = workItem.Status__c;
      row.Feature = workItem.Feature__r.Name;
      row.Reference = workItem.Name;
      row.Subject = workItem.Subject__c;
      row.EstimatedTime = workItem.Est_Time__c;
      row.BlockedDate = workItem.Set_to_Blocked__c;
      row.BlockedReason = workItem.Blocked_Reason__c;
      row.BlockedAge = workItem.Blocked_Age__c;

      rowList.add(row);
    }

    return rowList;
  }

  public List<WeeklyStatusReport.WorkItemRow> createBlockedWorkItems(
    List<Work_Item__c> blockedList
  ) {
    return this.createWorkItems(blockedList, WorkItemStatusNames.Blocked);
  }
}