force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Start_Date__c)) &amp;&amp; NOT(ISBLANK(End_Date__c)),
    (
        CASE(
            MOD(Start_Date__c - DATE(1985, 6, 24), 7),
            0, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 5, 1), 
            1, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 4, 4, 4, 5, 4, 6, 5, 1), 
            2, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 3, 3, 3, 4, 3, 5, 4, 6, 5, 1), 
            3, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 2, 2, 2, 3, 2, 4, 3, 5, 4, 6, 5, 1), 
            4, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 1, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 1), 
            5, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 0), 
            6, CASE(MOD(End_Date__c - Start_Date__c, 7), 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 5, 0), 
            999
        ) 
        + 
        (FLOOR((End_Date__c - Start_Date__c) / 7) * 5)
    ) * 8,
    null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Date__c</fullName>
    <label>Milestone Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Support_Type__c.field-meta.xml
<CustomField>
    <fullName>Support_Type__c</fullName>
    <label>Support Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GanttChartTaskTransformerTest.cls
@isTest
public class GanttChartTaskTransformerTest {
    @isTest
    public static void test_project() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();

        Project__c project = new Project__c();
        project.Account__c = accountId;
        project.Name = 'Test Project';
        project.Start_Date__c = Date.newInstance(2020, 6, 1);
        project.End_Date__c = Date.newInstance(2020, 12, 31);
        project.Duration__c = 200;
        project.Support_Type__c = 'MSA';
        insert project;

        List<Project__c> projectList = [SELECT Id, Name, Start_Date__c, End_Date__c, Duration__c FROM Project__c WHERE Id = :project.Id];

        // Act
        Test.startTest();
        GanttChartTaskTransformer transformer = new GanttChartTaskTransformer(projectList[0], 50);
        Test.stopTest();

        // Assert
        System.assertEquals(project.Id, transformer.getId());
        System.assertEquals(project.Name, transformer.getName());
        System.assertEquals(project.Start_Date__c, transformer.getStartDate());
        System.assertEquals(project.End_Date__c, transformer.getEndDate());
        System.assertEquals(null, transformer.getMilestoneDate());
        System.assertEquals(200, transformer.getDuration());
        System.assertEquals(50, transformer.getTotalHours());
        System.assertEquals(25, transformer.getPercentAllocated());
    }

    @isTest
    public static void test_phase() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();
        Id projectId = ProjectTestDataFactory.create(accountId);

        Phase__c phase = new Phase__c();
        phase.Project__c = projectId;
        phase.Name = 'Test Phase';
        phase.Start_Date__c = Date.newInstance(2021, 11, 29);
        phase.End_Date__c = Date.newInstance(2021, 12, 31);
        phase.Milestone_Date__c = Date.newInstance(2021, 12, 24);
        insert phase;

        List<Phase__c> phaseList = [SELECT Id, Name, Start_Date__c, End_Date__c, Duration__c, Milestone_Date__c FROM Phase__c WHERE Id = :phase.Id];

        // Act
        Test.startTest();
        GanttChartTaskTransformer transformer = new GanttChartTaskTransformer(phaseList[0], 50);
        Test.stopTest();

        // Assert
        System.assertEquals(phase.Id, transformer.getId());
        System.assertEquals(phase.Name, transformer.getName());
        System.assertEquals(phase.Start_Date__c, transformer.getStartDate());
        System.assertEquals(phase.End_Date__c, transformer.getEndDate());
        System.assertEquals(phase.Milestone_Date__c, transformer.getMilestoneDate());
        System.assertEquals(200, transformer.getDuration());
        System.assertEquals(50, transformer.getTotalHours());
        System.assertEquals(25, transformer.getPercentAllocated());
    }
}