force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Date__c</fullName>
    <label>Milestone Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PhaseTestDataFactory.cls
public class PhaseTestDataFactory {
  public static Phase__c create(Id projectId) {
    return create(projectId, 'Phase X');
  }

  public static Phase__c create(Id projectId, String name) {
    Phase__c phase = new Phase__c();
    phase.Name = name;
    phase.Project__c = projectId;
    phase.Start_Date__c = Date.today();
    phase.End_Date__c = (Date.today() + 28);

    return phase;
  }

  public static Phase__c createWithDates(
    Id projectId,
    Date startDate,
    Date endDate
  ) {
    Phase__c phase = create(projectId);
    phase.Start_Date__c = startDate;
    phase.End_Date__c = endDate;

    return phase;
  }

  public static Phase__c createMilestone(Id projectId, Date milestoneDate) {
    Phase__c phase = new Phase__c();
    phase.Name = 'Milestone X';
    phase.Project__c = projectId;
    phase.Milestone_Date__c = milestoneDate;

    return phase;
  }
}