force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Milestone_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Date__c</fullName>
    <label>Milestone Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PhaseTestDataFactoryTest.cls
@isTest
public class PhaseTestDataFactoryTest {
    @isTest
    public static void test_create() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();
        Id projectId = ProjectTestDataFactory.create(accountId);

        // Act
        Phase__c phase = PhaseTestDataFactory.create(projectId);
        insert phase;

        // Assert
        System.assertEquals('Phase X', phase.Name);
        System.assertEquals(projectId, phase.Project__c);
        System.assertEquals(Date.today(), phase.Start_Date__c);
        System.assertEquals((Date.today() + 28), phase.End_Date__c);
    }

    @isTest
    public static void test_create_with_name() {
        // Arrange
        Id accountId = AccountTestDataFactory.create();
        Id projectId = ProjectTestDataFactory.create(accountId);

        // Act
        Phase__c phase = PhaseTestDataFactory.create(projectId, 'Phase 1');
        insert phase;

        // Assert
        System.assertEquals('Phase 1', phase.Name);
    }

    @isTest
    public static void test_create_with_dates() {
        // Arrange
        final Date START_DATE = Date.newInstance(2020, 1, 1);
        final Date END_DATE = Date.newInstance(2020, 2, 28);

        Id accountId = AccountTestDataFactory.create();
        Id projectId = ProjectTestDataFactory.create(accountId);

        // Act
        Phase__c phase = PhaseTestDataFactory.createWithDates(projectId, START_DATE, END_DATE);
        insert phase;

        // Assert
        System.assertEquals(START_DATE, phase.Start_Date__c);
        System.assertEquals(END_DATE, phase.End_Date__c);
    }

    @isTest
    public static void test_create_milestone() {
        // Arrange
        final Date MILESTONE_DATE = Date.newInstance(2020, 1, 1);

        Id accountId = AccountTestDataFactory.create();
        Id projectId = ProjectTestDataFactory.create(accountId);

        // Act
        Phase__c phase = PhaseTestDataFactory.createMilestone(projectId, MILESTONE_DATE);
        insert phase;

        // Assert
        System.assertEquals('Milestone X', phase.Name);
        System.assertEquals(MILESTONE_DATE, phase.Milestone_Date__c);
    }
}