force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Amber</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phase__c/recordTypes/Phase.recordType-meta.xml
<RecordType>
    <fullName>Phase</fullName>
    <active>true</active>
    <label>Phase</label>
</RecordType>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Meeting__c/Project_Meeting__c.object-meta.xml
<CustomObject>
    <label>Project Meeting</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Project Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Blocked_Age__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Age__c</fullName>
    <label>Blocked Age</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Blocked_Reason__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Reason__c</fullName>
    <label>Blocked Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Est_Time__c.field-meta.xml
<CustomField>
    <fullName>Est_Time__c</fullName>
    <label>Est. Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Set_to_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Set_to_Blocked__c</fullName>
    <description>The date the WI was set to the Status Blocked</description>
    <label>Set to Blocked</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Under Analysis</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Implemented</fullName>
            </value>
            <value>
                <fullName>Won&apos;t Do</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeeklyStatusReportFactoryTest.cls
@isTest
public class WeeklyStatusReportFactoryTest {
  @isTest
  public static void testCreatePhases() {
    // Arrange
    Id accountId = AccountTestDataFactory.create();
    Id projectId = ProjectTestDataFactory.create(accountId);
    List<Phase__c> phaseList = new List<Phase__c>{
      PhaseTestDataFactory.create(projectId, 'Phase 1'),
      PhaseTestDataFactory.create(projectId, 'Phase 2')
    };

    // Act
    WeeklyStatusReportFactory factory = new WeeklyStatusReportFactory();
    List<WeeklyStatusReport.PhaseRow> rows = factory.createPhases(phaseList);

    // Assert
    System.assertEquals(2, rows.size(), 'There should be 2 rows');
    System.assertEquals(
      'Phase 1',
      rows[0].Name,
      'The first row should be Phase 1'
    );
    System.assertEquals(
      'Phase 2',
      rows[1].Name,
      'The second row should be Phase 2'
    );
  }

  @isTest
  public static void testCreateMeeting() {
    // Arrange
    Id accountId = AccountTestDataFactory.create();
    Id projectId = ProjectTestDataFactory.create(accountId);
    List<Project_Meeting__c> meetingList = new List<Project_Meeting__c>{
      ProjectMeetingTestDataFactory.create(projectId)
    };

    // Act
    WeeklyStatusReportFactory factory = new WeeklyStatusReportFactory();
    WeeklyStatusReport.MeetingRow row = factory.createMeeting(meetingList);

    // Assert
    System.assertEquals(
      'Meeting minutes.',
      row.Notes,
      'The notes should be "Meeting minutes."'
    );
    System.assertEquals(
      Date.today(),
      row.ReportDate,
      'The report date should be today'
    );
  }

  @isTest
  public static void testCreateWorkItems() {
    // Arrange
    Id accountId = AccountTestDataFactory.create();
    Id projectId = ProjectTestDataFactory.create(accountId);
    Id featureId = ProjectFeatureTestDataFactory.create(projectId);
    Id workItem1Id = WorkItemTestDataFactory.create(
      projectId,
      featureId,
      WorkItemStatusNames.Blocked,
      'Testing blocked work item'
    );
    Id workItem2Id = WorkItemTestDataFactory.create(
      projectId,
      featureId,
      WorkItemStatusNames.Blocked,
      'Testing blocked work item'
    );
    Id workItem3Id = WorkItemTestDataFactory.create(
      projectId,
      featureId,
      WorkItemStatusNames.Approved,
      ''
    );
    Id workItem4Id = WorkItemTestDataFactory.create(
      projectId,
      featureId,
      WorkItemStatusNames.Backlog,
      ''
    );

    List<Work_Item__c> workItemList = [
      SELECT
        Status__c,
        Feature__r.Name,
        Name,
        Subject__c,
        Est_Time__c,
        Set_to_Blocked__c,
        Blocked_Reason__c,
        Blocked_Age__c
      FROM Work_Item__c
      WHERE Id IN (:workItem1Id, :workItem2Id, :workItem3Id, :workItem4Id)
    ];

    // Act
    WeeklyStatusReportFactory factory = new WeeklyStatusReportFactory();
    List<WeeklyStatusReport.WorkItemRow> rows = factory.createWorkItems(
      workItemList,
      WorkItemStatusNames.Blocked
    );

    // Assert
    Assert.areEqual(2, rows.size(), 'There should be 2 work item rows');
    Assert.areEqual(
      WorkItemStatusNames.Blocked,
      rows[0].Status,
      'The first work item row should be Blocked'
    );
    Assert.areEqual(
      WorkItemStatusNames.Blocked,
      rows[1].Status,
      'The second work item row should be Blocked'
    );
  }
}