force-app/main/default/objects/Phase__c/Phase__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Project Phase</description>
    <label>Project Phase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Phases</relationshipLabel>
    <relationshipName>Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phase__c/fields/Total_Effort__c.field-meta.xml
<CustomField>
    <fullName>Total_Effort__c</fullName>
    <inlineHelpText>Total effort estimate (hours)</inlineHelpText>
    <label>Total Effort</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Challenges__c.field-meta.xml
<CustomField>
    <fullName>Challenges__c</fullName>
    <label>Challenges</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hypercare__c.field-meta.xml
<CustomField>
    <fullName>Hypercare__c</fullName>
    <defaultValue>0.05</defaultValue>
    <label>Hypercare %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Hypercare_Est__c.field-meta.xml
<CustomField>
    <fullName>Hypercare_Est__c</fullName>
    <description>Estimated hours required for hypercare</description>
    <formula>Total_Feature_Est__c * Hypercare__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hypercare Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Introduction__c.field-meta.xml
<CustomField>
    <fullName>Introduction__c</fullName>
    <label>Introduction</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Management__c.field-meta.xml
<CustomField>
    <fullName>Project_Management__c</fullName>
    <defaultValue>0.25</defaultValue>
    <label>Project Management %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Management_Est__c.field-meta.xml
<CustomField>
    <fullName>Project_Management_Est__c</fullName>
    <description>Estimated hours required for project management</description>
    <formula>Total_Feature_Est__c * Project_Management__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Management Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Testing__c.field-meta.xml
<CustomField>
    <fullName>Testing__c</fullName>
    <defaultValue>0.15</defaultValue>
    <label>Testing %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Testing_Est__c.field-meta.xml
<CustomField>
    <fullName>Testing_Est__c</fullName>
    <description>Estimated hours required for testing</description>
    <formula>Total_Feature_Est__c * Testing__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Testing Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Effort__c.field-meta.xml
<CustomField>
    <fullName>Total_Effort__c</fullName>
    <inlineHelpText>Total effort estimate (hours, from work items)</inlineHelpText>
    <label>Total Effort (hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Est_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Est_Cost__c</fullName>
    <formula>Total_Estimate__c * Proposal_Hourly_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This value is the total of all work item estimates on the project - including any unapproved work items. Excluding Work Items marked as Optional</inlineHelpText>
    <label>Total Est Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Est_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_Est_Days__c</fullName>
    <formula>Total_Estimate__c / 8</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Est (Days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Total_Estimate__c</fullName>
    <formula>Total_Feature_Est__c + IF(Is_PreSales__c, Project_Management_Est__c + Discovery_Est__c + Design_Analysis_Est__c + Testing_Est__c + UAT_Est__c + Training_Documentation_Est__c + Hypercare_Est__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Total_Feature_Est__c.field-meta.xml
<CustomField>
    <fullName>Total_Feature_Est__c</fullName>
    <label>Total Feature Est</label>
    <summarizedField>Project_Feature__c.Total_Est__c</summarizedField>
    <summaryForeignKey>Project_Feature__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/UAT__c.field-meta.xml
<CustomField>
    <fullName>UAT__c</fullName>
    <defaultValue>0.15</defaultValue>
    <label>UAT %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/UAT_Est__c.field-meta.xml
<CustomField>
    <fullName>UAT_Est__c</fullName>
    <description>Estimated hours required for user acceptance testing</description>
    <formula>Total_Feature_Est__c * UAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field shows the Total UAT Time estimated for each Project Feature during the Project Design Phase.</inlineHelpText>
    <label>UAT Est</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Est_Cost__c.field-meta.xml
<CustomField>
    <fullName>Est_Cost__c</fullName>
    <formula>Total_Est__c *  Project__r.Proposal_Hourly_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Est. Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phase</label>
    <referenceTo>Phase__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Features</relationshipLabel>
    <relationshipName>Project_Features</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Total_Effort__c.field-meta.xml
<CustomField>
    <fullName>Total_Effort__c</fullName>
    <inlineHelpText>Total estimated effort (hours)</inlineHelpText>
    <label>Total Effort [DEPRECATED]</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/Project_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{000000}</displayFormat>
        <label>Project Team Member Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Team Members</relationshipLabel>
    <relationshipName>Project_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/Salesforce_License__c.object-meta.xml
<CustomObject>
    <label>Salesforce License</label>
    <nameField>
        <displayFormat>SFL-{0000}</displayFormat>
        <label>Salesforce License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_License__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that holds these Licenses.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salesforce Licenses</relationshipLabel>
    <relationshipName>Salesforce_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Project you have selected is not linked to the selected Account</errorMessage>
        <filterItems>
            <field>Project__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Salesforce Licenses</relationshipLabel>
    <relationshipName>Salesforce_Licenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Third_Party_Service__c/Third_Party_Service__c.object-meta.xml
<CustomObject>
    <label>Third Party Service</label>
    <nameField>
        <displayFormat>TPS-{00000}</displayFormat>
        <label>Third Party Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Service__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Third Party Services</relationshipLabel>
    <relationshipName>Third_Party_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Project__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>65000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PhaseProposalDataAccess.cls
public with sharing class PhaseProposalDataAccess {
  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ApexCRUDViolation')
  public Phase__c getPhases(Id phaseId) {
    return [
      SELECT
        Name,
        Description__c,
        Total_Effort__c,
        Stage__c,
        Project__r.Name,
        Project__r.Account__r.Name,
        Project__r.Introduction__c,
        Project__r.Challenges__c,
        Project__r.Payment_Terms__c,
        Project__r.Project_Management__c,
        Project__r.Project_Management_Est__c,
        Project__r.Testing__c,
        Project__r.Testing_Est__c,
        Project__r.UAT_Est__c,
        Project__r.UAT__c,
        Project__r.Hypercare_Est__c,
        Project__r.Hypercare__c,
        Project__r.Total_Estimate__c,
        Project__r.Total_Est_Days__c,
        Project__r.Total_Feature_Est__c,
        Project__r.Total_Est_Cost__c,
        Project__r.Proposal_Hourly_Rate__c,
        Project__r.Opportunity__c,
        Project__r.Hide_Table_of_Contents__c,
        Project__r.Hide_Requirements__c,
        Project__r.Hide_Services__c,
        Project__r.Hide_Our_Approach__c,
        Project__r.Hide_Project_Management_Delivery__c,
        Project__r.Hide_Assumptions__c,
        Project__r.Vendor__c,
        Project__r.CurrencyIsoCode
      FROM Phase__c
      WHERE Id = :phaseId
    ];
  }

  // public Project__c getProject(Id phaseId) {
  //     return [
  //         SELECT
  //             Name,
  //             Account__r.Name,
  //             Introduction__c,
  //             Challenges__c,
  //             Payment_Terms__c,
  //             Project_Management__c,
  //             Project_Management_Est__c,
  //             Testing__c,
  //             Testing_Est__c,
  //             UAT__c,
  //             Hypercare__c,
  //             Proposal_Hourly_Rate__c,
  //             Opportunity__c,
  //             Hide_Table_of_Contents__c,
  //             Hide_Requirements__c,
  //             Hide_Services__c,
  //             Hide_Our_Approach__c,
  //             Hide_Project_Management_Delivery__c,
  //             Hide_Assumptions__c,
  //             Vendor__c,
  //             CurrencyIsoCode
  //         FROM Project__c
  //         WHERE Id = :phaseId
  //     ];
  // }

  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ApexCRUDViolation')
  public List<ContentVersion> getFiles(Id phaseId) {
    final List<String> allowedFileTypes = new List<String>{
      'GIF',
      'PNG',
      'JPEG',
      'JPG'
    };
    Set<Id> ContentDocumentIds = new Set<Id>(); // NOPMD

    for (ContentDocumentLink link : [
      SELECT ContentDocumentId
      FROM ContentDocumentLink
      WHERE LinkedEntityId = :phaseId
    ]) {
      ContentDocumentIds.add(link.ContentDocumentId);
    }

    return [
      SELECT Id, ContentDocumentId, VersionData, Description, FileType, Title
      FROM ContentVersion
      WHERE
        ContentDocumentId IN :ContentDocumentIds
        AND FileType IN :allowedFileTypes
        AND IsLatest = TRUE
    ];
  }

  // TODO: SuppressWarning added as part of Org sync. Refactor and remove on next update.
  @SuppressWarnings('PMD.ApexCRUDViolation')
  public List<Project_Feature__c> getFeatures(Id phaseId) {
    return [
      SELECT
        Name,
        Description__c,
        Total_Est__c,
        Work_Item_Count__c,
        (
          SELECT
            Name,
            Subject__c,
            Description__c,
            Assumptions__c,
            Importance__c,
            Est_Time__c,
            Is_Optional__c
          FROM Work_Items__r
          WHERE Project_Phase__c = :phaseId
          ORDER BY Sort_Order__c, Subject__c
        )
      FROM Project_Feature__c
      WHERE
        Id IN (
          SELECT Feature__c
          FROM Work_Item__c
          WHERE Project_Phase__c = :phaseId
        )
      ORDER BY Sort_Order__c, Name
    ];
  }

  // public List<Salesforce_License__c> getLicesnses(Id phaseId) {
  //     return [SELECT License__c, Quantity__c FROM Salesforce_License__c WHERE Phase__c = :phaseId ORDER BY Sort_Order__c];
  // }

  // public List<Project_Team_Member__c> getProjectTeamMembers(Id phaseId) {
  //     return [SELECT Role__c, Name__c, Email__c, Phone__c FROM Project_Team_Member__c WHERE Phase__c = :phaseId ORDER BY Sort_Order__c];
  // }

  // public List<Third_Party_Service__c> getServices(Id phaseId) {
  //     return [SELECT Service__c, Description__c, Est_Cost__c, CurrencyIsoCode FROM Third_Party_Service__c WHERE Phase__c = :phaseId ORDER BY Sort_Order__c];
  // }
}