force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <description>Request for leave, or sickness declaration</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>CASE(
 WEEKDAY(Start_Date__c),
  1, (Start_Date__c) + CEILING(Days__c) - 1 + 
      FLOOR((Days__c-1)/5)*2,
  2, (Start_Date__c) + CEILING(Days__c) - 1 + 
      FLOOR((Days__c)/5)*2,
  3, (Start_Date__c) + CEILING(Days__c) - 1 + 
      FLOOR((Days__c+1)/5)*2,
  4, (Start_Date__c) + CEILING(Days__c) - 1 + 
      FLOOR((Days__c+2)/5)*2,
  5, (Start_Date__c) + CEILING(Days__c) - 1 + 
      FLOOR((Days__c+3)/5)*2,
  6, (Start_Date__c) + CEILING(Days__c) - 1 + 
      CEILING((Days__c)/5)*2,
  7, (Start_Date__c) - IF(Days__c - 1&gt;0,1,0) + CEILING(Days__c) - 1 + 
      CEILING((Days__c)/5)*2,
 null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Summary__c.field-meta.xml
<CustomField>
    <fullName>Leave_Summary__c</fullName>
    <label>Leave Summary</label>
    <referenceTo>Leave_Summary__c</referenceTo>
    <relationshipLabel>Leave Requests</relationshipLabel>
    <relationshipName>Leave_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Start date of leave/absence</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Summary__c/Leave_Summary__c.object-meta.xml
<CustomObject>
    <label>Leave Summary</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Leave Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Summary__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),12,31)</defaultValue>
    <inlineHelpText>Employee end date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Summary__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,1)</defaultValue>
    <inlineHelpText>Employee start date for period</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects_R3</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0ea854</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>55c022</fullName>
                <label>Yellow-Green</label>
            </value>
            <value>
                <fullName>faf300</fullName>
                <label>Yellow</label>
            </value>
            <value>
                <fullName>faa001</fullName>
                <label>Yellow-Orange</label>
            </value>
            <value>
                <fullName>fa7900</fullName>
                <label>Orange</label>
            </value>
            <value>
                <fullName>fa2430</fullName>
                <label>Red-Orange</label>
            </value>
            <value>
                <fullName>fa2207</fullName>
                <label>Red</label>
            </value>
            <value>
                <fullName>b10f91</fullName>
                <label>Red-Purple</label>
            </value>
            <value>
                <fullName>5f2596</fullName>
                <label>Purple</label>
            </value>
            <value>
                <fullName>1d3c9e</fullName>
                <label>Blue-Purple</label>
            </value>
            <value>
                <fullName>2365b7</fullName>
                <label>Blue</label>
            </value>
            <value>
                <fullName>22afae</fullName>
                <label>Blue-Green</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/Project_Resource_Assignment__c.object-meta.xml
<CustomObject>
    <label>Project Resource Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000000}</displayFormat>
        <label>Project Resource Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resource Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Hours_Per_Day__c</fullName>
    <label>Hours Per Day</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Resource Assignments</relationshipLabel>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Project_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Project_Team_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Team Member</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Project Team Member does not belong to Project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Team_Member__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Team_Member__c</referenceTo>
    <relationshipLabel>Project Resource Assignments</relationshipLabel>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Is_Resource_Assignable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/Project_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{000000}</displayFormat>
        <label>Project Team Member Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Team Members</relationshipLabel>
    <relationshipName>Project_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Team_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ResourceManagementChartController.cls
public with sharing class ResourceManagementChartController {
    @TestVisible
    private static Set<String> ACTIVE_STATUSES = new Set<String>{
        ProjectStatusNames.Planning,
        ProjectStatusNames.KickOff,
        ProjectStatusNames.InProgress,
        ProjectStatusNames.Uat,
        ProjectStatusNames.HyperCare,
        ProjectStatusNames.Support
    };

    @TestVisible
    private static Map<Id, List<Date>> leaveDates = new Map<Id, List<Date>>();

    @AuraEnabled(cacheable=false)
    public static List<Project> getProjects(Date startDate, Date endDate, List<String> filteredStatusList, List<Id> filteredUserList) {
        try {
            if (filteredStatusList.size() == 0) {
                filteredStatusList.addAll(ACTIVE_STATUSES);
            }

            if (endDate == null) {
                endDate = startDate.addYears(2);
            }

            if (filteredUserList.size() == 0) {
                List<User> userList = [SELECT Id FROM User WHERE Is_Resource_Assignable__c = TRUE];
                for (User user : userList) {
                    filteredUserList.add(user.Id);
                }
            }

            Map<Id, List<Project_Resource_Assignment__c>> resourceAssignmentsMappedByProject = getResourceAssignmentsMappedByProject(startDate, endDate, filteredStatusList, filteredUserList);

            // Project 1 - Start: 01/01/2022 End: 31/05/2022
            // Project 2 - Start: 01/02/2022 End: 31/05/2022

            // Gantt - Start Date: 01/02/2022
            // Gantt - End Date: 10/06/2022

            System.debug(resourceAssignmentsMappedByProject);

            Set<Id> projectIds = resourceAssignmentsMappedByProject.keySet();

            System.debug(projectIds);

            String queryString = 'SELECT Id, Account__r.Name, Name, Start_Date__c, End_Date__c, Colour__c, Status__c FROM Project__c WHERE Id IN :projectIds ';
            if (filteredUserList.size() > 1) {
                queryString +=
                    'OR (Status__c IN :filteredStatusList ' +
                    'AND ((Start_Date__c >= :startDate ' +
                    'AND Start_Date__c <= :endDate) ' +
                    'OR (End_Date__c >= :startDate ' +
                    'AND End_Date__c <= :endDate))) ';
            }

            queryString += 'ORDER BY Account__r.Name, Name';

            List<Project__c> activeProjectsList = Database.query(queryString);

            System.debug(activeProjectsList);

            List<Project> projects = new List<Project>();

            for (Project__c activeProject : activeProjectsList) {
                Project project = new Project(
                    activeProject.Id,
                    activeProject.Account__c,
                    activeProject.Account__r.Name,
                    activeProject.Name,
                    activeProject.Start_Date__c,
                    activeProject.End_Date__c,
                    activeProject.Colour__c,
                    activeProject.Status__c
                );

                if (resourceAssignmentsMappedByProject.containsKey(activeProject.Id)) {
                    for (Project_Resource_Assignment__c resourceAssignment : resourceAssignmentsMappedByProject.get(activeProject.Id)) {
                        project.appendResourceAssignment(resourceAssignment);
                    }
                }

                projects.add(project);
            }

            return projects;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @TestVisible
    private static Map<Id, List<Project_Resource_Assignment__c>> getResourceAssignmentsMappedByProject(Date startDate, Date endDate, List<String> filteredStatusList, List<Id> filteredUserList) {
        List<Project_Resource_Assignment__c> resourceAssignmentList = [
            SELECT Id, Project__c, Start_Date__c, End_Date__c, Hours_Per_Day__c, User__c, User__r.Name, Project__r.Account__r.Name, Project__r.Name, Project__r.Start_Date__c, Project__r.End_Date__c
            FROM Project_Resource_Assignment__c
            WHERE
                Project__r.Status__c IN :filteredStatusList
                AND User__c IN :filteredUserList
                AND ((Start_Date__c >= :startDate
                AND Start_Date__c <= :endDate)
                OR (End_Date__c >= :startDate
                AND End_Date__c <= :endDate))
            ORDER BY Project__r.Account__r.Name, Project__r.Name, Start_Date__c, End_Date__c DESC, User__r.Name
        ];

        Map<Id, List<Project_Resource_Assignment__c>> resourceAssignmentsMappedByProject = new Map<Id, List<Project_Resource_Assignment__c>>();

        for (Project_Resource_Assignment__c resourceAssignment : resourceAssignmentList) {
            if (resourceAssignmentsMappedByProject.containsKey(resourceAssignment.Project__c)) {
                resourceAssignmentsMappedByProject.get(resourceAssignment.Project__c).add(resourceAssignment);
            } else {
                resourceAssignmentsMappedByProject.put(resourceAssignment.Project__c, new List<Project_Resource_Assignment__c>{ resourceAssignment });
            }
        }

        return resourceAssignmentsMappedByProject;
    }

    @AuraEnabled(cacheable=true)
    public static List<User> getUsers() {
        try {
            List<User> userList = [SELECT Id, Name, Project_Team_Role__c FROM User WHERE IsActive = TRUE AND Is_Resource_Assignable__c = TRUE ORDER BY Name];

            if (userList.size() == 0) {
                throw new CustomException('No users found.');
            }

            return userList;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=true)
    public static Map<Id, List<LeaveDate>> getLeaveDates() {
        try {
            List<Leave_Request__c> leaveRequestList = [
                SELECT Leave_Summary__r.OwnerId, Start_Date__c, End_Date__c, Status__c
                FROM Leave_Request__c
                WHERE Status__c IN (:LeaveRequestStatusNames.SUBMITTED, :LeaveRequestStatusNames.APPROVED)
            ];

            Map<Id, List<LeaveDate>> leaveDates = new Map<Id, List<LeaveDate>>();

            for (Leave_Request__c leaveRequest : leaveRequestList) {
                Id userId = leaveRequest.Leave_Summary__r.OwnerId;
                Date startDate = leaveRequest.Start_Date__c;
                Date endDate = leaveRequest.End_Date__c;
                List<LeaveDate> dates;

                if (leaveDates.containsKey(userId)) {
                    dates = leaveDates.get(userId);
                } else {
                    dates = new List<LeaveDate>();
                }

                while (startDate <= endDate) {
                    dates.add(new LeaveDate(startDate, leaveRequest.Status__c));
                    startDate = startDate.addDays(1);
                }

                leaveDates.put(userId, dates);
            }

            return leaveDates;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static User getUserPreferences() {
        try {
            return [SELECT Resource_Management_Columns__c, Resource_Management_Expanded_IDs__c, Resource_Management_Scale__c FROM User WHERE Id = :UserInfo.getUserId()];
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static Project getProjectDetails(Id recordId) {
        try {
            Project__c project = [SELECT Id, Account__c, Account__r.Name, Name, Start_Date__c, End_Date__c, Colour__c, Status__c FROM Project__c WHERE Id = :recordId];

            return new Project(project.Id, project.Account__c, project.Account__r.Name, project.Name, project.Start_Date__c, project.End_Date__c, project.Colour__c, project.Status__c);
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static ResourceAssignment getAssignmentDetails(Id recordId) {
        try {
            String entityType = GanttChartController.getEntityType(recordId);

            switch on entityType {
                when 'Project__c' {
                    Project__c project = [SELECT Id, Name, Start_Date__c, End_Date__c FROM Project__c WHERE Id = :recordId];

                    return new ResourceAssignment(null, project.Id, project.Name, null, project.Start_Date__c, project.End_Date__c, null);
                }
                when 'Project_Resource_Assignment__c' {
                    Project_Resource_Assignment__c assignment = [
                        SELECT Id, User__c, Start_Date__c, End_Date__c, Hours_Per_Day__c, Project__c, Project__r.Name
                        FROM Project_Resource_Assignment__c
                        WHERE Id = :recordId
                    ];

                    return new ResourceAssignment(
                        assignment.Id,
                        assignment.Project__c,
                        assignment.Project__r.Name,
                        assignment.User__c,
                        assignment.Start_Date__c,
                        assignment.End_Date__c,
                        assignment.Hours_Per_Day__c
                    );
                }
                when else {
                    throw new CustomException('Unknown entity type.');
                }
            }
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static void updateProject(Id projectId, String name, Date startDate, Date endDate, String status, String colour) {
        try {
            Project__c project = new Project__c(Id = projectId);
            project.Name = name;
            project.Start_Date__c = startDate;
            project.End_Date__c = endDate;
            project.Status__c = status;
            project.Colour__c = colour;
            update project;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static void saveAssignment(Id projectResourceAssignmentId, Id projectId, Id userId, Date startDate, Date endDate, Decimal hoursPerDay, String projectTeamRole) {
        try {
            Project_Resource_Assignment__c assignment = new Project_Resource_Assignment__c(Id = projectResourceAssignmentId);
            assignment.Project__c = projectId;
            assignment.User__c = userId;
            assignment.Start_Date__c = startDate;
            assignment.End_Date__c = endDate;
            assignment.Hours_Per_Day__c = hoursPerDay;
            upsert assignment;

            if (!String.isEmpty(projectTeamRole) && !isUserInProjectTeam(userId, projectId)) {
                Project_Team_Member__c member = new Project_Team_Member__c();
                member.Project__c = projectId;
                member.User__c = userId;
                member.Role__c = projectTeamRole;
                insert member;
            }
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static void updateAssignmentDates(Id id, Date startDate, Date endDate) {
        try {
            Project_Resource_Assignment__c assignment = new Project_Resource_Assignment__c(Id = id);
            assignment.Start_Date__c = startDate;
            assignment.End_Date__c = endDate;
            update assignment;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static void updateUserColumns(String columns) {
        try {
            User user = new User(Id = UserInfo.getUserId());
            user.Resource_Management_Columns__c = columns;
            update user;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static void updateUserExpandedIds(String expandedIds) {
        try {
            User user = new User(Id = UserInfo.getUserId());
            user.Resource_Management_Expanded_IDs__c = expandedIds;
            update user;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @AuraEnabled(cacheable=false)
    public static void updateUserScale(String scale) {
        try {
            User user = new User(Id = UserInfo.getUserId());
            user.Resource_Management_Scale__c = scale;
            update user;
        } catch (Exception e) {
            throw AuraHandledExceptionFactory.create(e);
        }
    }

    @TestVisible
    private static Boolean isUserInProjectTeam(Id userId, Id projectId) {
        return [SELECT Id FROM Project_Team_Member__c WHERE User__c = :userId AND Project__c = :projectId].size() > 0;
    }

    public class CustomException extends Exception {
    }

    public class LeaveDate {
        @AuraEnabled
        public Date LeaveDate { get; private set; }

        @AuraEnabled
        public Boolean IsApproved { get; private set; }

        public LeaveDate(Date leaveDate, String status) {
            this.LeaveDate = LeaveDate;
            this.IsApproved = (status == LeaveRequestStatusNames.APPROVED);
        }
    }

    public class Project {
        @AuraEnabled
        public String Id { get; private set; }

        @AuraEnabled
        public String AccountId { get; private set; }

        @AuraEnabled
        public String AccountName { get; private set; }

        @AuraEnabled
        public String Name { get; private set; }

        @AuraEnabled
        public Date StartDate { get; private set; }

        @AuraEnabled
        public Date EndDate { get; private set; }

        @AuraEnabled
        public String Colour { get; private set; }

        @AuraEnabled
        public String Status { get; private set; }

        @AuraEnabled
        public List<Project_Resource_Assignment__c> ResourceAssignments { get; private set; }

        public Project(Id id, Id accountId, String accountName, String name, Date startDate, Date endDate, String colour, String status) {
            this.Id = id;
            this.AccountId = accountId;
            this.AccountName = accountName;
            this.Name = name;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.Colour = colour;
            this.Status = status;
            this.ResourceAssignments = new List<Project_Resource_Assignment__c>();
        }

        public void appendResourceAssignment(Project_Resource_Assignment__c resourceAssignment) {
            this.ResourceAssignments.add(resourceAssignment);
        }
    }

    public class ResourceAssignment {
        @AuraEnabled
        public Id Id { get; private set; }

        @AuraEnabled
        public Id ProjectId { get; private set; }

        @AuraEnabled
        public String ProjectName { get; private set; }

        @AuraEnabled
        public Id UserId { get; private set; }

        @AuraEnabled
        public Date StartDate { get; private set; }

        @AuraEnabled
        public Date EndDate { get; private set; }

        @AuraEnabled
        public Decimal HoursPerDay { get; private set; }

        public ResourceAssignment(Id id, Id projectId, String projectName, Id userId, Date startDate, Date endDate, Decimal hoursPerDay) {
            this.Id = id;
            this.ProjectId = projectId;
            this.ProjectName = projectName;
            this.UserId = userId;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.HoursPerDay = hoursPerDay;
        }
    }
}