force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <description>Request for leave, or sickness declaration</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <inlineHelpText>Number of days requested (use decimals for half days, e.g. 0.5)</inlineHelpText>
    <label>Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Summary__c.field-meta.xml
<CustomField>
    <fullName>Leave_Summary__c</fullName>
    <label>Leave Summary</label>
    <referenceTo>Leave_Summary__c</referenceTo>
    <relationshipLabel>Leave Requests</relationshipLabel>
    <relationshipName>Leave_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual Leave</fullName>
                <default>true</default>
                <label>Annual Leave</label>
            </value>
            <value>
                <fullName>Sickness Declaration</fullName>
            </value>
            <value>
                <fullName>Compassionate Leave</fullName>
            </value>
            <value>
                <fullName>Parental Leave</fullName>
            </value>
            <value>
                <fullName>Paternity Leave</fullName>
            </value>
            <value>
                <fullName>Maternity Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Time in lieu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Start date of leave/absence</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Summary__c/Leave_Summary__c.object-meta.xml
<CustomObject>
    <label>Leave Summary</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Leave Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Summary__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,1)</defaultValue>
    <inlineHelpText>Employee start date for period</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Projects</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
                <default>true</default>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Kick off</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Hyper care</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/Project_Resource_Assignment__c.object-meta.xml
<CustomObject>
    <label>Project Resource Assignment</label>
    <nameField>
        <displayFormat>PRA-{00000000}</displayFormat>
        <label>Project Resource Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Resource Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Friday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Friday__c</fullName>
    <label>Hours Friday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Monday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Monday__c</fullName>
    <label>Hours Monday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Thursday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Thursday__c</fullName>
    <label>Hours Thursday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Tuesday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Tuesday__c</fullName>
    <label>Hours Tuesday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Hours_Wednesday__c.field-meta.xml
<CustomField>
    <fullName>Hours_Wednesday__c</fullName>
    <label>Hours Wednesday</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Resource Assignments</relationshipLabel>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Resource_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Is_Resource_Assignable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resource_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RevenueManagementControllerTest.cls
@isTest
public class RevenueManagementControllerTest {
  @isTest
  public static void testGetResourceAssignments() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    user.Standard_Rate__c = 150;
    update user;

    Id accountId = AccountTestDataFactory.create('Test Account');

    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    List<Project_Resource_Assignment__c> resourceAssignmentList = new List<Project_Resource_Assignment__c>{
      ProjectResourceAssignmentTestDataFactory.create(
        user.Id,
        projectId,
        150,
        Date.today().toStartofWeek(),
        8,
        6,
        4,
        0,
        0
      ),
      ProjectResourceAssignmentTestDataFactory.create(
        user.Id,
        projectId,
        125,
        Date.today().addDays(7).toStartofWeek(),
        4,
        4,
        4,
        4,
        4
      )
    };
    insert resourceAssignmentList;

    // Act
    Test.startTest();
    List<User> resourceAssignments = RevenueManagementController.getResourceAssignments(
      Date.today().addDays(-7),
      null,
      new List<String>(),
      new List<String>()
    );
    Test.stopTest();

    // Assert
    for (User resourceAssignment : resourceAssignments) {
      if (resourceAssignment.Id == user.Id) {
        System.assertEquals(
          2,
          resourceAssignment.Project_Resource_Assignments__r.size(),
          'User should have 2 resource assignments'
        );
        System.assertEquals(
          resourceAssignmentList[1].Id,
          resourceAssignment.Project_Resource_Assignments__r[0].Id,
          'First resource assignment should be the second one created'
        );
        System.assertEquals(
          resourceAssignmentList[0].Id,
          resourceAssignment.Project_Resource_Assignments__r[1].Id,
          'Second resource assignment should be the first one created'
        );
      } else {
        System.assertEquals(
          0,
          resourceAssignment.Project_Resource_Assignments__r.size(),
          'User should have no resource assignments'
        );
      }
    }
  }

  @isTest
  public static void testGetLeaveDates() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    user.Standard_Rate__c = 150;
    update user;

    Leave_Summary__c summary = new Leave_Summary__c(OwnerId = user.Id);
    insert summary;

    Leave_Request__c request = new Leave_Request__c(
      Leave_Summary__c = summary.Id,
      Leave_Type__c = 'Annual Leave',
      Start_Date__c = Date.newInstance(2024, 1, 1),
      Days__c = 2,
      Status__c = 'Approved'
    );
    insert request;

    // Act
    Map<Id, List<RevenueManagementController.LeaveDate>> response = RevenueManagementController.getLeaveDates(
      Date.newInstance(2024, 1, 1),
      null,
      new List<String>()
    );

    // Assert
    System.assert(
      response.containsKey(user.Id),
      'Response should contain user Id'
    );
    List<RevenueManagementController.LeaveDate> leaveDates = response.get(
      user.Id
    );
    System.assertEquals(2, leaveDates.size(), 'User should have 2 leave dates');
    System.assertEquals(
      Date.newInstance(2024, 1, 1),
      leaveDates[0].LeaveDate,
      'First leave date should be 2024-01-01'
    );
    System.assert(
      leaveDates[0].IsApproved,
      'First leave date should be approved'
    );
    System.assert(
      !leaveDates[0].IsSickness,
      'First leave date should not be sickness'
    );
  }

  @isTest
  public static void testGetUserPreferences() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'LastName',
      'System Administrator'
    );
    user.Resource_Management_Columns__c = '1;2;3';
    user.Resource_Management_Scale__c = 'week';
    update user;

    // Act
    User preferences;

    Test.startTest();
    System.runAs(user) {
      preferences = RevenueManagementController.getUserPreferences();
    }
    Test.stopTest();

    // Assert
    System.assertEquals(
      '1;2;3',
      preferences.Resource_Management_Columns__c,
      'Columns should be set'
    );
    System.assertEquals(
      'week',
      preferences.Resource_Management_Scale__c,
      'Scale should be set'
    );
  }

  @isTest
  public static void testGetResourceAssignmentDetails() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    user.Standard_Rate__c = 150;
    update user;

    Id accountId = AccountTestDataFactory.create('Test Account');

    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    Project_Resource_Assignment__c resourceAssignment = ProjectResourceAssignmentTestDataFactory.create(
      user.Id,
      projectId,
      150,
      Date.newInstance(2022, 8, 1),
      8,
      6,
      4,
      0,
      0
    );
    insert resourceAssignment;

    // Act
    Test.startTest();
    Project_Resource_Assignment__c response = RevenueManagementController.getResourceAssignmentDetails(
      resourceAssignment.Id
    );
    Test.stopTest();

    // Assert
    System.assertEquals(resourceAssignment.Id, response.Id, 'IDs should match');
    System.assertEquals(
      resourceAssignment.Start_Date__c,
      response.Start_Date__c,
      'Start date should match'
    );
    System.assertEquals(user.Id, response.User__c, 'User ID should match');
    System.assertEquals(
      projectId,
      response.Project__c,
      'Project ID should match'
    );
    System.assertEquals(150, response.Rate__c, 'Rate should match');
    System.assertEquals(
      8,
      response.Hours_Monday__c,
      'Monday hours should match'
    );
    System.assertEquals(
      6,
      response.Hours_Tuesday__c,
      'Tuesday hours should match'
    );
    System.assertEquals(
      4,
      response.Hours_Wednesday__c,
      'Wednesday hours should match'
    );
    System.assertEquals(
      0,
      response.Hours_Thursday__c,
      'Thursday hours should match'
    );
    System.assertEquals(
      0,
      response.Hours_Friday__c,
      'Friday hours should match'
    );
  }

  @isTest
  public static void testGetResourceAssignmentDetailsException() {
    try {
      RevenueManagementController.getResourceAssignmentDetails(
        '000000000000000000'
      );
    } catch (AuraHandledException e) {
      System.assert(true, 'Exception should be thrown');
      return;
    }

    System.assert(false, 'Exception should be thrown');
  }

  @isTest
  public static void testFindResourceAssignment() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    user.Standard_Rate__c = 150;
    update user;

    Id accountId = AccountTestDataFactory.create('Test Account');

    Id project1Id = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );
    Id project2Id = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    List<Project_Resource_Assignment__c> resourceAssignmentList = new List<Project_Resource_Assignment__c>{
      ProjectResourceAssignmentTestDataFactory.create(
        user.Id,
        project1Id,
        150,
        Date.newInstance(2022, 8, 1),
        4,
        4,
        4,
        4,
        4
      ),
      ProjectResourceAssignmentTestDataFactory.create(
        user.Id,
        project2Id,
        150,
        Date.newInstance(2022, 8, 8),
        8,
        8,
        8,
        8,
        8
      )
    };
    insert resourceAssignmentList;

    // Act
    Test.startTest();
    Project_Resource_Assignment__c response = RevenueManagementController.findResourceAssignment(
      Date.newInstance(2022, 8, 8),
      user.Id,
      project2Id
    );
    Test.stopTest();

    // Assert
    System.assertEquals(
      resourceAssignmentList[1].Id,
      response.Id,
      'IDs should match'
    );
    System.assertEquals(
      Date.newInstance(2022, 8, 8),
      response.Start_Date__c,
      'Start date should match'
    );
    System.assertEquals(user.Id, response.User__c, 'User ID should match');
    System.assertEquals(
      project2Id,
      response.Project__c,
      'Project ID should match'
    );
    System.assertEquals(150, response.Rate__c, 'Rate should match');
    System.assertEquals(
      8,
      response.Hours_Monday__c,
      'Monday hours should match'
    );
    System.assertEquals(
      8,
      response.Hours_Tuesday__c,
      'Tuesday hours should match'
    );
    System.assertEquals(
      8,
      response.Hours_Wednesday__c,
      'Wednesday hours should match'
    );
    System.assertEquals(
      8,
      response.Hours_Thursday__c,
      'Thursday hours should match'
    );
    System.assertEquals(
      8,
      response.Hours_Friday__c,
      'Friday hours should match'
    );
  }

  @isTest
  public static void testFindResourceAssignmentNotFound() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    update user;

    Id accountId = AccountTestDataFactory.create('Test Account');

    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    // Act
    Test.startTest();
    Project_Resource_Assignment__c response = RevenueManagementController.findResourceAssignment(
      Date.newInstance(2022, 8, 8),
      user.Id,
      projectId
    );
    Test.stopTest();

    // Assert
    System.assertEquals(null, response, 'Response should be null');
  }

  @isTest
  public static void testSaveResourceAssignment() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    user.Standard_Rate__c = 150;
    update user;

    Id accountId = AccountTestDataFactory.create('Test Account');

    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    final Date startDate = Date.newInstance(2022, 8, 1);
    final Decimal rate = 150;
    final String status = 'Confirmed';
    final Decimal hoursMon = 1;
    final Decimal hoursTue = 2;
    final Decimal hoursWed = 3;
    final Decimal hoursThu = 4;
    final Decimal hoursFri = 5;

    // Act
    Test.startTest();
    RevenueManagementController.saveResourceAssignment(
      null,
      startDate,
      user.Id,
      projectId,
      rate,
      status,
      hoursMon,
      hoursTue,
      hoursWed,
      hoursThu,
      hoursFri
    );
    Test.stopTest();

    // Assert
    System.assertEquals(
      1,
      [
        SELECT COUNT()
        FROM Project_Resource_Assignment__c
        WHERE
          Start_Date__c = :startDate
          AND User__c = :user.Id
          AND Project__c = :projectId
      ],
      'Resource assignment should be created'
    );
  }

  @isTest
  public static void testSaveResourceAssignmentUpdateExisting() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    user.Standard_Rate__c = 150;
    update user;

    Id accountId = AccountTestDataFactory.create('Test Account');

    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    Project_Resource_Assignment__c resourceAssignment = ProjectResourceAssignmentTestDataFactory.create(
      user.Id,
      projectId,
      150,
      Date.newInstance(2022, 8, 1),
      1,
      2,
      3,
      4,
      5
    );
    insert resourceAssignment;

    // Act
    Test.startTest();
    RevenueManagementController.saveResourceAssignment(
      resourceAssignment.Id,
      Date.newInstance(2022, 8, 1),
      user.Id,
      projectId,
      150,
      'Confirmed',
      8,
      7,
      6,
      5,
      4
    );
    Test.stopTest();

    // Assert
    Project_Resource_Assignment__c response = [
      SELECT
        Hours_Monday__c,
        Hours_Tuesday__c,
        Hours_Wednesday__c,
        Hours_Thursday__c,
        Hours_Friday__c
      FROM Project_Resource_Assignment__c
      WHERE Id = :resourceAssignment.Id
    ];
    System.assertEquals(
      8,
      response.Hours_Monday__c,
      'Monday hours should match'
    );
    System.assertEquals(
      7,
      response.Hours_Tuesday__c,
      'Tuesday hours should match'
    );
    System.assertEquals(
      6,
      response.Hours_Wednesday__c,
      'Wednesday hours should match'
    );
    System.assertEquals(
      5,
      response.Hours_Thursday__c,
      'Thursday hours should match'
    );
    System.assertEquals(
      4,
      response.Hours_Friday__c,
      'Friday hours should match'
    );
  }

  @isTest
  public static void testSaveResourceAssignmentException() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    update user;

    Id accountId = AccountTestDataFactory.create('Test Account');

    Id projectId = ProjectTestDataFactory.create(
      accountId,
      'Test Project',
      ProjectStatusNames.InProgress
    );

    Project_Resource_Assignment__c resourceAssignment = ProjectResourceAssignmentTestDataFactory.create(
      user.Id,
      projectId,
      150,
      Date.newInstance(2022, 8, 1),
      1,
      2,
      3,
      4,
      5
    );
    insert resourceAssignment;

    // Act
    Test.startTest();

    try {
      RevenueManagementController.saveResourceAssignment(
        null,
        Date.newInstance(2022, 8, 1),
        user.Id,
        projectId,
        150,
        'Confirmed',
        8,
        7,
        6,
        5,
        4
      );
    } catch (AuraHandledException e) {
      // Assert
      System.assertEquals(
        'A resource assignment already exists for the selected week.',
        e.getMessage(),
        'Exception message should match'
      );
      return;
    }

    Test.stopTest();

    // If we get here, the test failed
    System.assert(false, 'Exception should be thrown');
  }

  @isTest
  public static void testUpdateUserColumns() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    user.Resource_Management_Columns__c = '1;2;3';
    update user;

    // Act
    Test.startTest();
    System.runAs(user) {
      RevenueManagementController.updateUserColumns('4;5;6');
    }
    Test.stopTest();

    // Assert
    System.assertEquals(
      '4;5;6',
      [SELECT Resource_Management_Columns__c FROM User WHERE Id = :user.Id]
      .Resource_Management_Columns__c,
      'Columns should be updated'
    );
  }

  @isTest
  public static void testUpdateUserScale() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.pdd.test',
      'FirstName',
      'LastName'
    );
    user.Resource_Management_Scale__c = 'week';
    update user;

    // Act
    Test.startTest();
    System.runAs(user) {
      RevenueManagementController.updateUserScale('month');
    }
    Test.stopTest();

    // Assert
    System.assertEquals(
      'month',
      [SELECT Resource_Management_Scale__c FROM User WHERE Id = :user.Id]
      .Resource_Management_Scale__c,
      'Scale should be updated'
    );
  }
}