force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/Project_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{000000}</displayFormat>
        <label>Project Team Member Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF(NOT(ISBLANK(User__c)), User__r.FirstName + &apos; &apos; + User__r.LastName,
IF(NOT(ISBLANK(Contact__c)), Contact__r.FirstName + &apos; &apos; + Contact__r.LastName,
&apos;Not set&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Team_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/Salesforce_License__c.object-meta.xml
<CustomObject>
    <label>Salesforce License</label>
    <nameField>
        <displayFormat>SFL-{0000}</displayFormat>
        <label>Salesforce License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_License__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <label>License</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Studio</fullName>
            </value>
            <value>
                <fullName>Agentforce</fullName>
            </value>
            <value>
                <fullName>Agentforce - Customer Service</fullName>
            </value>
            <value>
                <fullName>Agentforce - Marketing Campaigns</fullName>
            </value>
            <value>
                <fullName>Agentforce - Personal Shopper</fullName>
            </value>
            <value>
                <fullName>Agentforce - Sales Coach</fullName>
            </value>
            <value>
                <fullName>Agentforce - SDR</fullName>
            </value>
            <value>
                <fullName>API Access</fullName>
            </value>
            <value>
                <fullName>Channel Account Login</fullName>
            </value>
            <value>
                <fullName>Channel Account Member</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Login License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Member License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Plus Login License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Plus Member License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2C</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud D2C</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>CPQ &amp; Billing</fullName>
            </value>
            <value>
                <fullName>CPQ for Customer Communities Login</fullName>
            </value>
            <value>
                <fullName>CPQ for Customer Communities Member</fullName>
            </value>
            <value>
                <fullName>CPQ for Partner Communities Login</fullName>
            </value>
            <value>
                <fullName>CPQ for Partner Communities Member</fullName>
            </value>
            <value>
                <fullName>CPQ Plus</fullName>
            </value>
            <value>
                <fullName>CPQ Plus &amp; Billing</fullName>
            </value>
            <value>
                <fullName>CRM Analytics Growth</fullName>
            </value>
            <value>
                <fullName>CRM Analytics Plus</fullName>
            </value>
            <value>
                <fullName>Customer Community Login</fullName>
            </value>
            <value>
                <fullName>Customer Community Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/fields/Salesforce_License__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_License__c</fullName>
    <formula>HYPERLINK(Id, TEXT( License__c ) , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesforce License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DragAndDropSorterTransformerTest.cls
@isTest
public class DragAndDropSorterTransformerTest {
  @isTest
  public static void testProjectFeature() {
    // Arrange
    Id accountId = AccountTestDataFactory.create();
    Id projectId = ProjectTestDataFactory.create(accountId);
    Id featureId = ProjectFeatureTestDataFactory.create(projectId);

    List<SObject> featureList = new List<SObject>(
      Database.query(
        'SELECT Id, Name FROM Project_Feature__c WHERE Id = :featureId'
      )
    );

    // Act
    DragAndDropSorterTransformer transformer = new DragAndDropSorterTransformer(
      featureList[0]
    );

    // Assert
    System.assertEquals(
      featureId,
      transformer.getId(),
      'Feature ID should be set'
    );
    System.assertEquals(
      featureList[0].get('Name'),
      transformer.getName(),
      'Feature name should be set'
    );
  }

  @isTest
  public static void testProjectTeamMember() {
    // Arrange
    User user = UserTestDataFactory.create(
      'test@r3.digital.test',
      'Test',
      'Name'
    );
    Id accountId = AccountTestDataFactory.create();
    Id projectId = ProjectTestDataFactory.create(accountId);
    Id memberId = ProjectTeamMemberTestDataFactory.create(projectId, user.Id);

    List<SObject> teamMemberList = new List<SObject>(
      Database.query(
        'SELECT Id, Name__c, Role__c FROM Project_Team_Member__c WHERE Id = :memberId'
      )
    );

    // Act
    DragAndDropSorterTransformer transformer = new DragAndDropSorterTransformer(
      teamMemberList[0]
    );

    // Assert
    System.assertEquals(
      memberId,
      transformer.getId(),
      'Team member ID should be set'
    );
    System.assertEquals(
      teamMemberList[0].get('Name__c') +
        ' - ' +
        teamMemberList[0].get('Role__c'),
      transformer.getName(),
      'Team member name and role should be concatenated'
    );
  }

  @isTest
  public static void testSalesforceLicense() {
    // Arrange
    Id accountId = AccountTestDataFactory.create();
    Id projectId = ProjectTestDataFactory.create(accountId);
    Id licenseId = SalesforceLicenseTestDataFactory.create(
      projectId,
      accountId
    );

    List<SObject> licenseList = new List<SObject>(
      Database.query(
        'SELECT Id, License__c FROM Salesforce_License__c WHERE Id = :licenseId'
      )
    );

    // Act
    DragAndDropSorterTransformer transformer = new DragAndDropSorterTransformer(
      licenseList[0]
    );

    // Assert
    System.assertEquals(
      licenseId,
      transformer.getId(),
      'License ID should be set'
    );
    System.assertEquals(
      licenseList[0].get('License__c'),
      transformer.getName(),
      'License name should be set'
    );
  }

  @isTest
  public static void testWorkItem() {
    // Arrange
    Id accountId = AccountTestDataFactory.create();
    Id projectId = ProjectTestDataFactory.create(accountId);
    Id featureId = ProjectFeatureTestDataFactory.create(projectId);
    Id workItemId = WorkItemTestDataFactory.create(projectId, featureId);

    List<SObject> workItemList = new List<SObject>(
      Database.query(
        'SELECT Id, Name, Subject__c FROM Work_Item__c WHERE Id = :workItemId'
      )
    );

    // Act
    DragAndDropSorterTransformer transformer = new DragAndDropSorterTransformer(
      workItemList[0]
    );

    // Assert
    System.assertEquals(
      workItemId,
      transformer.getId(),
      'Work Item ID should be set'
    );
    System.assertEquals(
      workItemList[0].get('Name') + ' - ' + workItemList[0].get('Subject__c'),
      transformer.getName(),
      'Work Item name and subject should be concatenated'
    );
  }
}