force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project_Feature__c/fields/Est_Cost__c.field-meta.xml
<CustomField>
    <fullName>Est_Cost__c</fullName>
    <formula>Total_Est__c *  Project__r.Proposal_Hourly_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Est. Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/Project_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PTM-{000000}</displayFormat>
        <label>Project Team Member Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Team_Member__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>IF(NOT(ISBLANK(User__c)), User__r.Email,
IF(NOT(ISBLANK(Contact__c)), Contact__r.Email,
&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF(NOT(ISBLANK(User__c)), User__r.FirstName + &apos; &apos; + User__r.LastName,
IF(NOT(ISBLANK(Contact__c)), Contact__r.FirstName + &apos; &apos; + Contact__r.LastName,
&apos;Not set&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>IF(NOT(ISBLANK(User__c)),  User__r.MobilePhone ,
IF(NOT(ISBLANK(Contact__c)),  Contact__r.MobilePhone ,
&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Project_Team_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/Salesforce_License__c.object-meta.xml
<CustomObject>
    <label>Salesforce License</label>
    <nameField>
        <displayFormat>SFL-{0000}</displayFormat>
        <label>Salesforce License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesforce_License__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <label>License</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Studio</fullName>
            </value>
            <value>
                <fullName>Agentforce</fullName>
            </value>
            <value>
                <fullName>Agentforce - Customer Service</fullName>
            </value>
            <value>
                <fullName>Agentforce - Marketing Campaigns</fullName>
            </value>
            <value>
                <fullName>Agentforce - Personal Shopper</fullName>
            </value>
            <value>
                <fullName>Agentforce - Sales Coach</fullName>
            </value>
            <value>
                <fullName>Agentforce - SDR</fullName>
            </value>
            <value>
                <fullName>API Access</fullName>
            </value>
            <value>
                <fullName>Channel Account Login</fullName>
            </value>
            <value>
                <fullName>Channel Account Member</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Login License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Member License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Plus Login License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2B Plus Member License</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud B2C</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud D2C</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>CPQ &amp; Billing</fullName>
            </value>
            <value>
                <fullName>CPQ for Customer Communities Login</fullName>
            </value>
            <value>
                <fullName>CPQ for Customer Communities Member</fullName>
            </value>
            <value>
                <fullName>CPQ for Partner Communities Login</fullName>
            </value>
            <value>
                <fullName>CPQ for Partner Communities Member</fullName>
            </value>
            <value>
                <fullName>CPQ Plus</fullName>
            </value>
            <value>
                <fullName>CPQ Plus &amp; Billing</fullName>
            </value>
            <value>
                <fullName>CRM Analytics Growth</fullName>
            </value>
            <value>
                <fullName>CRM Analytics Plus</fullName>
            </value>
            <value>
                <fullName>Customer Community Login</fullName>
            </value>
            <value>
                <fullName>Customer Community Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Salesforce_License__c/fields/Salesforce_License__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_License__c</fullName>
    <formula>HYPERLINK(Id, TEXT( License__c ) , &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Salesforce License</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Third_Party_Service__c/Third_Party_Service__c.object-meta.xml
<CustomObject>
    <label>Third Party Service</label>
    <nameField>
        <displayFormat>TPS-{00000}</displayFormat>
        <label>Third Party Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Third_Party_Service__c/fields/Est_Cost__c.field-meta.xml
<CustomField>
    <fullName>Est_Cost__c</fullName>
    <label>Est. Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Third_Party_Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aircall</fullName>
            </value>
            <value>
                <fullName>Blackthorn Payments</fullName>
            </value>
            <value>
                <fullName>BNF Drug Interaction Database</fullName>
            </value>
            <value>
                <fullName>Conga</fullName>
            </value>
            <value>
                <fullName>FormStack Documents</fullName>
            </value>
            <value>
                <fullName>FormStack Documents and eSign</fullName>
            </value>
            <value>
                <fullName>FormStack eSign</fullName>
            </value>
            <value>
                <fullName>FormStack Forms</fullName>
            </value>
            <value>
                <fullName>Gazela DM+D Medication Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Interactive Scheduler</fullName>
            </value>
            <value>
                <fullName>Gazela Job Board Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Microsoft Dynamics Integration Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Netsuite Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Sage Connector</fullName>
            </value>
            <value>
                <fullName>Gazela SAP Connector</fullName>
            </value>
            <value>
                <fullName>Gazela SharePoint app</fullName>
            </value>
            <value>
                <fullName>Gazela Signature Rx Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Stripe App</fullName>
            </value>
            <value>
                <fullName>Gazela Trustpilot Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Xero Connector</fullName>
            </value>
            <value>
                <fullName>Gazela Zoom Meeting Connector</fullName>
            </value>
            <value>
                <fullName>Gearset</fullName>
            </value>
            <value>
                <fullName>Gearset - CPQ+ and Billing</fullName>
            </value>
            <value>
                <fullName>Gearset - Enterprise</fullName>
            </value>
            <value>
                <fullName>Gearset - Salesforce Industries</fullName>
            </value>
            <value>
                <fullName>Gearset - Starter</fullName>
            </value>
            <value>
                <fullName>Gearset - Teams</fullName>
            </value>
            <value>
                <fullName>Impriviata</fullName>
            </value>
            <value>
                <fullName>InventoryWorks - Small Business Inventory Management</fullName>
            </value>
            <value>
                <fullName>IQVIA OneKey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Assumptions__c.field-meta.xml
<CustomField>
    <fullName>Assumptions__c</fullName>
    <label>Assumptions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>65000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Is_Optional__c.field-meta.xml
<CustomField>
    <fullName>Is_Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Separates the work item from the others, putting it in a &quot;Recommended Options&quot; section of the proposal and removes it from all the total estimates</inlineHelpText>
    <label>Is Optional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <formula>HYPERLINK(Id, Name + &apos; - &apos; + Subject__c, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Work Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PhaseProposalFactory.cls
public with sharing class PhaseProposalFactory {
    private final String THIRD_PARTY_SERVICE = 'Third-Party Service';

    public List<PhaseProposal.FeatureRow> createFeatures(List<Project_Feature__c> features) {
        return createFeatureRows(features, false);
    }

    public List<PhaseProposal.FeatureRow> createOptionalFeatures(List<Project_Feature__c> features) {
        return createFeatureRows(features, true);
    }

    private List<PhaseProposal.FeatureRow> createFeatureRows(List<Project_Feature__c> features, Boolean isOptional) {
        List<PhaseProposal.FeatureRow> featureRows = new List<PhaseProposal.FeatureRow>();

        for(Project_Feature__c feature : features) {
            List<PhaseProposal.WorkItemRow> workItems = new List<PhaseProposal.WorkItemRow>();
            Boolean isFirstRow = true;
            for(Work_Item__c workItem : feature.Work_Items__r) {
                if(workItem.Is_Optional__c == isOptional) {
                    workItems.add(new PhaseProposal.WorkItemRow(workItem, isFirstRow));
                    isFirstRow = false;
                }
            }
            if(workItems.size() > 0) {
                featureRows.add(new PhaseProposal.FeatureRow(feature, workItems));
            }
        }
        return featureRows;
    }

    public List<PhaseProposal.AssumptionRow> createAssumptions(List<Project_Feature__c> features) {
        List<PhaseProposal.AssumptionRow> assumptionRows = new List<PhaseProposal.AssumptionRow>();

        for(Project_Feature__c feature : features) {
            String assumptions = '';
            for(Work_Item__c workItem : feature.Work_Items__r) {
                if(String.isNotBlank(workItem.Assumptions__c)) {
                    assumptions += workItem.Assumptions__c.replace('<p><br></p>', '');
                }
            }
            if(String.isNotEmpty(assumptions)) {
                assumptionRows.add(new PhaseProposal.AssumptionRow(feature.Name, assumptions));
            }
        }
        return assumptionRows;
    }

    public List<PhaseProposal.ServiceRow> createServices(List<Third_Party_Service__c> source) {
        List<PhaseProposal.ServiceRow> target = new List<PhaseProposal.ServiceRow>();
        for(Third_Party_Service__c service : source) {
            target.add(createServiceRow(service));
        }
        return target;
    }

    private PhaseProposal.ServiceRow createServiceRow(Third_Party_Service__c source) {
        PhaseProposal.ServiceRow target = new PhaseProposal.ServiceRow();
        target.Name = source.Service__c;
        target.Description = String.isNotBlank(source.Description__c) ? source.Description__c.replace('<p><br></p>', '') : '';
        target.EstCost = source.Est_Cost__c;
        target.CurrencySymbol = CurrencyUtils.getSymbol(source.CurrencyIsoCode);
        return target;
    }

    public List<PhaseProposal.TeamMemberRow> createTeamMembers(List<Project_Team_Member__c> source) {
        List<PhaseProposal.TeamMemberRow> target = new List<PhaseProposal.TeamMemberRow>();
        for(Project_Team_Member__c member : source) {
            target.add(createTeamMemberRow(member));
        }
        return target;
    }

    private PhaseProposal.TeamMemberRow createTeamMemberRow(Project_Team_Member__c source) {
        PhaseProposal.TeamMemberRow target = new PhaseProposal.TeamMemberRow();
        target.Email = source.Email__c;
        target.Phone = source.Phone__c;
        target.Name = source.Name__c;
        target.Role = source.Role__c;
        return target;
    }

    public List<PhaseProposal.LicenseRow> createLicenses(List<Salesforce_License__c> source) {
        List<PhaseProposal.LicenseRow> target = new List<PhaseProposal.LicenseRow>();

        for(Salesforce_License__c license : source) {
            target.add(new PhaseProposal.LicenseRow(license.License__c, license.Quantity__c));
        }
        return target;
    }
}