force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FeatureCloneDataAccessTest.cls
@isTest
public class FeatureCloneDataAccessTest {
    @isTest
    public static void test_get_feature() {
        // Arrange
        Id accountId = AccountTestDataFactory.create('My Account');
        Id projectId = ProjectTestDataFactory.create(accountId, 'My Project', ProjectStatusNames.InProgress);
        Id featureId = ProjectFeatureTestDataFactory.create(projectId, 'My Feature');
        Id workItemId = WorkItemTestDataFactory.create(projectId, featureId);

        // Act
        Project_Feature__c feature = new FeatureCloneDataAccess().getFeature(featureId);

        // Assert
        System.assertEquals(featureId, feature.Id);
        System.assertEquals('My Feature', feature.Name);
        System.assertEquals(1, feature.Work_Items__r.size());
        System.assertEquals(workItemId, feature.Work_Items__r[0].Id);
    }
}