force-app/main/default/objects/Project_Feature__c/Project_Feature__c.object-meta.xml
<CustomObject>
    <label>Project Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Feature__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>R3 Digital Work Items</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>WI-{00000}</displayFormat>
        <label>Work Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Assumptions__c.field-meta.xml
<CustomField>
    <fullName>Assumptions__c</fullName>
    <label>Assumptions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Deliverables__c.field-meta.xml
<CustomField>
    <fullName>Deliverables__c</fullName>
    <label>Deliverables</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>65000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Est_Time__c.field-meta.xml
<CustomField>
    <fullName>Est_Time__c</fullName>
    <label>Est. Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Feature must belong to project</errorMessage>
        <filterItems>
            <field>$Source.Project__c</field>
            <operation>equals</operation>
            <valueField>Project_Feature__c.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Feature__c</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <label>Implementation</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Importance__c.field-meta.xml
<CustomField>
    <fullName>Importance__c</fullName>
    <description>Importance of the work item</description>
    <label>Importance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Importance</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Is_Optional__c.field-meta.xml
<CustomField>
    <fullName>Is_Optional__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Separates the work item from the others, putting it in a &quot;Recommended Options&quot; section of the proposal and removes it from all the total estimates</inlineHelpText>
    <label>Is Optional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Work Item</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Urgency__c.field-meta.xml
<CustomField>
    <fullName>Urgency__c</fullName>
    <description>Urgency of the work item</description>
    <label>Urgency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Urgency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/FeatureCloneDataAccess.cls
public with sharing class FeatureCloneDataAccess {
    public Project_Feature__c getFeature(Id featureId) {
        return [
            SELECT
                Id,
                Name,
                Description__c,
                (SELECT Id, Name, Assumptions__c, Deliverables__c, Description__c, Est_Time__c, Implementation__c, Importance__c, Is_Optional__c, Subject__c, Type__c, Urgency__c FROM Work_Items__r)
            FROM Project_Feature__c
            WHERE Id = :featureId
        ];
    }
}