force-app/main/default/objects/Wiki_Page__c/Wiki_Page__c.object-meta.xml
<CustomObject>
    <description>The wiki page object.</description>
    <label>Wiki Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wiki_Page__c/fields/Parent_Page__c.field-meta.xml
<CustomField>
    <fullName>Parent_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent wiki page for the wiki page.</description>
    <label>Parent Page</label>
    <referenceTo>Wiki_Page__c</referenceTo>
    <relationshipLabel>Wiki Pages</relationshipLabel>
    <relationshipName>Wiki_Pages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wiki_Page__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The sort order of the wiki page within its peer group.</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wiki_Page__c/fields/Wiki_Space__c.field-meta.xml
<CustomField>
    <fullName>Wiki_Space__c</fullName>
    <description>The wiki space to which the wiki page belongs.</description>
    <label>Wiki Space</label>
    <referenceTo>Wiki_Space__c</referenceTo>
    <relationshipLabel>Wiki Pages</relationshipLabel>
    <relationshipName>Wiki_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wiki_Space__c/Wiki_Space__c.object-meta.xml
<CustomObject>
    <description>A Wiki Space is a collection of related Wiki Pages</description>
    <label>Wiki Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Spaces</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/WikiSpaceController.cls
public with sharing class WikiSpaceController {
  @AuraEnabled(cacheable=true)
  public static Wiki_Page__c getHomepageBySpaceId(String spaceId) {
    try {
      if (String.isEmpty(spaceId)) {
        return null;
      }

      List<Wiki_Page__c> pages = [
        SELECT Id, Name, Wiki_Space__c, Wiki_Space__r.Name
        FROM Wiki_Page__c
        WHERE Wiki_Space__c = :spaceId AND Parent_page__c = NULL
        WITH SECURITY_ENFORCED
        ORDER BY Sort_Order__c ASC
        LIMIT 1
      ];

      if (pages.size() == 0) {
        return null;
      }

      return pages[0];
    } catch (Exception cause) {
      throw AuraHandledExceptionFactory.create(cause);
    }
  }

  @AuraEnabled
  public static Wiki_Page__c createHomepage(String spaceId) {
    try {
      if (
        !Schema.sObjectType.Wiki_Page__c.isCreateable() ||
        !Schema.sObjectType.Wiki_Page__c.fields.Name.isCreateable() ||
        !Schema.sObjectType.Wiki_Page__c.fields.Wiki_Space__c.isCreateable()
      ) {
        throw new DMLException(
          'Insufficient permissions to create Wiki_Page__c'
        );
      }

      Wiki_Page__c welcome = new Wiki_Page__c();
      welcome.Name = 'Welcome';
      welcome.Wiki_Space__c = spaceId;
      insert welcome;
      return welcome;
    } catch (Exception cause) {
      throw AuraHandledExceptionFactory.create(cause);
    }
  }
}