force-app/main/default/objects/Wiki_Page__c/Wiki_Page__c.object-meta.xml
<CustomObject>
    <description>The wiki page object.</description>
    <label>Wiki Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wiki_Page__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the wiki page.</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wiki_Page__c/fields/Parent_Page__c.field-meta.xml
<CustomField>
    <fullName>Parent_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent wiki page for the wiki page.</description>
    <label>Parent Page</label>
    <referenceTo>Wiki_Page__c</referenceTo>
    <relationshipLabel>Wiki Pages</relationshipLabel>
    <relationshipName>Wiki_Pages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wiki_Page__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The sort order of the wiki page within its peer group.</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wiki_Page__c/fields/Wiki_Space__c.field-meta.xml
<CustomField>
    <fullName>Wiki_Space__c</fullName>
    <description>The wiki space to which the wiki page belongs.</description>
    <label>Wiki Space</label>
    <referenceTo>Wiki_Space__c</referenceTo>
    <relationshipLabel>Wiki Pages</relationshipLabel>
    <relationshipName>Wiki_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wiki_Space__c/Wiki_Space__c.object-meta.xml
<CustomObject>
    <description>A Wiki Space is a collection of related Wiki Pages</description>
    <label>Wiki Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Spaces</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Wiki_Space__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the Wiki Space</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChangeSpaceModelController.cls
public with sharing class ChangeSpaceModelController {
  @AuraEnabled(cacheable=true)
  public static List<Wiki_Space__c> getSpaces() {
    try {
      List<Wiki_Space__c> spaces = [
        SELECT
          Id,
          Name,
          Description__c,
          (SELECT Id FROM Wiki_Pages__r ORDER BY Sort_Order__c ASC LIMIT 1)
        FROM Wiki_Space__c
        WITH SECURITY_ENFORCED
        ORDER BY Name ASC
      ];

      if (spaces.isEmpty()) {
        spaces.add(new Wiki_Space__c(Name = 'No Spaces Found'));
      }

      return spaces;
    } catch (Exception cause) {
      throw AuraHandledExceptionFactory.create(cause);
    }
  }
}