force-app/main/default/objects/Wiki_Page__c/Wiki_Page__c.object-meta.xml
<CustomObject>
    <description>The wiki page object.</description>
    <label>Wiki Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wiki_Page__c/fields/Parent_Page__c.field-meta.xml
<CustomField>
    <fullName>Parent_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The parent wiki page for the wiki page.</description>
    <label>Parent Page</label>
    <referenceTo>Wiki_Page__c</referenceTo>
    <relationshipLabel>Wiki Pages</relationshipLabel>
    <relationshipName>Wiki_Pages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wiki_Page__c/fields/Wiki_Space__c.field-meta.xml
<CustomField>
    <fullName>Wiki_Space__c</fullName>
    <description>The wiki space to which the wiki page belongs.</description>
    <label>Wiki Space</label>
    <referenceTo>Wiki_Space__c</referenceTo>
    <relationshipLabel>Wiki Pages</relationshipLabel>
    <relationshipName>Wiki_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wiki_Space__c/Wiki_Space__c.object-meta.xml
<CustomObject>
    <description>A Wiki Space is a collection of related Wiki Pages</description>
    <label>Wiki Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Spaces</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/WikiNavController.cls
public with sharing class WikiNavController {
  @AuraEnabled
  public static Boolean hasChildPages(Id recordId) {
    try {
      List<Wiki_Page__c> pages = [
        SELECT Id
        FROM Wiki_Page__c
        WHERE Parent_Page__c = :recordId
        WITH SECURITY_ENFORCED
      ];
      return pages.size() > 0;
    } catch (Exception cause) {
      throw AuraHandledExceptionFactory.create(cause);
    }
  }

  @AuraEnabled
  public static Boolean isFinalPage(Id spaceId, Id pageId) {
    try {
      List<Wiki_Page__c> pages = [
        SELECT Id
        FROM Wiki_Page__c
        WHERE Wiki_Space__c = :spaceId AND Id != :pageId
        WITH SECURITY_ENFORCED
      ];
      if (pages.size() == 0) {
        return true;
      }
      return false;
    } catch (Exception cause) {
      throw AuraHandledExceptionFactory.create(cause);
    }
  }
}