force-app/main/default/objects/Wiki_Page__c/Wiki_Page__c.object-meta.xml
<CustomObject>
    <description>The wiki page object.</description>
    <label>Wiki Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wiki_Page__c/fields/Wiki_Space__c.field-meta.xml
<CustomField>
    <fullName>Wiki_Space__c</fullName>
    <description>The wiki space to which the wiki page belongs.</description>
    <label>Wiki Space</label>
    <referenceTo>Wiki_Space__c</referenceTo>
    <relationshipLabel>Wiki Pages</relationshipLabel>
    <relationshipName>Wiki_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wiki_Space__c/Wiki_Space__c.object-meta.xml
<CustomObject>
    <description>A Wiki Space is a collection of related Wiki Pages</description>
    <label>Wiki Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Spaces</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/WikiSpaceTriggerHandler.cls
public with sharing class WikiSpaceTriggerHandler extends TriggerHandler {
  public override void afterInsert() {
    createWelcomePages((List<Wiki_Space__c>) Trigger.new);
  }

  private void createWelcomePages(List<Wiki_Space__c> spaces) {
    if (
      !Schema.sObjectType.Wiki_Page__c.isCreateable() ||
      !Schema.sObjectType.Wiki_Page__c.fields.Name.isCreateable() ||
      !Schema.sObjectType.Wiki_Page__c.fields.Wiki_Space__c.isCreateable()
    ) {
      throw new DMLException('Insufficient permissions to create Wiki_Page__c');
    }

    List<Wiki_Page__c> pages = new List<Wiki_Page__c>();
    for (Wiki_Space__c space : spaces) {
      Wiki_Page__c welcome = new Wiki_Page__c();
      welcome.Name = 'Welcome';
      welcome.Wiki_Space__c = space.Id;
      pages.add(welcome);
    }
    insert pages;
  }
}