force-app/main/default/objects/Wiki_Page__c/Wiki_Page__c.object-meta.xml
<CustomObject>
    <description>The wiki page object.</description>
    <label>Wiki Page</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wiki_Page__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the wiki page.</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wiki_Page__c/fields/Wiki_Space__c.field-meta.xml
<CustomField>
    <fullName>Wiki_Space__c</fullName>
    <description>The wiki space to which the wiki page belongs.</description>
    <label>Wiki Space</label>
    <referenceTo>Wiki_Space__c</referenceTo>
    <relationshipLabel>Wiki Pages</relationshipLabel>
    <relationshipName>Wiki_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wiki_Space__c/Wiki_Space__c.object-meta.xml
<CustomObject>
    <description>A Wiki Space is a collection of related Wiki Pages</description>
    <label>Wiki Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wiki Spaces</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Wiki_Space__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the Wiki Space</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
// This is a test data factory class
public class TestDataFactory {
  public static Id createSpace() {
    Wiki_Space__c space = new Wiki_Space__c();
    space.Name = 'Test Name';
    space.Description__c = 'Test Description';
    insert space;
    return space.Id;
  }

  public static Id createPage(Id spaceId) {
    Wiki_Page__c wikiPage = new Wiki_Page__c();
    wikiPage.Name = 'Test Page';
    wikiPage.Wiki_Space__c = spaceId;
    insert wikiPage;
    return wikiPage.Id;
  }
}